In [1]:
import pandas as pd

import matplotlib.pyplot as plt

import matplotlib as mpl

import numpy as np

%matplotlib inline

plt.style.use('ggplot')

pd.set_option('precision',3)

from IPython.display import display, HTML

pd.__version__

u'0.17.1'

In [2]:
CoastalID = pd.read_csv("CoastalID.csv")
Production = pd.read_csv("ProduccionBrutaTotal.csv")
AddedValue = pd.read_csv("ValorAgregadoBruto.csv")
Municipios = pd.read_csv("Coastal_municipio.csv")

In [3]:
Production.columns.values

array(['Clave de la entidad federativa', 'Entidad federativa',
       'Clave del municipio', 'Municipio', 'Year', 'TotalProduction'], dtype=object)

In [4]:
AddedValue.columns.values

array(['Clave de la entidad federativa', 'Entidad federativa',
       'Clave del municipio', 'Municipio', 'Year', 'AddedValue'], dtype=object)

In [5]:
Municipios.columns.values

array(['Clave de la entidad federativa', 'Entidad federativa',
       'Clave del municipio', 'Municipio', 'Coastal'], dtype=object)

In [6]:


Production_Value = pd.merge(
    left=Production, 
    right=AddedValue, 
    how='left'
)

In [7]:

Product_Value = pd.merge(
    left=Production_Value, 
    right=CoastalID, 
    how='left'
)

In [8]:
Product_Value['EconomicImpact'] = Product_Value['TotalProduction']+Product_Value['AddedValue']

In [9]:
Product_Value['Multiplier'] = Product_Value['EconomicImpact'] / Product_Value['TotalProduction']

In [10]:
Product_Value.columns.values

array(['Clave de la entidad federativa', 'Entidad federativa',
       'Clave del municipio', 'Municipio', 'Year', 'TotalProduction',
       'AddedValue', 'Ocean', 'OceanName', 'EconomicImpact', 'Multiplier'], dtype=object)

In [11]:
Product_Value = pd.merge(
    left=Product_Value, 
    right=Municipios, 
    how='left'
)

In [12]:
Product_Value

,Clave de la entidad federativa,Entidad federativa,Clave del municipio,Municipio,Year,TotalProduction,AddedValue,Ocean,OceanName,EconomicImpact,Multiplier,Coastal
0,0,Nacional,0,Nacional,2008,18649362,9559697,0,NaN,28209059,1.513,NaN
1,1,Aguascalientes,0,Estatal,2008,11616,8988,0,NaN,20604,1.774,NaN
2,1,Aguascalientes,1,Aguascalientes,2008,1704,23,0,NaN,1727,1.013,NaN
3,1,Aguascalientes,3,Calvillo,2008,199,166,0,NaN,365,1.834,NaN
4,1,Aguascalientes,5,Jesús María,2008,156,104,0,NaN,260,1.667,NaN
5,1,Aguascalientes,6,Pabellón de Arteaga,2008,NaN,NaN,0,NaN,NaN,NaN,NaN
6,1,Aguascalientes,7,Rincón de Romos,2008,6527,6067,0,NaN,12594,1.930,NaN
7,1,Aguascalientes,8,San José de Gracia,2008,3030,2628,0,NaN,5658,1.867,NaN
8,1,Aguascalientes,11,San Francisco de los Romo,2008,NaN,NaN,0,NaN,NaN,NaN,NaN
9,2,Baja California,0,Estatal,2008,1010294,528727,1,Pacific,1539021,1.523,1
10,2,Baja California,1,Ensenada,2008,869876,456292,1,Pacific,1326168,1.525,1
11,2,Baja California,2,Mexicali,2008,72149,44345,1,Pacific,116494,1.615,1
12,2,Baja California,4,Tijuana,2008,59558,22948,1,Pacific,82506,1.385,1
13,2,Baja California,5,Playas de Rosarito,2008,8711,5142,1,Pacific,13853,1.590,1
14,3,Baja California Sur,0,Estatal,2008,1070835,760807,1,Pacific,1831642,1.710,1
15,3,Baja California Sur,1,Comondú,2008,201984,128569,1,Pacific,330553,1.637,1
16,3,Baja California Sur,2,Mulegé,2008,513994,421306,1,Pacific,935300,1.820,1
17,3,Baja California Sur,3,La Paz,2008,287545,170827,1,Pacific,458372,1.594,1
18,3,Baja California Sur,8,Los Cabos,2008,35601,20827,1,Pacific,56428,1.585,1
19,3,Baja California Sur,9,Loreto,2008,31711,19278,1,Pacific,50989,1.608,1
20,4,Campeche,0,Estatal,2008,597028,311946,1,Atlantic,908974,1.522,1
21,4,Campeche,1,Calkiní,2008,19296,9372,1,Atlantic,28668,1.486,0
22,4,Campeche,2,Campeche,2008,222027,89713,1,Atlantic,311740,1.404,1
23,4,Campeche,3,Carmen,2008,201420,115582,1,Atlantic,317002,1.574,1
24,4,Campeche,4,Champotón,2008,146872,92824,1,Atlantic,239696,1.632,1
25,4,Campeche,7,Palizada,2008,6278,3789,1,Atlantic,10067,1.604,1
26,4,Campeche,8,Tenabo,2008,NaN,NaN,1,Atlantic,NaN,NaN,1
27,4,Campeche,9,Escárcega,2008,581,444,1,Atlantic,1025,1.764,0
28,4,Campeche,10,Calakmul,2008,56,11,1,Atlantic,67,1.196,0
29,4,Campeche,11,Candelaria,2008,498,211,1,Atlantic,709,1.424,0
...,...,...,...,...,...,...,...,...,...,...,...,...
3363,31,Yucatán,102,Valladolid,2003,NaN,NaN,1,Atlantic,NaN,NaN,0
3364,31,Yucatán,105,Yaxkukul,2003,NaN,NaN,1,Atlantic,NaN,NaN,0
3365,31,Yucatán,106,Yobaín,2003,2274,1039,1,Atlantic,3313,1.457,1
3366,32,Zacatecas,0,Estatal,2003,4932,4034,0,NaN,8966,1.818,NaN
3367,32,Zacatecas,1,Apozol,2003,286,242,0,NaN,528,1.846,NaN
3368,32,Zacatecas,2,Apulco,2003,200,172,0,NaN,372,1.860,NaN
3369,32,Zacatecas,5,Calera,2003,NaN,NaN,0,NaN,NaN,NaN,NaN
3370,32,Zacatecas,10,Fresnillo,2003,511,417,0,NaN,928,1.816,NaN
3371,32,Zacatecas,17,Guadalupe,2003,NaN,NaN,0,NaN,NaN,NaN,NaN
3372,32,Zacatecas,19,Jalpa,2003,251,213,0,NaN,464,1.849,NaN
3373,32,Zacatecas,20,Jerez,2003,106,92,0,NaN,198,1.868,NaN
3374,32,Zacatecas,22,Juan Aldama,2003,NaN,NaN,0,NaN,NaN,NaN,NaN
3375,32,Zacatecas,24,Loreto,2003,20,17,0,NaN,37,1.850,NaN
3376,32,Zacatecas,29,Miguel Auza,2003,117,86,0,NaN,203,1.735,NaN
3377,32,Zacatecas,33,Moyahua de Estrada,2003,4,3,0,NaN,7,1.750,NaN
3378,32,Zacatecas,34,Nochistlán de Mejía,2003,468,403,0,NaN,871,1.861,NaN
3379,32,Zacatecas,39,Río Grande,2003,NaN,NaN,0,NaN,NaN,NaN,NaN
3380,32,Zacatecas,40,Sain Alto,2003,269,199,0,NaN,468,1.740,NaN
3381,32,Zacatecas,42,Sombrerete,2003,50,34,0,NaN,84,1.680,NaN
3382,32,Zacatecas,43,Susticacán,2003,70,65,0,NaN,135,1.929,NaN
3383,32,Zacatecas,44,Tabasco,2003,683,643,0,NaN,1326,1.941,NaN
3384,32,Zacatecas,45,Tepechitlán,2003,316,243,0,NaN,559,1.769,NaN
3385,32,Zacatecas,46,Tepetongo,2003,NaN,NaN,0,NaN,NaN,NaN,NaN
3386,32,Zacatecas,47,Teúl de González Ortega,2003,NaN,NaN,0,NaN,NaN,NaN,NaN
3387,32,Zacatecas,48,Tlaltenango de Sánchez Román,2003,NaN,NaN,0,NaN,NaN,NaN,NaN
3388,32,Zacatecas,49,Valparaíso,2003,106,76,0,NaN,182,1.717,NaN
3389,32,Zacatecas,51,Villa de Cos,2003,NaN,NaN,0,NaN,NaN,NaN,NaN
3390,32,Zacatecas,52,Villa García,2003,72,72,0,NaN,144,2.000,NaN
3391,32,Zacatecas,55,Villanueva,2003,1376,1046,0,NaN,2422,1.760,NaN
3392,32,Zacatecas,56,Zacatecas,2003,27,11,0,NaN,38,1.407,NaN

In [13]:
Product_Value.to_csv('Multiplier.csv')