In [58]:
%matplotlib inline

import pandas as pd

import matplotlib.pyplot as plt

import numpy

pd.__version__

u'0.17.0'

In [59]:
pd.read_csv("SSFsubsidiesnonfuel.csv")

,ID,Cnumber,RegionID,RegionName,Type,SubType,Category,ReEst_Subsidy2009,NewData,Developed,HDI_2005,Countries,%SSFsubsidies_assessed,weighted_by_sectorsize,Data_group,%SSF_totalCatch_EEZ,%SSF_totalCatch_Country,SSF_USD_1000
0,1418,608,2,Asia,A1,Fisheries mangt.,Good,150317.400345,False,Developing,0.771,Philippines,28.662420,TRUE,3,28.662420,25.475502,43084.605195
1,1419,608,2,Asia,A2,Fishery R&D,Good,106929.633393,False,Developing,0.771,Philippines,25.475502,TRUE,3,28.662420,25.475502,27240.860867
2,1420,608,2,Asia,A3,MPAs,Good,14325.450291,False,Developing,0.771,Philippines,28.662420,TRUE,3,28.662420,25.475502,4106.020784
3,1421,608,2,Asia,B1,Boat constsruct. & renov.,Bad,291723.649784,False,Developing,0.771,Philippines,25.475502,TRUE,3,28.662420,25.475502,74318.064163
4,1422,608,2,Asia,B2,Fisheries dev. projects,Bad,5987.405124,True,Developing,0.771,Philippines,25.475502,TRUE,3,28.662420,25.475502,1525.321511
5,1423,608,2,Asia,B3,Fishing port develop.,Bad,0.000000,False,Developing,0.771,Philippines,NaN,NaN,NaN,28.662420,25.475502,NaN
6,1424,608,2,Asia,B4,Markt. & storage infrast.,Bad,2305.468110,False,Developing,0.771,Philippines,20.000000,FALSE,1,28.662420,25.475502,461.093622
7,1425,608,2,Asia,B5,Tax exemption,Bad,92663.171127,False,Developing,0.771,Philippines,0.000000,FALSE,2,28.662420,25.475502,0.000000
8,1426,608,2,Asia,B6,Fishing access,Bad,0.000000,False,Developing,0.771,Philippines,NaN,NaN,NaN,28.662420,25.475502,NaN
9,1428,608,2,Asia,C1,Fisher assistance,Ugly,35605.265432,True,Developing,0.771,Philippines,100.000000,FALSE,1,28.662420,25.475502,35605.265432
10,1429,608,2,Asia,C2,Vessel buyback,Ugly,0.000000,False,Developing,0.771,Philippines,NaN,NaN,NaN,28.662420,25.475502,NaN
11,1430,608,2,Asia,C3,Rural fisher communities,Ugly,21737.044519,False,Developing,0.771,Philippines,100.000000,FALSE,1,28.662420,25.475502,21737.044519
12,820,356,2,Asia,A1,Fisheries mangt.,Good,6450.238140,True,Developing,0.619,India,42.381331,TRUE,3,42.381331,41.498407,2733.696798
13,821,356,2,Asia,A2,Fishery R&D,Good,2179.113474,True,Developing,0.619,India,41.498407,TRUE,3,42.381331,41.498407,904.297382
14,822,356,2,Asia,A3,MPAs,Good,1781.843735,False,Developing,0.619,India,42.381331,TRUE,3,42.381331,41.498407,755.169097
15,823,356,2,Asia,B1,Boat constsruct. & renov.,Bad,4035.395412,True,Developing,0.619,India,0.000000,FALSE,2,42.381331,41.498407,0.000000
16,824,356,2,Asia,B2,Fisheries dev. projects,Bad,3751.334747,True,Developing,0.619,India,20.000000,FALSE,1,42.381331,41.498407,750.266949
17,825,356,2,Asia,B3,Fishing port develop.,Bad,4062.029933,True,Developing,0.619,India,17.000000,FALSE,1,42.381331,41.498407,690.545089
18,826,356,2,Asia,B4,Markt. & storage infrast.,Bad,4035.395412,True,Developing,0.619,India,25.000000,FALSE,1,42.381331,41.498407,1008.848853
19,827,356,2,Asia,B5,Tax exemption,Bad,123957.406261,False,Developing,0.619,India,20.000000,FALSE,1,42.381331,41.498407,24791.481252
20,828,356,2,Asia,B6,Fishing access,Bad,0.000000,False,Developing,0.619,India,NaN,NaN,NaN,42.381331,41.498407,NaN
21,830,356,2,Asia,C1,Fisher assistance,Ugly,5084.598507,True,Developing,0.619,India,41.498407,TRUE,3,42.381331,41.498407,2110.027391
22,831,356,2,Asia,C2,Vessel buyback,Ugly,0.000000,False,Developing,0.619,India,NaN,NaN,NaN,42.381331,41.498407,NaN
23,832,356,2,Asia,C3,Rural fisher communities,Ugly,2905.485033,True,Developing,0.619,India,100.000000,FALSE,1,42.381331,41.498407,2905.485033
24,1756,764,2,Asia,A1,Fisheries mangt.,Good,18538.640909,False,Developing,0.781,Thailand,42.279905,TRUE,3,42.279905,13.560304,7838.119773
25,1757,764,2,Asia,A2,Fishery R&D,Good,2067.787646,False,Developing,0.781,Thailand,13.560304,TRUE,3,42.279905,13.560304,280.398288
26,1758,764,2,Asia,A3,MPAs,Good,2884.411251,False,Developing,0.781,Thailand,42.279905,TRUE,3,42.279905,13.560304,1219.526338
27,1759,764,2,Asia,B1,Boat constsruct. & renov.,Bad,58456.068748,False,Developing,0.781,Thailand,25.000000,FALSE,1,42.279905,13.560304,14614.017187
28,1760,764,2,Asia,B2,Fisheries dev. projects,Bad,242.934986,True,Developing,0.781,Thailand,13.560304,TRUE,3,42.279905,13.560304,32.942722
29,1761,764,2,Asia,B3,Fishing port develop.,Bad,8015.852723,True,Developing,0.781,Thailand,0.000000,FALSE,2,42.279905,13.560304,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
774,1502,642,1,Europe,B4,Markt. & storage infrast.,Bad,25694.478873,True,Developing,0.813,Romania,1.300000,1,3,91.666667,1.269394,334.028225
775,1503,642,1,Europe,B5,Tax exemption,Bad,47.431407,False,Developing,0.813,Romania,1.300000,1,3,91.666667,1.269394,0.616608
776,1504,642,1,Europe,B6,Fishing access,Bad,0.000000,False,Developing,0.813,Romania,NaN,NaN,NaN,91.666667,1.269394,NaN
777,1506,642,1,Europe,C1,Fisher assistance,Ugly,10.566188,True,Developing,0.813,Romania,1.300000,1,3,91.666667,1.269394,0.137360
778,1507,642,1,Europe,C2,Vessel buyback,Ugly,0.000000,False,Developing,0.813,Romania,NaN,NaN,NaN,91.666667,1.269394,NaN
779,1508,642,1,Europe,C3,Rural fisher communities,Ugly,0.000000,False,Developing,0.813,Romania,NaN,NaN,NaN,91.666667,1.269394,NaN
780,1860,804,1,Europe,A1,Fisheries mangt.,Good,9039.338360,False,Developing,0.788,Ukraine,10.300000,1,3,10.292729,3.028619,931.051851
781,1861,804,1,Europe,A2,Fishery R&D,Good,0.000000,False,Developing,0.788,Ukraine,NaN,NaN,NaN,10.292729,3.028619,NaN
782,1862,804,1,Europe,A3,MPAs,Good,815.509180,False,Developing,0.788,Ukraine,10.300000,1,3,10.292729,3.028619,83.997446
783,1863,804,1,Europe,B1,Boat constsruct. & renov.,Bad,16357.036931,False,Developing,0.788,Ukraine,3.000000,1,3,10.292729,3.028619,490.711108
784,1864,804,1,Europe,B2,Fisheries dev. projects,Bad,6.506637,True,Developing,0.788,Ukraine,3.000000,1,3,10.292729,3.028619,0.195199
785,1865,804,1,Europe,B3,Fishing port develop.,Bad,0.000000,False,Developing,0.788,Ukraine,NaN,NaN,NaN,10.292729,3.028619,NaN
786,1866,804,1,Europe,B4,Markt. & storage infrast.,Bad,0.000000,False,Developing,0.788,Ukraine,NaN,NaN,NaN,10.292729,3.028619,NaN
787,1867,804,1,Europe,B5,Tax exemption,Bad,0.000000,False,Developing,0.788,Ukraine,NaN,NaN,NaN,10.292729,3.028619,NaN
788,1868,804,1,Europe,B6,Fishing access,Bad,0.000000,False,Developing,0.788,Ukraine,NaN,NaN,NaN,10.292729,3.028619,NaN
789,1870,804,1,Europe,C1,Fisher assistance,Ugly,0.000000,False,Developing,0.788,Ukraine,NaN,NaN,NaN,10.292729,3.028619,NaN
790,1871,804,1,Europe,C2,Vessel buyback,Ugly,0.000000,False,Developing,0.788,Ukraine,NaN,NaN,NaN,10.292729,3.028619,NaN
791,1872,804,1,Europe,C3,Rural fisher communities,Ugly,1218.802917,False,Developing,0.788,Ukraine,100.000000,0,3,10.292729,3.028619,1218.802917
792,469,208,1,Europe,A1,Fisheries mangt.,Good,27710.195182,True,Developed,0.949,Denmark,7.800000,1,3,7.759108,6.799901,2161.395224
793,470,208,1,Europe,A2,Fishery R&D,Good,12472.157835,True,Developed,0.949,Denmark,7.800000,1,3,7.759108,6.799901,972.828311
794,471,208,1,Europe,A3,MPAs,Good,27261.643121,False,Developed,0.949,Denmark,7.800000,1,3,7.759108,6.799901,2126.408163
795,472,208,1,Europe,B1,Boat constsruct. & renov.,Bad,26508.544867,True,Developed,0.949,Denmark,6.800000,1,3,7.759108,6.799901,1802.581051
796,473,208,1,Europe,B2,Fisheries dev. projects,Bad,0.000000,True,Developed,0.949,Denmark,NaN,NaN,NaN,7.759108,6.799901,NaN
797,474,208,1,Europe,B3,Fishing port develop.,Bad,0.000000,False,Developed,0.949,Denmark,NaN,NaN,NaN,7.759108,6.799901,NaN
798,475,208,1,Europe,B4,Markt. & storage infrast.,Bad,18192.846849,True,Developed,0.949,Denmark,18.300000,0,2,7.759108,6.799901,3329.290973
799,476,208,1,Europe,B5,Tax exemption,Bad,0.000000,False,Developed,0.949,Denmark,NaN,NaN,NaN,7.759108,6.799901,NaN
800,477,208,1,Europe,B6,Fishing access,Bad,2867.290462,True,Developed,0.949,Denmark,0.000000,1,3,7.759108,6.799901,0.000000
801,479,208,1,Europe,C1,Fisher assistance,Ugly,23594.021906,True,Developed,0.949,Denmark,5.100000,0,2,7.759108,6.799901,1203.295117
802,480,208,1,Europe,C2,Vessel buyback,Ugly,7601.016403,True,Developed,0.949,Denmark,0.000000,0,3,7.759108,6.799901,0.000000
803,481,208,1,Europe,C3,Rural fisher communities,Ugly,0.000000,False,Developed,0.949,Denmark,NaN,NaN,NaN,7.759108,6.799901,NaN

In [60]:
subsidies = pd.read_csv("SSFsubsidiesnonfuel.csv")

subsidies.head()

,ID,Cnumber,RegionID,RegionName,Type,SubType,Category,ReEst_Subsidy2009,NewData,Developed,HDI_2005,Countries,%SSFsubsidies_assessed,weighted_by_sectorsize,Data_group,%SSF_totalCatch_EEZ,%SSF_totalCatch_Country,SSF_USD_1000
0,1418,608,2,Asia,A1,Fisheries mangt.,Good,150317.400345,False,Developing,0.771,Philippines,28.662420,TRUE,3,28.66242,25.475502,43084.605195
1,1419,608,2,Asia,A2,Fishery R&D,Good,106929.633393,False,Developing,0.771,Philippines,25.475502,TRUE,3,28.66242,25.475502,27240.860867
2,1420,608,2,Asia,A3,MPAs,Good,14325.450291,False,Developing,0.771,Philippines,28.662420,TRUE,3,28.66242,25.475502,4106.020784
3,1421,608,2,Asia,B1,Boat constsruct. & renov.,Bad,291723.649784,False,Developing,0.771,Philippines,25.475502,TRUE,3,28.66242,25.475502,74318.064163
4,1422,608,2,Asia,B2,Fisheries dev. projects,Bad,5987.405124,True,Developing,0.771,Philippines,25.475502,TRUE,3,28.66242,25.475502,1525.321511

In [61]:
subsidies_short = subsidies.loc[:,['RegionName', 'Countries', 'Type','ReEst_Subsidy2009','%SSFsubsidies_assessed', 'SSF_USD_1000','weighted_by_sectorsize', 'Data_group','%SSF_totalCatch_EEZ','%SSF_totalCatch_Country']]

In [62]:
subsidies_short

,RegionName,Countries,Type,ReEst_Subsidy2009,%SSFsubsidies_assessed,SSF_USD_1000,weighted_by_sectorsize,Data_group,%SSF_totalCatch_EEZ,%SSF_totalCatch_Country
0,Asia,Philippines,A1,150317.400345,28.662420,43084.605195,TRUE,3,28.662420,25.475502
1,Asia,Philippines,A2,106929.633393,25.475502,27240.860867,TRUE,3,28.662420,25.475502
2,Asia,Philippines,A3,14325.450291,28.662420,4106.020784,TRUE,3,28.662420,25.475502
3,Asia,Philippines,B1,291723.649784,25.475502,74318.064163,TRUE,3,28.662420,25.475502
4,Asia,Philippines,B2,5987.405124,25.475502,1525.321511,TRUE,3,28.662420,25.475502
5,Asia,Philippines,B3,0.000000,NaN,NaN,NaN,NaN,28.662420,25.475502
6,Asia,Philippines,B4,2305.468110,20.000000,461.093622,FALSE,1,28.662420,25.475502
7,Asia,Philippines,B5,92663.171127,0.000000,0.000000,FALSE,2,28.662420,25.475502
8,Asia,Philippines,B6,0.000000,NaN,NaN,NaN,NaN,28.662420,25.475502
9,Asia,Philippines,C1,35605.265432,100.000000,35605.265432,FALSE,1,28.662420,25.475502
10,Asia,Philippines,C2,0.000000,NaN,NaN,NaN,NaN,28.662420,25.475502
11,Asia,Philippines,C3,21737.044519,100.000000,21737.044519,FALSE,1,28.662420,25.475502
12,Asia,India,A1,6450.238140,42.381331,2733.696798,TRUE,3,42.381331,41.498407
13,Asia,India,A2,2179.113474,41.498407,904.297382,TRUE,3,42.381331,41.498407
14,Asia,India,A3,1781.843735,42.381331,755.169097,TRUE,3,42.381331,41.498407
15,Asia,India,B1,4035.395412,0.000000,0.000000,FALSE,2,42.381331,41.498407
16,Asia,India,B2,3751.334747,20.000000,750.266949,FALSE,1,42.381331,41.498407
17,Asia,India,B3,4062.029933,17.000000,690.545089,FALSE,1,42.381331,41.498407
18,Asia,India,B4,4035.395412,25.000000,1008.848853,FALSE,1,42.381331,41.498407
19,Asia,India,B5,123957.406261,20.000000,24791.481252,FALSE,1,42.381331,41.498407
20,Asia,India,B6,0.000000,NaN,NaN,NaN,NaN,42.381331,41.498407
21,Asia,India,C1,5084.598507,41.498407,2110.027391,TRUE,3,42.381331,41.498407
22,Asia,India,C2,0.000000,NaN,NaN,NaN,NaN,42.381331,41.498407
23,Asia,India,C3,2905.485033,100.000000,2905.485033,FALSE,1,42.381331,41.498407
24,Asia,Thailand,A1,18538.640909,42.279905,7838.119773,TRUE,3,42.279905,13.560304
25,Asia,Thailand,A2,2067.787646,13.560304,280.398288,TRUE,3,42.279905,13.560304
26,Asia,Thailand,A3,2884.411251,42.279905,1219.526338,TRUE,3,42.279905,13.560304
27,Asia,Thailand,B1,58456.068748,25.000000,14614.017187,FALSE,1,42.279905,13.560304
28,Asia,Thailand,B2,242.934986,13.560304,32.942722,TRUE,3,42.279905,13.560304
29,Asia,Thailand,B3,8015.852723,0.000000,0.000000,FALSE,2,42.279905,13.560304
...,...,...,...,...,...,...,...,...,...,...
774,Europe,Romania,B4,25694.478873,1.300000,334.028225,1,3,91.666667,1.269394
775,Europe,Romania,B5,47.431407,1.300000,0.616608,1,3,91.666667,1.269394
776,Europe,Romania,B6,0.000000,NaN,NaN,NaN,NaN,91.666667,1.269394
777,Europe,Romania,C1,10.566188,1.300000,0.137360,1,3,91.666667,1.269394
778,Europe,Romania,C2,0.000000,NaN,NaN,NaN,NaN,91.666667,1.269394
779,Europe,Romania,C3,0.000000,NaN,NaN,NaN,NaN,91.666667,1.269394
780,Europe,Ukraine,A1,9039.338360,10.300000,931.051851,1,3,10.292729,3.028619
781,Europe,Ukraine,A2,0.000000,NaN,NaN,NaN,NaN,10.292729,3.028619
782,Europe,Ukraine,A3,815.509180,10.300000,83.997446,1,3,10.292729,3.028619
783,Europe,Ukraine,B1,16357.036931,3.000000,490.711108,1,3,10.292729,3.028619
784,Europe,Ukraine,B2,6.506637,3.000000,0.195199,1,3,10.292729,3.028619
785,Europe,Ukraine,B3,0.000000,NaN,NaN,NaN,NaN,10.292729,3.028619
786,Europe,Ukraine,B4,0.000000,NaN,NaN,NaN,NaN,10.292729,3.028619
787,Europe,Ukraine,B5,0.000000,NaN,NaN,NaN,NaN,10.292729,3.028619
788,Europe,Ukraine,B6,0.000000,NaN,NaN,NaN,NaN,10.292729,3.028619
789,Europe,Ukraine,C1,0.000000,NaN,NaN,NaN,NaN,10.292729,3.028619
790,Europe,Ukraine,C2,0.000000,NaN,NaN,NaN,NaN,10.292729,3.028619
791,Europe,Ukraine,C3,1218.802917,100.000000,1218.802917,0,3,10.292729,3.028619
792,Europe,Denmark,A1,27710.195182,7.800000,2161.395224,1,3,7.759108,6.799901
793,Europe,Denmark,A2,12472.157835,7.800000,972.828311,1,3,7.759108,6.799901
794,Europe,Denmark,A3,27261.643121,7.800000,2126.408163,1,3,7.759108,6.799901
795,Europe,Denmark,B1,26508.544867,6.800000,1802.581051,1,3,7.759108,6.799901
796,Europe,Denmark,B2,0.000000,NaN,NaN,NaN,NaN,7.759108,6.799901
797,Europe,Denmark,B3,0.000000,NaN,NaN,NaN,NaN,7.759108,6.799901
798,Europe,Denmark,B4,18192.846849,18.300000,3329.290973,0,2,7.759108,6.799901
799,Europe,Denmark,B5,0.000000,NaN,NaN,NaN,NaN,7.759108,6.799901
800,Europe,Denmark,B6,2867.290462,0.000000,0.000000,1,3,7.759108,6.799901
801,Europe,Denmark,C1,23594.021906,5.100000,1203.295117,0,2,7.759108,6.799901
802,Europe,Denmark,C2,7601.016403,0.000000,0.000000,0,3,7.759108,6.799901
803,Europe,Denmark,C3,0.000000,NaN,NaN,NaN,NaN,7.759108,6.799901

In [63]:
subsidies_short.groupby('Countries').mean()

,ReEst_Subsidy2009,%SSFsubsidies_assessed,SSF_USD_1000,Data_group,%SSF_totalCatch_EEZ,%SSF_totalCatch_Country
Countries,,,,,,
Angola,10237.880012,46.600420,6109.903975,2.444444,44.575137,46.050702
Argentina,15979.380763,6.634602,611.834535,2.333333,16.685018,17.343202
Australia,35837.897925,28.869204,11879.476657,2.833333,19.461492,17.146119
Brazil,45608.799719,41.769922,22155.662561,2.222222,51.260412,52.316106
Cameroon,990.648636,59.840000,863.139366,NaN,74.771689,82.493703
Canada,91007.679915,4.643931,8063.195950,2.857143,6.131213,3.991331
Chile,11351.295369,35.358258,1709.074080,2.000000,69.392954,75.615910
China,210190.868001,17.032798,41477.915756,2.727273,35.600970,23.241135
Costa Rica,1073.009658,35.827459,845.831718,2.800000,25.350318,28.436658
Cuba,1346.602773,87.330906,4823.427914,3.000000,90.100000,81.792717
Denmark,12183.976386,6.700000,1449.474855,2.750000,7.759108,6.799901
Ecuador,4932.331802,14.998022,2178.627775,2.200000,21.900000,15.595055
Egypt,1127.413503,17.144118,518.710874,2.400000,27.060440,20.563674
France,34127.767835,19.513450,7426.333288,2.500000,40.432985,22.117134
Gabon,652.323399,58.671429,545.499090,2.428571,27.942422,63.461538
Ghana,4624.453590,65.787314,3360.967781,2.250000,56.467555,51.549627
Greece,16242.584746,38.352000,6414.687254,2.700000,59.786667,51.024124
Guinea,3288.542253,34.714286,1436.631677,2.285714,21.500000,75.952478
Guyana,5122.745877,50.739556,3592.673992,2.000000,51.700000,51.355662
Iceland,11101.947357,2.688381,624.343314,2.833333,3.534304,3.020560
India,13186.903388,34.975948,3664.981784,1.900000,42.381331,41.498407
Indonesia,35228.434495,28.834670,8011.045486,2.000000,22.323870,10.800000
Iran,18273.395463,63.648061,21317.400888,2.166667,58.052126,57.892057
Italy,22854.271894,10.847683,4740.709816,3.000000,14.656489,11.655200
Jamaica,1723.885137,100.000000,3447.770273,2.000000,100.000000,100.000000
Japan,374127.513827,23.394121,102663.265541,2.454545,23.586724,11.800000
Korea Rep,64341.036597,8.450000,10496.490943,2.200000,16.380902,17.293921
Madagascar,943.662988,57.175000,973.066951,2.250000,73.744951,83.311604
Malaysia,14868.794981,21.706250,4169.263199,2.125000,22.118858,29.133010
Mauritania,2172.164258,44.287500,1932.395514,2.125000,4.300000,38.465310
...,...,...,...,...,...,...
New Zealand,6236.045610,13.938178,5215.147006,3.000000,13.938178,22.236906
Nicaragua,1620.591055,30.421414,798.869744,2.333333,31.500000,21.800000
Nigeria,4318.805580,60.739052,5286.356928,2.250000,66.616027,68.156207
Norway,22984.137388,13.150000,4156.356467,2.625000,10.098171,8.287195
Panama,4079.933333,26.641002,1377.571636,2.333333,16.400000,13.523007
Papua N Guin,50869.420079,4.305707,1028.671581,2.125000,9.400476,15.640194
Peru,21497.898870,20.471699,6678.957072,2.125000,8.596049,9.334413
Philippines,60132.874011,39.305705,23119.808455,2.222222,28.662420,25.475502
Poland,32761.333460,4.737049,2291.121790,2.875000,11.944444,3.748910
Romania,4793.924519,35.200000,2592.223556,3.000000,91.666667,1.269394
Russian Fed,105606.848385,6.296975,6460.175954,2.375000,15.181599,16.068940
Saudi Arabia,2737.823284,65.783333,1892.328823,2.500000,64.926740,71.688574
Senegal,655.593497,48.016667,521.876046,2.166667,44.073841,50.575668
Seychelles,346.603044,26.600000,88.652629,2.200000,11.111111,8.970976
Sierra Leone,1433.326612,64.850000,1719.008575,2.250000,76.444043,80.769231
South Africa,2793.865418,8.143379,682.545162,3.000000,8.143379,8.143379
Spain,87672.317557,5.581822,3244.714927,2.300000,7.788784,2.664720
Sri Lanka,15658.776182,34.360000,17172.380793,2.200000,49.069849,52.457786
Suriname,1949.716690,73.877486,2982.741417,2.400000,51.891892,65.603645
Sweden,13316.042310,4.564919,845.201161,3.000000,5.259676,6.863597
Taiwan,19641.616463,15.050000,4181.085542,2.125000,23.400309,7.867387
Thailand,20751.304339,30.582302,5947.252696,2.222222,42.279905,13.560304
Tunisia,503.747685,23.678512,292.792155,2.800000,26.210526,26.433121
Turkey,8611.960294,27.066667,2148.807551,2.833333,16.188242,14.977017
UK,27065.342389,4.484090,1293.287501,2.800000,3.603992,8.057232
USA,333834.087210,17.028063,89570.155273,3.000000,26.719067,19.473750
Ukraine,2286.432835,25.320000,544.951704,3.000000,10.292729,3.028619
Vanuatu,5507.010832,14.072941,1951.440046,3.000000,21.301775,6.844106
Venezuela,3865.063680,66.219926,5447.439804,2.333333,94.310345,75.698865
Viet Nam,54213.987808,22.979514,18100.874352,2.666667,31.833732,37.108916

In [64]:
subsidies.loc[:,['RegionName','Countries', 'Type' ,'ReEst_Subsidy2009','SSF_USD_1000']]

    RegionName    Countries Type  ReEst_Subsidy2009  SSF_USD_1000
0         Asia  Philippines   A1      150317.400345  43084.605195
1         Asia  Philippines   A2      106929.633393  27240.860867
2         Asia  Philippines   A3       14325.450291   4106.020784
3         Asia  Philippines   B1      291723.649784  74318.064163
4         Asia  Philippines   B2        5987.405124   1525.321511
5         Asia  Philippines   B3           0.000000           NaN
6         Asia  Philippines   B4        2305.468110    461.093622
7         Asia  Philippines   B5       92663.171127      0.000000
8         Asia  Philippines   B6           0.000000           NaN
9         Asia  Philippines   C1       35605.265432  35605.265432
10        Asia  Philippines   C2           0.000000           NaN
11        Asia  Philippines   C3       21737.044519  21737.044519
12        Asia        India   A1        6450.238140   2733.696798
13        Asia        India   A2        2179.113474    904.297382
14        Asia        India   A3        1781.843735    755.169097
15        Asia        India   B1        4035.395412      0.000000
16        Asia        India   B2        3751.334747    750.266949
17        Asia        India   B3        4062.029933    690.545089
18        Asia        India   B4        4035.395412   1008.848853
19        Asia        India   B5      123957.406261  24791.481252
20        Asia        India   B6           0.000000           NaN
21        Asia        India   C1        5084.598507   2110.027391
22        Asia        India   C2           0.000000           NaN
23        Asia        India   C3        2905.485033   2905.485033
24        Asia     Thailand   A1       18538.640909   7838.119773
25        Asia     Thailand   A2        2067.787646    280.398288
26        Asia     Thailand   A3        2884.411251   1219.526338
27        Asia     Thailand   B1       58456.068748  14614.017187
28        Asia     Thailand   B2         242.934986     32.942722
29        Asia     Thailand   B3        8015.852723      0.000000
..         ...          ...  ...                ...           ...
774     Europe      Romania   B4       25694.478873    334.028225
775     Europe      Romania   B5          47.431407      0.616608
776     Europe      Romania   B6           0.000000           NaN
777     Europe      Romania   C1          10.566188      0.137360
778     Europe      Romania   C2           0.000000           NaN
779     Europe      Romania   C3           0.000000           NaN
780     Europe      Ukraine   A1        9039.338360    931.051851
781     Europe      Ukraine   A2           0.000000           NaN
782     Europe      Ukraine   A3         815.509180     83.997446
783     Europe      Ukraine   B1       16357.036931    490.711108
784     Europe      Ukraine   B2           6.506637      0.195199
785     Europe      Ukraine   B3           0.000000           NaN
786     Europe      Ukraine   B4           0.000000           NaN
787     Europe      Ukraine   B5           0.000000           NaN
788     Europe      Ukraine   B6           0.000000           NaN
789     Europe      Ukraine   C1           0.000000           NaN
790     Europe      Ukraine   C2           0.000000           NaN
791     Europe      Ukraine   C3        1218.802917   1218.802917
792     Europe      Denmark   A1       27710.195182   2161.395224
793     Europe      Denmark   A2       12472.157835    972.828311
794     Europe      Denmark   A3       27261.643121   2126.408163
795     Europe      Denmark   B1       26508.544867   1802.581051
796     Europe      Denmark   B2           0.000000           NaN
797     Europe      Denmark   B3           0.000000           NaN
798     Europe      Denmark   B4       18192.846849   3329.290973
799     Europe      Denmark   B5           0.000000           NaN
800     Europe      Denmark   B6        2867.290462      0.000000
801     Europe      Denmark   C1       23594.021906   1203.295117
802     Europe      Denmark   C2        7601.016403      0.000000
803     Europe      Denmark   C3           0.000000           NaN

[804 rows x 5 columns]

In [65]:
subsidies_values_only = subsidies.loc[:,['RegionName','Countries','Type' ,'ReEst_Subsidy2009','SSF_USD_1000']]

In [66]:
subsidies_values_only.groupby(['RegionName','Countries']).sum()

                                                    ReEst_Subsidy2009  \
RegionName                            Countries
Africa                                Angola            122854.560149
                                      Cameroon           11887.783631
                                      Egypt              13528.962038
                                      Gabon               7827.880786
                                      Ghana              50868.989487
                                      Guinea             36173.964783
                                      Madagascar         11323.955852
                                      Mauritania         26065.971094
                                      Morocco           212774.245464
                                      Mozambique         10422.289071
                                      Namibia            51722.794987
                                      Nigeria            47506.861375
                                      Senegal             7867.121965
                                      Seychelles          4159.236526
                                      Sierra Leone       15766.592734
                                      South Africa       33526.385018
                                      Tunisia             6044.972222
Asia                                  China            2522290.416015
                                      India             158242.840652
                                      Indonesia         422741.213946
                                      Iran              219280.745556
                                      Japan            4489530.165921
                                      Korea Rep         772092.439169
                                      Malaysia          178425.539776
                                      Myanmar           348213.354164
                                      Philippines       721594.488127
                                      Saudi Arabia       32853.879414
                                      Sri Lanka         187905.314178
                                      Taiwan            235699.397558
                                      Thailand          249015.652072
...                                                               ...
Europe                                Netherlands       106037.562727
                                      Norway            275809.648656
                                      Poland            393136.001524
                                      Romania            57527.094233
                                      Russian Fed      1267282.180622
                                      Spain            1052067.810688
                                      Sweden            159792.507716
                                      UK                324784.108663
                                      Ukraine            27437.194025
North America                         Canada           1092092.158981
                                      Mexico            118892.803827
                                      USA              4006009.046523
Oceania                               Australia         430054.775105
                                      Micronesia       1976079.289046
                                      New Zealand        74832.547317
                                      Papua N Guin      610433.040953
                                      Vanuatu            66084.129987
South, Central America and Carribbean Argentina         191752.569153
                                      Brazil            547305.596630
                                      Chile             136215.544422
                                      Costa Rica         12876.115901
                                      Cuba               16159.233277
                                      Ecuador            59187.981621
                                      Guyana             56350.204643
                                      Jamaica            20686.621640
                                      Nicaragua          19447.092660
                                      Panama             48959.199991
                                      Peru              257974.786440
                                      Suriname           23396.600285
                                      Venezuela          46380.764156

                                                      SSF_USD_1000
RegionName                            Countries
Africa                                Angola          54989.135778
                                      Cameroon         4315.696832
                                      Egypt            2593.554368
                                      Gabon            3818.493627
                                      Ghana           26887.742245
                                      Guinea          10056.421737
                                      Madagascar       3892.267803
                                      Mauritania      15459.164114
                                      Morocco         28196.858484
                                      Mozambique       7889.877485
                                      Namibia             0.000000
                                      Nigeria         21145.427712
                                      Senegal          3131.256276
                                      Seychelles        443.263143
                                      Sierra Leone     6876.034300
                                      South Africa     2730.180649
                                      Tunisia          1463.960776
Asia                                  China          497734.989077
                                      India           36649.817845
                                      Indonesia       56077.318403
                                      Iran           127904.405330
                                      Japan         1129295.920947
                                      Korea Rep      104964.909425
                                      Malaysia        37523.368791
                                      Myanmar         83729.909920
                                      Philippines    208078.276093
                                      Saudi Arabia    11353.972940
                                      Sri Lanka       85861.903964
                                      Taiwan          33448.684338
                                      Thailand        71367.032347
...                                                            ...
Europe                                Netherlands       312.364723
                                      Norway          33250.851738
                                      Poland          20620.096113
                                      Romania         20737.788447
                                      Russian Fed     51681.407635
                                      Spain           32447.149274
                                      Sweden           6761.609289
                                      UK              12932.875007
                                      Ukraine          2724.758520
North America                         Canada          56442.371651
                                      Mexico          45367.255190
                                      USA            895701.552729
Oceania                               Australia       71276.859943
                                      Micronesia      38256.995231
                                      New Zealand     10430.294013
                                      Papua N Guin     8229.372649
                                      Vanuatu          7805.760183
South, Central America and Carribbean Argentina        5506.510815
                                      Brazil         243712.288176
                                      Chile            8545.370401
                                      Costa Rica       4229.158592
                                      Cuba            14470.283741
                                      Ecuador         10893.138875
                                      Guyana          14370.695969
                                      Jamaica         20686.621640
                                      Nicaragua        4793.218462
                                      Panama           8265.429813
                                      Peru            53431.656580
                                      Suriname        14913.707087
                                      Venezuela       32684.638825

[67 rows x 2 columns]

In [67]:
subsidies_values_only.groupby(['RegionName','Type']).sum()

                                            ReEst_Subsidy2009   SSF_USD_1000
RegionName                            Type
Africa                                A1        140177.790570   28857.966342
                                      A2         92402.573672   22279.217007
                                      A3         16371.588605    3014.624030
                                      B1        196819.527275   36149.985180
                                      B2        101584.943702   56316.102244
                                      B3         39271.989797   16387.903216
                                      B4         47722.747165   13700.194703
                                      B5         14588.375559    2927.457944
                                      B6          6681.592074       0.000000
                                      C1          1297.486928     851.932829
                                      C2             0.000000            NaN
                                      C3         13403.951834   13403.951834
Asia                                  A1       2666793.855913  851601.087300
                                      A2        754597.552435  197832.154994
                                      A3        126879.261289   33260.787042
                                      B1       1197805.364523  317856.636879
                                      B2        328336.471199   88731.588347
                                      B3       2775670.702754  637020.517989
                                      B4        316512.744490   32067.413025
                                      B5        705465.501553   91124.124799
                                      B6        576445.416265       0.000000
                                      C1        852818.079401  263786.003151
                                      C2        898263.586636       0.000000
                                      C3         92208.287309   92208.287309
Europe                                A1        714272.311257   72552.672372
                                      A2        355912.112435   37752.993647
                                      A3        259889.501968   25624.141163
                                      B1       1021905.341649   61979.907589
                                      B2        278073.869342   17800.038924
                                      B3        419963.690522   28317.947781
...                                                       ...            ...
North America                         B4        222424.340688   42554.889682
                                      B5         91313.106865   17782.086085
                                      B6         52061.349567       0.000000
                                      C1        650000.734907   68216.371672
                                      C2        286682.861134       0.000000
                                      C3             0.000000            NaN
Oceania                               A1        545914.380564   26178.428133
                                      A2        290456.723328   14094.017301
                                      A3         91105.177432   16111.764096
                                      B1        410656.260464   18225.726209
                                      B2        145660.514207   30506.106093
                                      B3         88808.111132       0.000000
                                      B4       1299426.994274       0.000000
                                      B5         71437.780882       0.000000
                                      B6             0.000000            NaN
                                      C1         28262.262712   28262.262712
                                      C2        168997.617791       0.000000
                                      C3         16757.959622    2620.977477
South, Central America and Carribbean A1        498392.222360  148136.669151
                                      A2        182409.590366   81716.568562
                                      A3         68109.513332   37091.251097
                                      B1        193802.472457   47002.271295
                                      B2         56554.901953    9547.716777
                                      B3         61411.106382   34186.196848
                                      B4        128400.173593    6694.379543
                                      B5        137405.186726   11136.047226
                                      B6             0.000000       0.000000
                                      C1         55207.507074   46839.984789
                                      C2         30598.870245       0.000000
                                      C3         24400.766329   14151.633688

[72 rows x 2 columns]

In [68]:
subsidies_short.groupby(['RegionName','Countries']).mean()

                                                    ReEst_Subsidy2009  \
RegionName                            Countries
Africa                                Angola             10237.880012
                                      Cameroon             990.648636
                                      Egypt               1127.413503
                                      Gabon                652.323399
                                      Ghana               4624.453590
                                      Guinea              3288.542253
                                      Madagascar           943.662988
                                      Mauritania          2172.164258
                                      Morocco            17731.187122
                                      Mozambique           868.524089
                                      Namibia             4702.072272
                                      Nigeria             4318.805580
                                      Senegal              655.593497
                                      Seychelles           346.603044
                                      Sierra Leone        1433.326612
                                      South Africa        2793.865418
                                      Tunisia              503.747685
Asia                                  China             210190.868001
                                      India              13186.903388
                                      Indonesia          35228.434495
                                      Iran               18273.395463
                                      Japan             374127.513827
                                      Korea Rep          64341.036597
                                      Malaysia           14868.794981
                                      Myanmar            29017.779514
                                      Philippines        60132.874011
                                      Saudi Arabia        2737.823284
                                      Sri Lanka          15658.776182
                                      Taiwan             19641.616463
                                      Thailand           20751.304339
...                                                               ...
Europe                                Netherlands         8836.463561
                                      Norway             22984.137388
                                      Poland             32761.333460
                                      Romania             4793.924519
                                      Russian Fed       105606.848385
                                      Spain              87672.317557
                                      Sweden             13316.042310
                                      UK                 27065.342389
                                      Ukraine             2286.432835
North America                         Canada             91007.679915
                                      Mexico              9907.733652
                                      USA               333834.087210
Oceania                               Australia          35837.897925
                                      Micronesia        164673.274087
                                      New Zealand         6236.045610
                                      Papua N Guin       50869.420079
                                      Vanuatu             5507.010832
South, Central America and Carribbean Argentina          15979.380763
                                      Brazil             45608.799719
                                      Chile              11351.295369
                                      Costa Rica          1073.009658
                                      Cuba                1346.602773
                                      Ecuador             4932.331802
                                      Guyana              5122.745877
                                      Jamaica             1723.885137
                                      Nicaragua           1620.591055
                                      Panama              4079.933333
                                      Peru               21497.898870
                                      Suriname            1949.716690
                                      Venezuela           3865.063680

                                                    %SSFsubsidies_assessed  \
RegionName                            Countries
Africa                                Angola                     46.600420
                                      Cameroon                   59.840000
                                      Egypt                      17.144118
                                      Gabon                      58.671429
                                      Ghana                      65.787314
                                      Guinea                     34.714286
                                      Madagascar                 57.175000
                                      Mauritania                 44.287500
                                      Morocco                    31.017024
                                      Mozambique                 75.552463
                                      Namibia                     0.000000
                                      Nigeria                    60.739052
                                      Senegal                    48.016667
                                      Seychelles                 26.600000
                                      Sierra Leone               64.850000
                                      South Africa                8.143379
                                      Tunisia                    23.678512
Asia                                  China                      17.032798
                                      India                      34.975948
                                      Indonesia                  28.834670
                                      Iran                       63.648061
                                      Japan                      23.394121
                                      Korea Rep                   8.450000
                                      Malaysia                   21.706250
                                      Myanmar                    34.191173
                                      Philippines                39.305705
                                      Saudi Arabia               65.783333
                                      Sri Lanka                  34.360000
                                      Taiwan                     15.050000
                                      Thailand                   30.582302
...                                                                    ...
Europe                                Netherlands                 0.353750
                                      Norway                     13.150000
                                      Poland                      4.737049
                                      Romania                    35.200000
                                      Russian Fed                 6.296975
                                      Spain                       5.581822
                                      Sweden                      4.564919
                                      UK                          4.484090
                                      Ukraine                    25.320000
North America                         Canada                      4.643931
                                      Mexico                     33.160113
                                      USA                        17.028063
Oceania                               Australia                  28.869204
                                      Micronesia                  5.549155
                                      New Zealand                13.938178
                                      Papua N Guin                4.305707
                                      Vanuatu                    14.072941
South, Central America and Carribbean Argentina                   6.634602
                                      Brazil                     41.769922
                                      Chile                      35.358258
                                      Costa Rica                 35.827459
                                      Cuba                       87.330906
                                      Ecuador                    14.998022
                                      Guyana                     50.739556
                                      Jamaica                   100.000000
                                      Nicaragua                  30.421414
                                      Panama                     26.641002
                                      Peru                       20.471699
                                      Suriname                   73.877486
                                      Venezuela                  66.219926

                                                     SSF_USD_1000  Data_group  \
RegionName                            Countries
Africa                                Angola          6109.903975    2.444444
                                      Cameroon         863.139366         NaN
                                      Egypt            518.710874    2.400000
                                      Gabon            545.499090    2.428571
                                      Ghana           3360.967781    2.250000
                                      Guinea          1436.631677    2.285714
                                      Madagascar       973.066951    2.250000
                                      Mauritania      1932.395514    2.125000
                                      Morocco         4028.122641    2.142857
                                      Mozambique      1972.469371    2.000000
                                      Namibia            0.000000    1.000000
                                      Nigeria         5286.356928    2.250000
                                      Senegal          521.876046    2.166667
                                      Seychelles        88.652629    2.200000
                                      Sierra Leone    1719.008575    2.250000
                                      South Africa     682.545162    3.000000
                                      Tunisia          292.792155    2.800000
Asia                                  China          41477.915756    2.727273
                                      India           3664.981784    1.900000
                                      Indonesia       8011.045486    2.000000
                                      Iran           21317.400888    2.166667
                                      Japan         102663.265541    2.454545
                                      Korea Rep      10496.490943    2.200000
                                      Malaysia        4169.263199    2.125000
                                      Myanmar        13954.984987    2.833333
                                      Philippines    23119.808455    2.222222
                                      Saudi Arabia    1892.328823    2.500000
                                      Sri Lanka      17172.380793    2.200000
                                      Taiwan          4181.085542    2.125000
                                      Thailand        5947.252696    2.222222
...                                                           ...         ...
Europe                                Netherlands       39.045590    2.875000
                                      Norway          4156.356467    2.625000
                                      Poland          2291.121790    2.875000
                                      Romania         2592.223556    3.000000
                                      Russian Fed     6460.175954    2.375000
                                      Spain           3244.714927    2.300000
                                      Sweden           845.201161    3.000000
                                      UK              1293.287501    2.800000
                                      Ukraine          544.951704    3.000000
North America                         Canada          8063.195950    2.857143
                                      Mexico         11341.813797    2.750000
                                      USA            89570.155273    3.000000
Oceania                               Australia      11879.476657    2.833333
                                      Micronesia      5465.285033    2.000000
                                      New Zealand     5215.147006    3.000000
                                      Papua N Guin    1028.671581    2.125000
                                      Vanuatu         1951.440046    3.000000
South, Central America and Carribbean Argentina        611.834535    2.333333
                                      Brazil         22155.662561    2.222222
                                      Chile           1709.074080    2.000000
                                      Costa Rica       845.831718    2.800000
                                      Cuba            4823.427914    3.000000
                                      Ecuador         2178.627775    2.200000
                                      Guyana          3592.673992    2.000000
                                      Jamaica         3447.770273    2.000000
                                      Nicaragua        798.869744    2.333333
                                      Panama          1377.571636    2.333333
                                      Peru            6678.957072    2.125000
                                      Suriname        2982.741417    2.400000
                                      Venezuela       5447.439804    2.333333

                                                    %SSF_totalCatch_EEZ  \
RegionName                            Countries
Africa                                Angola                  44.575137
                                      Cameroon                74.771689
                                      Egypt                   27.060440
                                      Gabon                   27.942422
                                      Ghana                   56.467555
                                      Guinea                  21.500000
                                      Madagascar              73.744951
                                      Mauritania               4.300000
                                      Morocco                  4.966797
                                      Mozambique              73.684211
                                      Namibia                  0.000000
                                      Nigeria                 66.616027
                                      Senegal                 44.073841
                                      Seychelles              11.111111
                                      Sierra Leone            76.444043
                                      South Africa             8.143379
                                      Tunisia                 26.210526
Asia                                  China                   35.600970
                                      India                   42.381331
                                      Indonesia               22.323870
                                      Iran                    58.052126
                                      Japan                   23.586724
                                      Korea Rep               16.380902
                                      Malaysia                22.118858
                                      Myanmar                 20.813764
                                      Philippines             28.662420
                                      Saudi Arabia            64.926740
                                      Sri Lanka               49.069849
                                      Taiwan                  23.400309
                                      Thailand                42.279905
...                                                                 ...
Europe                                Netherlands              0.547727
                                      Norway                  10.098171
                                      Poland                  11.944444
                                      Romania                 91.666667
                                      Russian Fed             15.181599
                                      Spain                    7.788784
                                      Sweden                   5.259676
                                      UK                       3.603992
                                      Ukraine                 10.292729
North America                         Canada                   6.131213
                                      Mexico                  42.202139
                                      USA                     26.719067
Oceania                               Australia               19.461492
                                      Micronesia               8.501559
                                      New Zealand             13.938178
                                      Papua N Guin             9.400476
                                      Vanuatu                 21.301775
South, Central America and Carribbean Argentina               16.685018
                                      Brazil                  51.260412
                                      Chile                   69.392954
                                      Costa Rica              25.350318
                                      Cuba                    90.100000
                                      Ecuador                 21.900000
                                      Guyana                  51.700000
                                      Jamaica                100.000000
                                      Nicaragua               31.500000
                                      Panama                  16.400000
                                      Peru                     8.596049
                                      Suriname                51.891892
                                      Venezuela               94.310345

                                                    %SSF_totalCatch_Country
RegionName                            Countries
Africa                                Angola                      46.050702
                                      Cameroon                    82.493703
                                      Egypt                       20.563674
                                      Gabon                       63.461538
                                      Ghana                       51.549627
                                      Guinea                      75.952478
                                      Madagascar                  83.311604
                                      Mauritania                  38.465310
                                      Morocco                      8.952369
                                      Mozambique                  78.525641
                                      Namibia                      0.000000
                                      Nigeria                     68.156207
                                      Senegal                     50.575668
                                      Seychelles                   8.970976
                                      Sierra Leone                80.769231
                                      South Africa                 8.143379
                                      Tunisia                     26.433121
Asia                                  China                       23.241135

In [69]:
countrydata = pd.read_csv("Country_Data.csv")

In [70]:
countrydata

,CID,Countries,Subregion,CLon,CLat,SIDS,TotPop,HDI,Develop,GDP
0,1,Albania,Southern Europe,20.050049,40.934006,0,3020209,0.749,High,3.066000e+10
1,2,Algeria,Northern Africa,2.296145,27.940730,0,38813722,0.717,Medium,5.626000e+11
2,3,Angola,Middle Africa,17.237553,-13.299091,0,19088106,0.526,Low,1.755000e+11
3,4,Antigua Barb,Caribbean,-61.800000,17.050000,1,91295,0.774,High,1.989000e+09
4,5,Argentina,South America,-64.379883,-33.707205,0,43024374,0.808,High,9.274000e+11
5,6,Australia,Australia and New Zealand,133.769531,-25.105497,0,22507617,0.933,High,1.100000e+12
6,7,Bahamas,Caribbean,-77.934265,24.533303,1,321834,0.789,High,9.034000e+09
7,8,Bahrain,Western Asia,50.550000,26.000000,1,1314089,0.815,High,6.156000e+10
8,9,Bangladesh,Southern Asia,90.186768,24.444024,0,166280712,0.558,Medium,5.366000e+11
9,10,Barbados,Caribbean,-59.550018,13.151284,1,289680,0.776,High,4.513000e+09
10,11,Belgium,Western Europe,4.383545,50.692543,0,10449361,0.881,High,4.671000e+11
11,12,Belize,Central America,-88.846436,17.261154,1,340844,0.732,Medium,2.907000e+09
12,13,Benin,Western Africa,2.438965,9.702289,0,10160556,0.476,Low,1.985000e+10
13,14,Bosnia Herzg,Southern Europe,18.416667,43.866667,NaN,3871643,0.731,High,3.808000e+10
14,15,Brazil,South America,-51.815643,-12.986242,0,202656788,0.744,High,3.073000e+12
15,16,Brunei Darsm,Southeastern Asia,114.612122,4.438665,0,422675,0.852,High,3.211000e+10
16,17,Bulgaria,Eastern Europe,25.125732,42.501972,0,6924716,0.777,High,1.233000e+11
17,18,Cambodia,Southeastern Asia,104.768372,12.773467,0,15458332,0.584,Medium,5.025000e+10
18,19,Cameroon,Middle Africa,12.370605,4.471011,0,23130708,0.504,Medium,6.723000e+10
19,20,Canada,Northern America,-106.424561,56.532039,0,34834841,0.902,High,1.579000e+12
20,21,Cape Verde,Western Africa,-23.521729,15.012443,1,538535,0.636,Medium,3.286000e+09
21,22,Chile,South America,-69.833221,-26.826905,0,17363894,0.822,High,4.103000e+11
22,23,China,Eastern Asia,103.977356,34.709304,0,1355692576,0.719,Medium,1.763000e+13
23,24,Colombia,South America,-73.085175,3.422521,0,46245297,0.711,Medium,6.427000e+11
24,25,Comoros,Eastern Africa,43.368530,-11.729226,1,766865,0.488,Medium,1.211000e+09
25,26,Congo Dem Rep,Middle Africa,22.450562,-3.021555,0,77433744,0.338,Low,5.573000e+10
26,27,Congo Rep,Middle Africa,15.419312,-1.001421,0,4662446,0.564,Medium,2.809000e+10
27,28,Costa Rica,Central America,-83.807831,9.879147,0,4755234,0.763,High,7.121000e+10
28,29,Cote d'Ivoire,Western Africa,-5.372314,7.606192,0,22848945,0.452,Low,7.195000e+10
29,30,Croatia,Southern Europe,14.732666,45.001224,0,4470534,0.812,High,8.730000e+10
...,...,...,...,...,...,...,...,...,...,...
122,123,Somalia,Eastern Africa,49.188538,9.008521,0,10428043,NaN,Medium,5.896000e+09
123,124,South Africa,Southern Africa,22.821350,-31.209278,0,48375645,0.658,Low,6.831000e+11
124,125,Spain,Southern Europe,-3.343628,39.652454,0,47737941,0.869,Medium,1.534000e+12
125,126,Sri Lanka,Southern Asia,80.771484,7.305261,0,21866445,0.750,High,2.171000e+11
126,127,St Kitts Nev,Caribbean,-62.750000,17.333333,1,51538,0.750,Medium,1.220000e+09
127,128,St Lucia,Caribbean,-60.975708,13.900474,1,163362,0.714,Medium,1.893000e+09
128,129,St Vincent,Caribbean,-61.173462,13.227645,1,102918,0.719,Medium,1.193000e+09
129,130,Sudan,Northern Africa,30.524139,15.795888,0,35482233,0.473,Medium,1.595000e+11
130,131,Suriname,South America,-55.898438,4.335456,1,573311,0.705,Medium,9.240000e+09
131,132,Sweden,Northern Europe,15.231171,61.314264,0,9723809,0.898,High,4.342000e+10
132,133,Syria,Western Asia,38.759766,35.054732,0,17951639,0.658,Medium,1.076000e+10
133,134,Taiwan,Eastern Asia,121.014404,23.882698,0,23359928,0.777,High,1.022000e+12
134,135,Tanzania,Eastern Africa,35.240356,-6.385978,0,49639138,0.488,Medium,9.253000e+10
135,136,Thailand,Southeastern Asia,100.870285,15.604314,0,67741401,0.722,Medium,9.901000e+11
136,137,Timor Leste,Southeastern Asia,125.897827,-8.756491,0,1201542,0.620,Medium,8.364000e+09
137,138,Togo,Western Africa,1.068420,8.400375,0,7351374,0.473,Medium,1.018000e+10
138,139,Tonga,Polynesia,-175.198242,-21.178986,1,106440,0.705,High,5.230000e+08
139,140,Trinidad Tob,Caribbean,-61.272337,10.442975,1,1223916,0.766,High,4.223000e+10
140,141,Tunisia,Northern Africa,9.593815,34.010550,0,10937521,0.721,Medium,1.251000e+11
141,142,Turkey,Western Asia,34.628908,39.527348,0,81619392,0.759,Medium,1.512000e+12
142,143,Tuvalu,Polynesia,178.679921,-7.478442,1,10782,NaN,NaN,3.500000e+07
143,144,UK,Northern Europe,-1.538080,53.032955,0,63742977,0.892,Medium,2.435000e+12
144,145,Ukraine,Eastern Europe,33.178719,48.942347,0,44291413,0.734,High,3.731000e+11
145,146,Untd Arab Em,Western Asia,54.448252,23.913460,0,5628805,0.827,High,6.050000e+08
146,147,Uruguay,South America,-56.206051,-32.888813,0,3332972,0.790,High,6.978000e+10
147,148,USA,Northern America,-104.690304,40.278267,0,318892103,0.914,High,1.746000e+13
148,149,Vanuatu,Melanesia,166.959158,-15.376706,1,266937,0.616,Medium,6.870000e+08
149,150,Venezuela,South America,-66.369987,7.927041,0,28868486,0.764,Medium,5.457000e+08
150,151,Viet Nam,Southeastern Asia,108.277199,14.058324,0,93421835,0.638,Medium,5.095000e+11
151,152,Yemen,Western Asia,47.373059,15.990375,0,26052966,0.500,Medium,1.060000e+11

In [71]:
countrydata_short = countrydata.loc[:,['Countries','Region', 'Subregion']]

In [72]:
countrydata_short

         Countries  Region                  Subregion
0          Albania     NaN            Southern Europe
1          Algeria     NaN            Northern Africa
2           Angola     NaN              Middle Africa
3     Antigua Barb     NaN                  Caribbean
4        Argentina     NaN              South America
5        Australia     NaN  Australia and New Zealand
6          Bahamas     NaN                  Caribbean
7          Bahrain     NaN               Western Asia
8       Bangladesh     NaN              Southern Asia
9         Barbados     NaN                  Caribbean
10         Belgium     NaN             Western Europe
11          Belize     NaN            Central America
12           Benin     NaN             Western Africa
13    Bosnia Herzg     NaN            Southern Europe
14          Brazil     NaN              South America
15    Brunei Darsm     NaN          Southeastern Asia
16        Bulgaria     NaN             Eastern Europe
17        Cambodia     NaN          Southeastern Asia
18        Cameroon     NaN              Middle Africa
19          Canada     NaN           Northern America
20      Cape Verde     NaN             Western Africa
21           Chile     NaN              South America
22           China     NaN               Eastern Asia
23        Colombia     NaN              South America
24         Comoros     NaN             Eastern Africa
25   Congo Dem Rep     NaN              Middle Africa
26       Congo Rep     NaN              Middle Africa
27      Costa Rica     NaN            Central America
28   Cote d'Ivoire     NaN             Western Africa
29         Croatia     NaN            Southern Europe
..             ...     ...                        ...
122        Somalia     NaN             Eastern Africa
123   South Africa     NaN            Southern Africa
124          Spain     NaN            Southern Europe
125      Sri Lanka     NaN              Southern Asia
126   St Kitts Nev     NaN                  Caribbean
127       St Lucia     NaN                  Caribbean
128     St Vincent     NaN                  Caribbean
129          Sudan     NaN            Northern Africa
130       Suriname     NaN              South America
131         Sweden     NaN            Northern Europe
132          Syria     NaN               Western Asia
133         Taiwan     NaN               Eastern Asia
134       Tanzania     NaN             Eastern Africa
135       Thailand     NaN          Southeastern Asia
136    Timor Leste     NaN          Southeastern Asia
137           Togo     NaN             Western Africa
138          Tonga     NaN                  Polynesia
139   Trinidad Tob     NaN                  Caribbean
140        Tunisia     NaN            Northern Africa
141         Turkey     NaN               Western Asia
142         Tuvalu     NaN                  Polynesia
143             UK     NaN            Northern Europe
144        Ukraine     NaN             Eastern Europe
145   Untd Arab Em     NaN               Western Asia
146        Uruguay     NaN              South America
147            USA     NaN           Northern America
148        Vanuatu     NaN                  Melanesia
149      Venezuela     NaN              South America
150       Viet Nam     NaN          Southeastern Asia
151          Yemen     NaN               Western Asia

[152 rows x 3 columns]

In [73]:
frames = [subsidies,countrydata]

In [74]:
frames

[       ID  Cnumber  RegionID RegionName Type                    SubType  \
 0    1418      608         2       Asia   A1           Fisheries mangt.
 1    1419      608         2       Asia   A2                Fishery R&D
 2    1420      608         2       Asia   A3                       MPAs
 3    1421      608         2       Asia   B1  Boat constsruct. & renov.
 4    1422      608         2       Asia   B2    Fisheries dev. projects
 5    1423      608         2       Asia   B3      Fishing port develop.
 6    1424      608         2       Asia   B4  Markt. & storage infrast.
 7    1425      608         2       Asia   B5              Tax exemption
 8    1426      608         2       Asia   B6             Fishing access
 9    1428      608         2       Asia   C1          Fisher assistance
 10   1429      608         2       Asia   C2             Vessel buyback
 11   1430      608         2       Asia   C3   Rural fisher communities
 12    820      356         2       Asia   A1           Fisheries mangt.
 13    821      356         2       Asia   A2                Fishery R&D
 14    822      356         2       Asia   A3                       MPAs
 15    823      356         2       Asia   B1  Boat constsruct. & renov.
 16    824      356         2       Asia   B2    Fisheries dev. projects
 17    825      356         2       Asia   B3      Fishing port develop.
 18    826      356         2       Asia   B4  Markt. & storage infrast.
 19    827      356         2       Asia   B5              Tax exemption
 20    828      356         2       Asia   B6             Fishing access
 21    830      356         2       Asia   C1          Fisher assistance
 22    831      356         2       Asia   C2             Vessel buyback
 23    832      356         2       Asia   C3   Rural fisher communities
 24   1756      764         2       Asia   A1           Fisheries mangt.
 25   1757      764         2       Asia   A2                Fishery R&D
 26   1758      764         2       Asia   A3                       MPAs
 27   1759      764         2       Asia   B1  Boat constsruct. & renov.
 28   1760      764         2       Asia   B2    Fisheries dev. projects
 29   1761      764         2       Asia   B3      Fishing port develop.
 ..    ...      ...       ...        ...  ...                        ...
 774  1502      642         1     Europe   B4  Markt. & storage infrast.
 775  1503      642         1     Europe   B5              Tax exemption
 776  1504      642         1     Europe   B6             Fishing access
 777  1506      642         1     Europe   C1          Fisher assistance
 778  1507      642         1     Europe   C2             Vessel buyback
 779  1508      642         1     Europe   C3   Rural fisher communities
 780  1860      804         1     Europe   A1           Fisheries mangt.
 781  1861      804         1     Europe   A2                Fishery R&D
 782  1862      804         1     Europe   A3                       MPAs
 783  1863      804         1     Europe   B1  Boat constsruct. & renov.
 784  1864      804         1     Europe   B2    Fisheries dev. projects
 785  1865      804         1     Europe   B3      Fishing port develop.
 786  1866      804         1     Europe   B4  Markt. & storage infrast.
 787  1867      804         1     Europe   B5              Tax exemption
 788  1868      804         1     Europe   B6             Fishing access
 789  1870      804         1     Europe   C1          Fisher assistance
 790  1871      804         1     Europe   C2             Vessel buyback
 791  1872      804         1     Europe   C3   Rural fisher communities
 792   469      208         1     Europe   A1           Fisheries mangt.
 793   470      208         1     Europe   A2                Fishery R&D
 794   471      208         1     Europe   A3                       MPAs
 795   472      208         1     Europe   B1  Boat constsruct. & renov.
 796   473      208         1     Europe   B2    Fisheries dev. projects
 797   474      208         1     Europe   B3      Fishing port develop.
 798   475      208         1     Europe   B4  Markt. & storage infrast.
 799   476      208         1     Europe   B5              Tax exemption
 800   477      208         1     Europe   B6             Fishing access
 801   479      208         1     Europe   C1          Fisher assistance
 802   480      208         1     Europe   C2             Vessel buyback
 803   481      208         1     Europe   C3   Rural fisher communities

     Category  ReEst_Subsidy2009 NewData   Developed  HDI_2005    Countries  \
 0       Good      150317.400345   False  Developing     0.771  Philippines
 1       Good      106929.633393   False  Developing     0.771  Philippines
 2       Good       14325.450291   False  Developing     0.771  Philippines
 3        Bad      291723.649784   False  Developing     0.771  Philippines
 4        Bad        5987.405124    True  Developing     0.771  Philippines
 5        Bad           0.000000   False  Developing     0.771  Philippines
 6        Bad        2305.468110   False  Developing     0.771  Philippines
 7        Bad       92663.171127   False  Developing     0.771  Philippines
 8        Bad           0.000000   False  Developing     0.771  Philippines
 9       Ugly       35605.265432    True  Developing     0.771  Philippines
 10      Ugly           0.000000   False  Developing     0.771  Philippines
 11      Ugly       21737.044519   False  Developing     0.771  Philippines
 12      Good        6450.238140    True  Developing     0.619        India
 13      Good        2179.113474    True  Developing     0.619        India
 14      Good        1781.843735   False  Developing     0.619        India
 15       Bad        4035.395412    True  Developing     0.619        India
 16       Bad        3751.334747    True  Developing     0.619        India
 17       Bad        4062.029933    True  Developing     0.619        India
 18       Bad        4035.395412    True  Developing     0.619        India
 19       Bad      123957.406261   False  Developing     0.619        India
 20       Bad           0.000000   False  Developing     0.619        India
 21      Ugly        5084.598507    True  Developing     0.619        India
 22      Ugly           0.000000   False  Developing     0.619        India
 23      Ugly        2905.485033    True  Developing     0.619        India
 24      Good       18538.640909   False  Developing     0.781     Thailand
 25      Good        2067.787646   False  Developing     0.781     Thailand
 26      Good        2884.411251   False  Developing     0.781     Thailand
 27       Bad       58456.068748   False  Developing     0.781     Thailand
 28       Bad         242.934986    True  Developing     0.781     Thailand
 29       Bad        8015.852723    True  Developing     0.781     Thailand
 ..       ...                ...     ...         ...       ...          ...
 774      Bad       25694.478873    True  Developing     0.813      Romania
 775      Bad          47.431407   False  Developing     0.813      Romania
 776      Bad           0.000000   False  Developing     0.813      Romania
 777     Ugly          10.566188    True  Developing     0.813      Romania
 778     Ugly           0.000000   False  Developing     0.813      Romania
 779     Ugly           0.000000   False  Developing     0.813      Romania
 780     Good        9039.338360   False  Developing     0.788      Ukraine
 781     Good           0.000000   False  Developing     0.788      Ukraine
 782     Good         815.509180   False  Developing     0.788      Ukraine
 783      Bad       16357.036931   False  Developing     0.788      Ukraine
 784      Bad           6.506637    True  Developing     0.788      Ukraine
 785      Bad           0.000000   False  Developing     0.788      Ukraine
 786      Bad           0.000000   False  Developing     0.788      Ukraine
 787      Bad           0.000000   False  Developing     0.788      Ukraine
 788      Bad           0.000000   False  Developing     0.788      Ukraine
 789     Ugly           0.000000   False  Developing     0.788      Ukraine
 790     Ugly           0.000000   False  Developing     0.788      Ukraine
 791     Ugly        1218.802917   False  Developing     0.788      Ukraine
 792     Good       27710.195182    True   Developed     0.949      Denmark
 793     Good       12472.157835    True   Developed     0.949      Denmark
 794     Good       27261.643121   False   Developed     0.949      Denmark
 795      Bad       26508.544867    True   Developed     0.949      Denmark
 796      Bad           0.000000    True   Developed     0.949      Denmark
 797      Bad           0.000000   False   Developed     0.949      Denmark
 798      Bad       18192.846849    True   Developed     0.949      Denmark
 799      Bad           0.000000   False   Developed     0.949      Denmark
 800      Bad        2867.290462    True   Developed     0.949      Denmark
 801     Ugly       23594.021906    True   Developed     0.949      Denmark
 802     Ugly        7601.016403    True   Developed     0.949      Denmark
 803     Ugly           0.000000   False   Developed     0.949      Denmark

      %SSFsubsidies_assessed weighted_by_sectorsize  Data_group  \
 0                 28.662420                   TRUE           3
 1                 25.475502                   TRUE           3
 2                 28.662420                   TRUE           3
 3                 25.475502                   TRUE           3
 4                 25.475502                   TRUE           3
 5                       NaN                    NaN         NaN
 6                 20.000000                  FALSE           1
 7                  0.000000                  FALSE           2
 8                       NaN                    NaN         NaN
 9                100.000000                  FALSE           1
 10                      NaN                    NaN         NaN
 11               100.000000                  FALSE           1
 12                42.381331                   TRUE           3
 13                41.498407                   TRUE           3
 14                42.381331                   TRUE           3
 15                 0.000000                  FALSE           2
 16                20.000000                  FALSE           1
 17                17.000000                  FALSE           1
 18                25.000000                  FALSE           1
 19                20.000000                  FALSE           1
 20                      NaN                    NaN         NaN
 21                41.498407                   TRUE           3
 22                      NaN                    NaN         NaN
 23               100.000000                  FALSE           1
 24                42.279905                   TRUE           3
 25                13.560304                   TRUE           3
 26                42.279905                   TRUE           3
 27                25.000000                  FALSE           1
 28                13.560304                   TRUE           3
 29                 0.000000                  FALSE           2
 ..                      ...                    ...         ...
 774                1.300000                      1           3
 775                1.300000                      1           3
 776                     NaN                    NaN         NaN
 777                1.300000                      1           3
 778                     NaN                    NaN         NaN
 779                     NaN                    NaN         NaN
 780               10.300000                      1           3
 781                     NaN                    NaN         NaN
 782               10.300000                      1           3
 783                3.000000                      1           3
 784                3.000000                      1           3
 785                     NaN                    NaN         NaN
 786                     NaN                    NaN         NaN
 787                     NaN                    NaN         NaN
 788                     NaN                    NaN         NaN
 789                     NaN                    NaN         NaN
 790                     NaN                    NaN         NaN
 791              100.000000                      0           3
 792                7.800000                      1           3
 793                7.800000                      1           3
 794                7.800000                      1           3
 795                6.800000                      1           3
 796                     NaN                    NaN         NaN
 797                     NaN                    NaN         NaN
 798               18.300000                      0           2
 799                     NaN                    NaN         NaN
 800                0.000000                      1           3
 801                5.100000                      0           2
 802                0.000000                      0           3
 803                     NaN                    NaN         NaN

      %SSF_totalCatch_EEZ  %SSF_totalCatch_Country  SSF_USD_1000
 0              28.662420                25.475502  43084.605195
 1              28.662420                25.475502  27240.860867
 2              28.662420                25.475502   4106.020784
 3              28.662420                25.475502  74318.064163
 4              28.662420                25.475502   1525.321511
 5              28.662420                25.475502           NaN
 6              28.662420                25.475502    461.093622
 7              28.662420                25.475502      0.000000
 8              28.662420                25.475502           NaN
 9              28.662420                25.475502  35605.265432
 10             28.662420                25.475502           NaN
 11             28.662420                25.475502  21737.044519
 12             42.381331                41.498407   2733.696798
 13             42.381331                41.498407    904.297382
 14             42.381331                41.498407    755.169097
 15             42.381331                41.498407      0.000000
 16             42.381331                41.498407    750.266949
 17             42.381331                41.498407    690.545089
 18             42.381331                41.498407   1008.848853
 19             42.381331                41.498407  24791.481252
 20             42.381331                41.498407           NaN
 21             42.381331                41.498407   2110.027391
 22             42.381331                41.498407           NaN
 23             42.381331                41.498407   2905.485033
 24             42.279905                13.560304   7838.119773
 25             42.279905                13.560304    280.398288
 26             42.279905                13.560304   1219.526338
 27             42.279905                13.560304  14614.017187
 28             42.279905                13.560304     32.942722
 29             42.279905                13.560304      0.000000
 ..                   ...                      ...           ...
 774            91.666667                 1.269394    334.028225
 775            91.666667                 1.269394      0.616608
 776            91.666667                 1.269394           NaN
 777            91.666667                 1.269394      0.137360
 778            91.666667                 1.269394           NaN
 779            91.666667                 1.269394           NaN
 780            10.292729                 3.028619    931.051851
 781            10.292729                 3.028619           NaN
 782            10.292729                 3.028619     83.997446
 783            10.292729                 3.028619    490.711108
 784            10.292729                 3.028619      0.195199
 785            10.292729                 3.028619           NaN
 786            10.292729                 3.028619           NaN
 787            10.292729                 3.028619           NaN
 788            10.292729                 3.028619           NaN
 789            10.292729                 3.028619           NaN
 790            10.292729                 3.028619           NaN
 791            10.292729                 3.028619   1218.802917
 792             7.759108                 6.799901   2161.395224
 793             7.759108                 6.799901    972.828311
 794             7.759108                 6.799901   2126.408163
 795             7.759108                 6.799901   1802.581051
 796             7.759108                 6.799901           NaN
 797             7.759108                 6.799901           NaN
 798             7.759108                 6.799901   3329.290973
 799             7.759108                 6.799901           NaN
 800             7.759108                 6.799901      0.000000
 801             7.759108                 6.799901   1203.295117
 802             7.759108                 6.799901      0.000000
 803             7.759108                 6.799901           NaN

 [804 rows x 18 columns],
      CID      Countries                  Subregion        CLon       CLat  \
 0      1        Albania            Southern Europe   20.050049  40.934006
 1      2        Algeria            Northern Africa    2.296145  27.940730
 2      3         Angola              Middle Africa   17.237553 -13.299091
 3      4   Antigua Barb                  Caribbean  -61.800000  17.050000
 4      5      Argentina              South America  -64.379883 -33.707205
 5      6      Australia  Australia and New Zealand  133.769531 -25.105497
 6      7        Bahamas                  Caribbean  -77.934265  24.533303
 7      8        Bahrain               Western Asia   50.550000  26.000000
 8      9     Bangladesh              Southern Asia   90.186768  24.444024
 9     10       Barbados                  Caribbean  -59.550018  13.151284
 10    11        Belgium             Western Europe    4.383545  50.692543
 11    12         Belize            Central America  -88.846436  17.261154
 12    13          Benin             Western Africa    2.438965   9.702289
 13    14   Bosnia Herzg            Southern Europe   18.416667  43.866667
 14    15         Brazil              South America  -51.815643 -12.986242
 15    16   Brunei Darsm          Southeastern Asia  114.612122   4.438665
 16    17       Bulgaria             Eastern Europe   25.125732  42.501972
 17    18       Cambodia          Southeastern Asia  104.768372  12.773467
 18    19       Cameroon              Middle Africa   12.370605   4.471011
 19    20         Canada           Northern America -106.424561  56.532039
 20    21     Cape Verde             Western Africa  -23.521729  15.012443
 21    22          Chile              South America  -69.833221 -26.826905
 22    23          China               Eastern Asia  103.977356  34.709304
 23    24       Colombia              South America  -73.085175   3.422521
 24    25        Comoros             Eastern Africa   43.368530 -11.729226
 25    26  Congo Dem Rep              Middle Africa   22.450562  -3.021555
 26    27      Congo Rep              Middle Africa   15.419312  -1.001421
 27    28     Costa Rica            Central America  -83.807831   9.879147
 28    29  Cote d'Ivoire             Western Africa   -5.372314   7.606192
 29    30        Croatia            Southern Europe   14.732666  45.001224
 ..   ...            ...                        ...         ...        ...
 122  123        Somalia             Eastern Africa   49.188538   9.008521
 123  124   South Africa            Southern Africa   22.821350 -31.209278
 124  125          Spain            Southern Europe   -3.343628  39.652454
 125  126      Sri Lanka              Southern Asia   80.771484   7.305261

In [75]:
pd.concat(frames)

,%SSF_totalCatch_Country,%SSF_totalCatch_EEZ,%SSFsubsidies_assessed,CID,CLat,CLon,Category,Cnumber,Countries,Data_group,...,ReEst_Subsidy2009,RegionID,RegionName,SIDS,SSF_USD_1000,SubType,Subregion,TotPop,Type,weighted_by_sectorsize
0,25.475502,28.662420,28.662420,NaN,NaN,NaN,Good,608,Philippines,3,...,150317.400345,2,Asia,NaN,43084.605195,Fisheries mangt.,NaN,NaN,A1,TRUE
1,25.475502,28.662420,25.475502,NaN,NaN,NaN,Good,608,Philippines,3,...,106929.633393,2,Asia,NaN,27240.860867,Fishery R&D,NaN,NaN,A2,TRUE
2,25.475502,28.662420,28.662420,NaN,NaN,NaN,Good,608,Philippines,3,...,14325.450291,2,Asia,NaN,4106.020784,MPAs,NaN,NaN,A3,TRUE
3,25.475502,28.662420,25.475502,NaN,NaN,NaN,Bad,608,Philippines,3,...,291723.649784,2,Asia,NaN,74318.064163,Boat constsruct. & renov.,NaN,NaN,B1,TRUE
4,25.475502,28.662420,25.475502,NaN,NaN,NaN,Bad,608,Philippines,3,...,5987.405124,2,Asia,NaN,1525.321511,Fisheries dev. projects,NaN,NaN,B2,TRUE
5,25.475502,28.662420,NaN,NaN,NaN,NaN,Bad,608,Philippines,NaN,...,0.000000,2,Asia,NaN,NaN,Fishing port develop.,NaN,NaN,B3,NaN
6,25.475502,28.662420,20.000000,NaN,NaN,NaN,Bad,608,Philippines,1,...,2305.468110,2,Asia,NaN,461.093622,Markt. & storage infrast.,NaN,NaN,B4,FALSE
7,25.475502,28.662420,0.000000,NaN,NaN,NaN,Bad,608,Philippines,2,...,92663.171127,2,Asia,NaN,0.000000,Tax exemption,NaN,NaN,B5,FALSE
8,25.475502,28.662420,NaN,NaN,NaN,NaN,Bad,608,Philippines,NaN,...,0.000000,2,Asia,NaN,NaN,Fishing access,NaN,NaN,B6,NaN
9,25.475502,28.662420,100.000000,NaN,NaN,NaN,Ugly,608,Philippines,1,...,35605.265432,2,Asia,NaN,35605.265432,Fisher assistance,NaN,NaN,C1,FALSE
10,25.475502,28.662420,NaN,NaN,NaN,NaN,Ugly,608,Philippines,NaN,...,0.000000,2,Asia,NaN,NaN,Vessel buyback,NaN,NaN,C2,NaN
11,25.475502,28.662420,100.000000,NaN,NaN,NaN,Ugly,608,Philippines,1,...,21737.044519,2,Asia,NaN,21737.044519,Rural fisher communities,NaN,NaN,C3,FALSE
12,41.498407,42.381331,42.381331,NaN,NaN,NaN,Good,356,India,3,...,6450.238140,2,Asia,NaN,2733.696798,Fisheries mangt.,NaN,NaN,A1,TRUE
13,41.498407,42.381331,41.498407,NaN,NaN,NaN,Good,356,India,3,...,2179.113474,2,Asia,NaN,904.297382,Fishery R&D,NaN,NaN,A2,TRUE
14,41.498407,42.381331,42.381331,NaN,NaN,NaN,Good,356,India,3,...,1781.843735,2,Asia,NaN,755.169097,MPAs,NaN,NaN,A3,TRUE
15,41.498407,42.381331,0.000000,NaN,NaN,NaN,Bad,356,India,2,...,4035.395412,2,Asia,NaN,0.000000,Boat constsruct. & renov.,NaN,NaN,B1,FALSE
16,41.498407,42.381331,20.000000,NaN,NaN,NaN,Bad,356,India,1,...,3751.334747,2,Asia,NaN,750.266949,Fisheries dev. projects,NaN,NaN,B2,FALSE
17,41.498407,42.381331,17.000000,NaN,NaN,NaN,Bad,356,India,1,...,4062.029933,2,Asia,NaN,690.545089,Fishing port develop.,NaN,NaN,B3,FALSE
18,41.498407,42.381331,25.000000,NaN,NaN,NaN,Bad,356,India,1,...,4035.395412,2,Asia,NaN,1008.848853,Markt. & storage infrast.,NaN,NaN,B4,FALSE
19,41.498407,42.381331,20.000000,NaN,NaN,NaN,Bad,356,India,1,...,123957.406261,2,Asia,NaN,24791.481252,Tax exemption,NaN,NaN,B5,FALSE
20,41.498407,42.381331,NaN,NaN,NaN,NaN,Bad,356,India,NaN,...,0.000000,2,Asia,NaN,NaN,Fishing access,NaN,NaN,B6,NaN
21,41.498407,42.381331,41.498407,NaN,NaN,NaN,Ugly,356,India,3,...,5084.598507,2,Asia,NaN,2110.027391,Fisher assistance,NaN,NaN,C1,TRUE
22,41.498407,42.381331,NaN,NaN,NaN,NaN,Ugly,356,India,NaN,...,0.000000,2,Asia,NaN,NaN,Vessel buyback,NaN,NaN,C2,NaN
23,41.498407,42.381331,100.000000,NaN,NaN,NaN,Ugly,356,India,1,...,2905.485033,2,Asia,NaN,2905.485033,Rural fisher communities,NaN,NaN,C3,FALSE
24,13.560304,42.279905,42.279905,NaN,NaN,NaN,Good,764,Thailand,3,...,18538.640909,2,Asia,NaN,7838.119773,Fisheries mangt.,NaN,NaN,A1,TRUE
25,13.560304,42.279905,13.560304,NaN,NaN,NaN,Good,764,Thailand,3,...,2067.787646,2,Asia,NaN,280.398288,Fishery R&D,NaN,NaN,A2,TRUE
26,13.560304,42.279905,42.279905,NaN,NaN,NaN,Good,764,Thailand,3,...,2884.411251,2,Asia,NaN,1219.526338,MPAs,NaN,NaN,A3,TRUE
27,13.560304,42.279905,25.000000,NaN,NaN,NaN,Bad,764,Thailand,1,...,58456.068748,2,Asia,NaN,14614.017187,Boat constsruct. & renov.,NaN,NaN,B1,FALSE
28,13.560304,42.279905,13.560304,NaN,NaN,NaN,Bad,764,Thailand,3,...,242.934986,2,Asia,NaN,32.942722,Fisheries dev. projects,NaN,NaN,B2,TRUE
29,13.560304,42.279905,0.000000,NaN,NaN,NaN,Bad,764,Thailand,2,...,8015.852723,2,Asia,NaN,0.000000,Fishing port develop.,NaN,NaN,B3,FALSE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122,NaN,NaN,NaN,123,9.008521,49.188538,NaN,NaN,Somalia,NaN,...,NaN,NaN,NaN,0,NaN,NaN,Eastern Africa,10428043,NaN,NaN
123,NaN,NaN,NaN,124,-31.209278,22.821350,NaN,NaN,South Africa,NaN,...,NaN,NaN,NaN,0,NaN,NaN,Southern Africa,48375645,NaN,NaN
124,NaN,NaN,NaN,125,39.652454,-3.343628,NaN,NaN,Spain,NaN,...,NaN,NaN,NaN,0,NaN,NaN,Southern Europe,47737941,NaN,NaN
125,NaN,NaN,NaN,126,7.305261,80.771484,NaN,NaN,Sri Lanka,NaN,...,NaN,NaN,NaN,0,NaN,NaN,Southern Asia,21866445,NaN,NaN
126,NaN,NaN,NaN,127,17.333333,-62.750000,NaN,NaN,St Kitts Nev,NaN,...,NaN,NaN,NaN,1,NaN,NaN,Caribbean,51538,NaN,NaN
127,NaN,NaN,NaN,128,13.900474,-60.975708,NaN,NaN,St Lucia,NaN,...,NaN,NaN,NaN,1,NaN,NaN,Caribbean,163362,NaN,NaN
128,NaN,NaN,NaN,129,13.227645,-61.173462,NaN,NaN,St Vincent,NaN,...,NaN,NaN,NaN,1,NaN,NaN,Caribbean,102918,NaN,NaN
129,NaN,NaN,NaN,130,15.795888,30.524139,NaN,NaN,Sudan,NaN,...,NaN,NaN,NaN,0,NaN,NaN,Northern Africa,35482233,NaN,NaN
130,NaN,NaN,NaN,131,4.335456,-55.898438,NaN,NaN,Suriname,NaN,...,NaN,NaN,NaN,1,NaN,NaN,South America,573311,NaN,NaN
131,NaN,NaN,NaN,132,61.314264,15.231171,NaN,NaN,Sweden,NaN,...,NaN,NaN,NaN,0,NaN,NaN,Northern Europe,9723809,NaN,NaN
132,NaN,NaN,NaN,133,35.054732,38.759766,NaN,NaN,Syria,NaN,...,NaN,NaN,NaN,0,NaN,NaN,Western Asia,17951639,NaN,NaN
133,NaN,NaN,NaN,134,23.882698,121.014404,NaN,NaN,Taiwan,NaN,...,NaN,NaN,NaN,0,NaN,NaN,Eastern Asia,23359928,NaN,NaN
134,NaN,NaN,NaN,135,-6.385978,35.240356,NaN,NaN,Tanzania,NaN,...,NaN,NaN,NaN,0,NaN,NaN,Eastern Africa,49639138,NaN,NaN
135,NaN,NaN,NaN,136,15.604314,100.870285,NaN,NaN,Thailand,NaN,...,NaN,NaN,NaN,0,NaN,NaN,Southeastern Asia,67741401,NaN,NaN
136,NaN,NaN,NaN,137,-8.756491,125.897827,NaN,NaN,Timor Leste,NaN,...,NaN,NaN,NaN,0,NaN,NaN,Southeastern Asia,1201542,NaN,NaN
137,NaN,NaN,NaN,138,8.400375,1.068420,NaN,NaN,Togo,NaN,...,NaN,NaN,NaN,0,NaN,NaN,Western Africa,7351374,NaN,NaN
138,NaN,NaN,NaN,139,-21.178986,-175.198242,NaN,NaN,Tonga,NaN,...,NaN,NaN,NaN,1,NaN,NaN,Polynesia,106440,NaN,NaN
139,NaN,NaN,NaN,140,10.442975,-61.272337,NaN,NaN,Trinidad Tob,NaN,...,NaN,NaN,NaN,1,NaN,NaN,Caribbean,1223916,NaN,NaN
140,NaN,NaN,NaN,141,34.010550,9.593815,NaN,NaN,Tunisia,NaN,...,NaN,NaN,NaN,0,NaN,NaN,Northern Africa,10937521,NaN,NaN
141,NaN,NaN,NaN,142,39.527348,34.628908,NaN,NaN,Turkey,NaN,...,NaN,NaN,NaN,0,NaN,NaN,Western Asia,81619392,NaN,NaN
142,NaN,NaN,NaN,143,-7.478442,178.679921,NaN,NaN,Tuvalu,NaN,...,NaN,NaN,NaN,1,NaN,NaN,Polynesia,10782,NaN,NaN
143,NaN,NaN,NaN,144,53.032955,-1.538080,NaN,NaN,UK,NaN,...,NaN,NaN,NaN,0,NaN,NaN,Northern Europe,63742977,NaN,NaN
144,NaN,NaN,NaN,145,48.942347,33.178719,NaN,NaN,Ukraine,NaN,...,NaN,NaN,NaN,0,NaN,NaN,Eastern Europe,44291413,NaN,NaN
145,NaN,NaN,NaN,146,23.913460,54.448252,NaN,NaN,Untd Arab Em,NaN,...,NaN,NaN,NaN,0,NaN,NaN,Western Asia,5628805,NaN,NaN
146,NaN,NaN,NaN,147,-32.888813,-56.206051,NaN,NaN,Uruguay,NaN,...,NaN,NaN,NaN,0,NaN,NaN,South America,3332972,NaN,NaN
147,NaN,NaN,NaN,148,40.278267,-104.690304,NaN,NaN,USA,NaN,...,NaN,NaN,NaN,0,NaN,NaN,Northern America,318892103,NaN,NaN
148,NaN,NaN,NaN,149,-15.376706,166.959158,NaN,NaN,Vanuatu,NaN,...,NaN,NaN,NaN,1,NaN,NaN,Melanesia,266937,NaN,NaN
149,NaN,NaN,NaN,150,7.927041,-66.369987,NaN,NaN,Venezuela,NaN,...,NaN,NaN,NaN,0,NaN,NaN,South America,28868486,NaN,NaN
150,NaN,NaN,NaN,151,14.058324,108.277199,NaN,NaN,Viet Nam,NaN,...,NaN,NaN,NaN,0,NaN,NaN,Southeastern Asia,93421835,NaN,NaN
151,NaN,NaN,NaN,152,15.990375,47.373059,NaN,NaN,Yemen,NaN,...,NaN,NaN,NaN,0,NaN,NaN,Western Asia,26052966,NaN,NaN

In [76]:
 pd.concat([subsidies_short,countrydata_short],axis=1)

,RegionName,Countries,Type,ReEst_Subsidy2009,%SSFsubsidies_assessed,SSF_USD_1000,weighted_by_sectorsize,Data_group,%SSF_totalCatch_EEZ,%SSF_totalCatch_Country,Countries,Region,Subregion
0,Asia,Philippines,A1,150317.400345,28.662420,43084.605195,TRUE,3,28.662420,25.475502,Albania,NaN,Southern Europe
1,Asia,Philippines,A2,106929.633393,25.475502,27240.860867,TRUE,3,28.662420,25.475502,Algeria,NaN,Northern Africa
2,Asia,Philippines,A3,14325.450291,28.662420,4106.020784,TRUE,3,28.662420,25.475502,Angola,NaN,Middle Africa
3,Asia,Philippines,B1,291723.649784,25.475502,74318.064163,TRUE,3,28.662420,25.475502,Antigua Barb,NaN,Caribbean
4,Asia,Philippines,B2,5987.405124,25.475502,1525.321511,TRUE,3,28.662420,25.475502,Argentina,NaN,South America
5,Asia,Philippines,B3,0.000000,NaN,NaN,NaN,NaN,28.662420,25.475502,Australia,NaN,Australia and New Zealand
6,Asia,Philippines,B4,2305.468110,20.000000,461.093622,FALSE,1,28.662420,25.475502,Bahamas,NaN,Caribbean
7,Asia,Philippines,B5,92663.171127,0.000000,0.000000,FALSE,2,28.662420,25.475502,Bahrain,NaN,Western Asia
8,Asia,Philippines,B6,0.000000,NaN,NaN,NaN,NaN,28.662420,25.475502,Bangladesh,NaN,Southern Asia
9,Asia,Philippines,C1,35605.265432,100.000000,35605.265432,FALSE,1,28.662420,25.475502,Barbados,NaN,Caribbean
10,Asia,Philippines,C2,0.000000,NaN,NaN,NaN,NaN,28.662420,25.475502,Belgium,NaN,Western Europe
11,Asia,Philippines,C3,21737.044519,100.000000,21737.044519,FALSE,1,28.662420,25.475502,Belize,NaN,Central America
12,Asia,India,A1,6450.238140,42.381331,2733.696798,TRUE,3,42.381331,41.498407,Benin,NaN,Western Africa
13,Asia,India,A2,2179.113474,41.498407,904.297382,TRUE,3,42.381331,41.498407,Bosnia Herzg,NaN,Southern Europe
14,Asia,India,A3,1781.843735,42.381331,755.169097,TRUE,3,42.381331,41.498407,Brazil,NaN,South America
15,Asia,India,B1,4035.395412,0.000000,0.000000,FALSE,2,42.381331,41.498407,Brunei Darsm,NaN,Southeastern Asia
16,Asia,India,B2,3751.334747,20.000000,750.266949,FALSE,1,42.381331,41.498407,Bulgaria,NaN,Eastern Europe
17,Asia,India,B3,4062.029933,17.000000,690.545089,FALSE,1,42.381331,41.498407,Cambodia,NaN,Southeastern Asia
18,Asia,India,B4,4035.395412,25.000000,1008.848853,FALSE,1,42.381331,41.498407,Cameroon,NaN,Middle Africa
19,Asia,India,B5,123957.406261,20.000000,24791.481252,FALSE,1,42.381331,41.498407,Canada,NaN,Northern America
20,Asia,India,B6,0.000000,NaN,NaN,NaN,NaN,42.381331,41.498407,Cape Verde,NaN,Western Africa
21,Asia,India,C1,5084.598507,41.498407,2110.027391,TRUE,3,42.381331,41.498407,Chile,NaN,South America
22,Asia,India,C2,0.000000,NaN,NaN,NaN,NaN,42.381331,41.498407,China,NaN,Eastern Asia
23,Asia,India,C3,2905.485033,100.000000,2905.485033,FALSE,1,42.381331,41.498407,Colombia,NaN,South America
24,Asia,Thailand,A1,18538.640909,42.279905,7838.119773,TRUE,3,42.279905,13.560304,Comoros,NaN,Eastern Africa
25,Asia,Thailand,A2,2067.787646,13.560304,280.398288,TRUE,3,42.279905,13.560304,Congo Dem Rep,NaN,Middle Africa
26,Asia,Thailand,A3,2884.411251,42.279905,1219.526338,TRUE,3,42.279905,13.560304,Congo Rep,NaN,Middle Africa
27,Asia,Thailand,B1,58456.068748,25.000000,14614.017187,FALSE,1,42.279905,13.560304,Costa Rica,NaN,Central America
28,Asia,Thailand,B2,242.934986,13.560304,32.942722,TRUE,3,42.279905,13.560304,Cote d'Ivoire,NaN,Western Africa
29,Asia,Thailand,B3,8015.852723,0.000000,0.000000,FALSE,2,42.279905,13.560304,Croatia,NaN,Southern Europe
...,...,...,...,...,...,...,...,...,...,...,...,...,...
774,Europe,Romania,B4,25694.478873,1.300000,334.028225,1,3,91.666667,1.269394,NaN,NaN,NaN
775,Europe,Romania,B5,47.431407,1.300000,0.616608,1,3,91.666667,1.269394,NaN,NaN,NaN
776,Europe,Romania,B6,0.000000,NaN,NaN,NaN,NaN,91.666667,1.269394,NaN,NaN,NaN
777,Europe,Romania,C1,10.566188,1.300000,0.137360,1,3,91.666667,1.269394,NaN,NaN,NaN
778,Europe,Romania,C2,0.000000,NaN,NaN,NaN,NaN,91.666667,1.269394,NaN,NaN,NaN
779,Europe,Romania,C3,0.000000,NaN,NaN,NaN,NaN,91.666667,1.269394,NaN,NaN,NaN
780,Europe,Ukraine,A1,9039.338360,10.300000,931.051851,1,3,10.292729,3.028619,NaN,NaN,NaN
781,Europe,Ukraine,A2,0.000000,NaN,NaN,NaN,NaN,10.292729,3.028619,NaN,NaN,NaN
782,Europe,Ukraine,A3,815.509180,10.300000,83.997446,1,3,10.292729,3.028619,NaN,NaN,NaN
783,Europe,Ukraine,B1,16357.036931,3.000000,490.711108,1,3,10.292729,3.028619,NaN,NaN,NaN
784,Europe,Ukraine,B2,6.506637,3.000000,0.195199,1,3,10.292729,3.028619,NaN,NaN,NaN
785,Europe,Ukraine,B3,0.000000,NaN,NaN,NaN,NaN,10.292729,3.028619,NaN,NaN,NaN
786,Europe,Ukraine,B4,0.000000,NaN,NaN,NaN,NaN,10.292729,3.028619,NaN,NaN,NaN
787,Europe,Ukraine,B5,0.000000,NaN,NaN,NaN,NaN,10.292729,3.028619,NaN,NaN,NaN
788,Europe,Ukraine,B6,0.000000,NaN,NaN,NaN,NaN,10.292729,3.028619,NaN,NaN,NaN
789,Europe,Ukraine,C1,0.000000,NaN,NaN,NaN,NaN,10.292729,3.028619,NaN,NaN,NaN
790,Europe,Ukraine,C2,0.000000,NaN,NaN,NaN,NaN,10.292729,3.028619,NaN,NaN,NaN
791,Europe,Ukraine,C3,1218.802917,100.000000,1218.802917,0,3,10.292729,3.028619,NaN,NaN,NaN
792,Europe,Denmark,A1,27710.195182,7.800000,2161.395224,1,3,7.759108,6.799901,NaN,NaN,NaN
793,Europe,Denmark,A2,12472.157835,7.800000,972.828311,1,3,7.759108,6.799901,NaN,NaN,NaN
794,Europe,Denmark,A3,27261.643121,7.800000,2126.408163,1,3,7.759108,6.799901,NaN,NaN,NaN
795,Europe,Denmark,B1,26508.544867,6.800000,1802.581051,1,3,7.759108,6.799901,NaN,NaN,NaN
796,Europe,Denmark,B2,0.000000,NaN,NaN,NaN,NaN,7.759108,6.799901,NaN,NaN,NaN
797,Europe,Denmark,B3,0.000000,NaN,NaN,NaN,NaN,7.759108,6.799901,NaN,NaN,NaN
798,Europe,Denmark,B4,18192.846849,18.300000,3329.290973,0,2,7.759108,6.799901,NaN,NaN,NaN
799,Europe,Denmark,B5,0.000000,NaN,NaN,NaN,NaN,7.759108,6.799901,NaN,NaN,NaN
800,Europe,Denmark,B6,2867.290462,0.000000,0.000000,1,3,7.759108,6.799901,NaN,NaN,NaN
801,Europe,Denmark,C1,23594.021906,5.100000,1203.295117,0,2,7.759108,6.799901,NaN,NaN,NaN
802,Europe,Denmark,C2,7601.016403,0.000000,0.000000,0,3,7.759108,6.799901,NaN,NaN,NaN
803,Europe,Denmark,C3,0.000000,NaN,NaN,NaN,NaN,7.759108,6.799901,NaN,NaN,NaN

In [77]:
 pd.concat([subsidies_short,countrydata_short],axis = 1, join_axes=[subsidies_short.index])

,RegionName,Countries,Type,ReEst_Subsidy2009,%SSFsubsidies_assessed,SSF_USD_1000,weighted_by_sectorsize,Data_group,%SSF_totalCatch_EEZ,%SSF_totalCatch_Country,Countries,Region,Subregion
0,Asia,Philippines,A1,150317.400345,28.662420,43084.605195,TRUE,3,28.662420,25.475502,Albania,NaN,Southern Europe
1,Asia,Philippines,A2,106929.633393,25.475502,27240.860867,TRUE,3,28.662420,25.475502,Algeria,NaN,Northern Africa
2,Asia,Philippines,A3,14325.450291,28.662420,4106.020784,TRUE,3,28.662420,25.475502,Angola,NaN,Middle Africa
3,Asia,Philippines,B1,291723.649784,25.475502,74318.064163,TRUE,3,28.662420,25.475502,Antigua Barb,NaN,Caribbean
4,Asia,Philippines,B2,5987.405124,25.475502,1525.321511,TRUE,3,28.662420,25.475502,Argentina,NaN,South America
5,Asia,Philippines,B3,0.000000,NaN,NaN,NaN,NaN,28.662420,25.475502,Australia,NaN,Australia and New Zealand
6,Asia,Philippines,B4,2305.468110,20.000000,461.093622,FALSE,1,28.662420,25.475502,Bahamas,NaN,Caribbean
7,Asia,Philippines,B5,92663.171127,0.000000,0.000000,FALSE,2,28.662420,25.475502,Bahrain,NaN,Western Asia
8,Asia,Philippines,B6,0.000000,NaN,NaN,NaN,NaN,28.662420,25.475502,Bangladesh,NaN,Southern Asia
9,Asia,Philippines,C1,35605.265432,100.000000,35605.265432,FALSE,1,28.662420,25.475502,Barbados,NaN,Caribbean
10,Asia,Philippines,C2,0.000000,NaN,NaN,NaN,NaN,28.662420,25.475502,Belgium,NaN,Western Europe
11,Asia,Philippines,C3,21737.044519,100.000000,21737.044519,FALSE,1,28.662420,25.475502,Belize,NaN,Central America
12,Asia,India,A1,6450.238140,42.381331,2733.696798,TRUE,3,42.381331,41.498407,Benin,NaN,Western Africa
13,Asia,India,A2,2179.113474,41.498407,904.297382,TRUE,3,42.381331,41.498407,Bosnia Herzg,NaN,Southern Europe
14,Asia,India,A3,1781.843735,42.381331,755.169097,TRUE,3,42.381331,41.498407,Brazil,NaN,South America
15,Asia,India,B1,4035.395412,0.000000,0.000000,FALSE,2,42.381331,41.498407,Brunei Darsm,NaN,Southeastern Asia
16,Asia,India,B2,3751.334747,20.000000,750.266949,FALSE,1,42.381331,41.498407,Bulgaria,NaN,Eastern Europe
17,Asia,India,B3,4062.029933,17.000000,690.545089,FALSE,1,42.381331,41.498407,Cambodia,NaN,Southeastern Asia
18,Asia,India,B4,4035.395412,25.000000,1008.848853,FALSE,1,42.381331,41.498407,Cameroon,NaN,Middle Africa
19,Asia,India,B5,123957.406261,20.000000,24791.481252,FALSE,1,42.381331,41.498407,Canada,NaN,Northern America
20,Asia,India,B6,0.000000,NaN,NaN,NaN,NaN,42.381331,41.498407,Cape Verde,NaN,Western Africa
21,Asia,India,C1,5084.598507,41.498407,2110.027391,TRUE,3,42.381331,41.498407,Chile,NaN,South America
22,Asia,India,C2,0.000000,NaN,NaN,NaN,NaN,42.381331,41.498407,China,NaN,Eastern Asia
23,Asia,India,C3,2905.485033,100.000000,2905.485033,FALSE,1,42.381331,41.498407,Colombia,NaN,South America
24,Asia,Thailand,A1,18538.640909,42.279905,7838.119773,TRUE,3,42.279905,13.560304,Comoros,NaN,Eastern Africa
25,Asia,Thailand,A2,2067.787646,13.560304,280.398288,TRUE,3,42.279905,13.560304,Congo Dem Rep,NaN,Middle Africa
26,Asia,Thailand,A3,2884.411251,42.279905,1219.526338,TRUE,3,42.279905,13.560304,Congo Rep,NaN,Middle Africa
27,Asia,Thailand,B1,58456.068748,25.000000,14614.017187,FALSE,1,42.279905,13.560304,Costa Rica,NaN,Central America
28,Asia,Thailand,B2,242.934986,13.560304,32.942722,TRUE,3,42.279905,13.560304,Cote d'Ivoire,NaN,Western Africa
29,Asia,Thailand,B3,8015.852723,0.000000,0.000000,FALSE,2,42.279905,13.560304,Croatia,NaN,Southern Europe
...,...,...,...,...,...,...,...,...,...,...,...,...,...
774,Europe,Romania,B4,25694.478873,1.300000,334.028225,1,3,91.666667,1.269394,NaN,NaN,NaN
775,Europe,Romania,B5,47.431407,1.300000,0.616608,1,3,91.666667,1.269394,NaN,NaN,NaN
776,Europe,Romania,B6,0.000000,NaN,NaN,NaN,NaN,91.666667,1.269394,NaN,NaN,NaN
777,Europe,Romania,C1,10.566188,1.300000,0.137360,1,3,91.666667,1.269394,NaN,NaN,NaN
778,Europe,Romania,C2,0.000000,NaN,NaN,NaN,NaN,91.666667,1.269394,NaN,NaN,NaN
779,Europe,Romania,C3,0.000000,NaN,NaN,NaN,NaN,91.666667,1.269394,NaN,NaN,NaN
780,Europe,Ukraine,A1,9039.338360,10.300000,931.051851,1,3,10.292729,3.028619,NaN,NaN,NaN
781,Europe,Ukraine,A2,0.000000,NaN,NaN,NaN,NaN,10.292729,3.028619,NaN,NaN,NaN
782,Europe,Ukraine,A3,815.509180,10.300000,83.997446,1,3,10.292729,3.028619,NaN,NaN,NaN
783,Europe,Ukraine,B1,16357.036931,3.000000,490.711108,1,3,10.292729,3.028619,NaN,NaN,NaN
784,Europe,Ukraine,B2,6.506637,3.000000,0.195199,1,3,10.292729,3.028619,NaN,NaN,NaN
785,Europe,Ukraine,B3,0.000000,NaN,NaN,NaN,NaN,10.292729,3.028619,NaN,NaN,NaN
786,Europe,Ukraine,B4,0.000000,NaN,NaN,NaN,NaN,10.292729,3.028619,NaN,NaN,NaN
787,Europe,Ukraine,B5,0.000000,NaN,NaN,NaN,NaN,10.292729,3.028619,NaN,NaN,NaN
788,Europe,Ukraine,B6,0.000000,NaN,NaN,NaN,NaN,10.292729,3.028619,NaN,NaN,NaN
789,Europe,Ukraine,C1,0.000000,NaN,NaN,NaN,NaN,10.292729,3.028619,NaN,NaN,NaN
790,Europe,Ukraine,C2,0.000000,NaN,NaN,NaN,NaN,10.292729,3.028619,NaN,NaN,NaN
791,Europe,Ukraine,C3,1218.802917,100.000000,1218.802917,0,3,10.292729,3.028619,NaN,NaN,NaN
792,Europe,Denmark,A1,27710.195182,7.800000,2161.395224,1,3,7.759108,6.799901,NaN,NaN,NaN
793,Europe,Denmark,A2,12472.157835,7.800000,972.828311,1,3,7.759108,6.799901,NaN,NaN,NaN
794,Europe,Denmark,A3,27261.643121,7.800000,2126.408163,1,3,7.759108,6.799901,NaN,NaN,NaN
795,Europe,Denmark,B1,26508.544867,6.800000,1802.581051,1,3,7.759108,6.799901,NaN,NaN,NaN
796,Europe,Denmark,B2,0.000000,NaN,NaN,NaN,NaN,7.759108,6.799901,NaN,NaN,NaN
797,Europe,Denmark,B3,0.000000,NaN,NaN,NaN,NaN,7.759108,6.799901,NaN,NaN,NaN
798,Europe,Denmark,B4,18192.846849,18.300000,3329.290973,0,2,7.759108,6.799901,NaN,NaN,NaN
799,Europe,Denmark,B5,0.000000,NaN,NaN,NaN,NaN,7.759108,6.799901,NaN,NaN,NaN
800,Europe,Denmark,B6,2867.290462,0.000000,0.000000,1,3,7.759108,6.799901,NaN,NaN,NaN
801,Europe,Denmark,C1,23594.021906,5.100000,1203.295117,0,2,7.759108,6.799901,NaN,NaN,NaN
802,Europe,Denmark,C2,7601.016403,0.000000,0.000000,0,3,7.759108,6.799901,NaN,NaN,NaN
803,Europe,Denmark,C3,0.000000,NaN,NaN,NaN,NaN,7.759108,6.799901,NaN,NaN,NaN

In [78]:
subsidies_short.head()

,RegionName,Countries,Type,ReEst_Subsidy2009,%SSFsubsidies_assessed,SSF_USD_1000,weighted_by_sectorsize,Data_group,%SSF_totalCatch_EEZ,%SSF_totalCatch_Country
0,Asia,Philippines,A1,150317.400345,28.662420,43084.605195,TRUE,3,28.66242,25.475502
1,Asia,Philippines,A2,106929.633393,25.475502,27240.860867,TRUE,3,28.66242,25.475502
2,Asia,Philippines,A3,14325.450291,28.662420,4106.020784,TRUE,3,28.66242,25.475502
3,Asia,Philippines,B1,291723.649784,25.475502,74318.064163,TRUE,3,28.66242,25.475502
4,Asia,Philippines,B2,5987.405124,25.475502,1525.321511,TRUE,3,28.66242,25.475502

In [79]:
countrydata_short.head()

      Countries  Region        Subregion
0       Albania     NaN  Southern Europe
1       Algeria     NaN  Northern Africa
2        Angola     NaN    Middle Africa
3  Antigua Barb     NaN        Caribbean
4     Argentina     NaN    South America

In [80]:
countrydata_short['Subregion'].dtype

dtype('O')

In [81]:
subsidies_short['Data_group'].dtype

dtype('float64')

In [82]:
for col in subsidies_short:
    print col, subsidies_short[col].dtypes

RegionName object
Countries object
Type object
ReEst_Subsidy2009 float64
%SSFsubsidies_assessed float64
SSF_USD_1000 float64
weighted_by_sectorsize object
Data_group float64
%SSF_totalCatch_EEZ float64
%SSF_totalCatch_Country float64

In [83]:
for col in countrydata_short:
    print col, countrydata_short[col].dtypes

Countries object
Region float64
Subregion object

In [84]:
merged_countries_short = pd.merge(left=subsidies_short,right=countrydata_short, how='left')

In [85]:
merged_countries_short.head()

,RegionName,Countries,Type,ReEst_Subsidy2009,%SSFsubsidies_assessed,SSF_USD_1000,weighted_by_sectorsize,Data_group,%SSF_totalCatch_EEZ,%SSF_totalCatch_Country,Region,Subregion
0,Asia,Philippines,A1,150317.400345,28.662420,43084.605195,TRUE,3,28.66242,25.475502,NaN,Southeastern Asia
1,Asia,Philippines,A2,106929.633393,25.475502,27240.860867,TRUE,3,28.66242,25.475502,NaN,Southeastern Asia
2,Asia,Philippines,A3,14325.450291,28.662420,4106.020784,TRUE,3,28.66242,25.475502,NaN,Southeastern Asia
3,Asia,Philippines,B1,291723.649784,25.475502,74318.064163,TRUE,3,28.66242,25.475502,NaN,Southeastern Asia
4,Asia,Philippines,B2,5987.405124,25.475502,1525.321511,TRUE,3,28.66242,25.475502,NaN,Southeastern Asia

In [86]:
merged_countries = pd.merge(left=subsidies,right=countrydata, how='left')

In [87]:
merged_countries.tail()

,ID,Cnumber,RegionID,RegionName,Type,SubType,Category,ReEst_Subsidy2009,NewData,Developed,...,SSF_USD_1000,CID,Subregion,CLon,CLat,SIDS,TotPop,HDI,Develop,GDP
799,476,208,1,Europe,B5,Tax exemption,Bad,0.000000,False,Developed,...,NaN,33,Northern Europe,9.30542,56.284154,0,5569077,0.9,High,2.487000e+11
800,477,208,1,Europe,B6,Fishing access,Bad,2867.290462,True,Developed,...,0.000000,33,Northern Europe,9.30542,56.284154,0,5569077,0.9,High,2.487000e+11
801,479,208,1,Europe,C1,Fisher assistance,Ugly,23594.021906,True,Developed,...,1203.295117,33,Northern Europe,9.30542,56.284154,0,5569077,0.9,High,2.487000e+11
802,480,208,1,Europe,C2,Vessel buyback,Ugly,7601.016403,True,Developed,...,0.000000,33,Northern Europe,9.30542,56.284154,0,5569077,0.9,High,2.487000e+11
803,481,208,1,Europe,C3,Rural fisher communities,Ugly,0.000000,False,Developed,...,NaN,33,Northern Europe,9.30542,56.284154,0,5569077,0.9,High,2.487000e+11

In [88]:
merged_countries

,ID,Cnumber,RegionID,RegionName,Type,SubType,Category,ReEst_Subsidy2009,NewData,Developed,...,SSF_USD_1000,CID,Subregion,CLon,CLat,SIDS,TotPop,HDI,Develop,GDP
0,1418,608,2,Asia,A1,Fisheries mangt.,Good,150317.400345,False,Developing,...,43084.605195,108,Southeastern Asia,120.884124,15.351374,0,84619974,0.771,Medium,2.500000e+11
1,1419,608,2,Asia,A2,Fishery R&D,Good,106929.633393,False,Developing,...,27240.860867,108,Southeastern Asia,120.884124,15.351374,0,84619974,0.771,Medium,2.500000e+11
2,1420,608,2,Asia,A3,MPAs,Good,14325.450291,False,Developing,...,4106.020784,108,Southeastern Asia,120.884124,15.351374,0,84619974,0.771,Medium,2.500000e+11
3,1421,608,2,Asia,B1,Boat constsruct. & renov.,Bad,291723.649784,False,Developing,...,74318.064163,108,Southeastern Asia,120.884124,15.351374,0,84619974,0.771,Medium,2.500000e+11
4,1422,608,2,Asia,B2,Fisheries dev. projects,Bad,5987.405124,True,Developing,...,1525.321511,108,Southeastern Asia,120.884124,15.351374,0,84619974,0.771,Medium,2.500000e+11
5,1423,608,2,Asia,B3,Fishing port develop.,Bad,0.000000,False,Developing,...,NaN,108,Southeastern Asia,120.884124,15.351374,0,84619974,0.771,Medium,2.500000e+11
6,1424,608,2,Asia,B4,Markt. & storage infrast.,Bad,2305.468110,False,Developing,...,461.093622,108,Southeastern Asia,120.884124,15.351374,0,84619974,0.771,Medium,2.500000e+11
7,1425,608,2,Asia,B5,Tax exemption,Bad,92663.171127,False,Developing,...,0.000000,108,Southeastern Asia,120.884124,15.351374,0,84619974,0.771,Medium,2.500000e+11
8,1426,608,2,Asia,B6,Fishing access,Bad,0.000000,False,Developing,...,NaN,108,Southeastern Asia,120.884124,15.351374,0,84619974,0.771,Medium,2.500000e+11
9,1428,608,2,Asia,C1,Fisher assistance,Ugly,35605.265432,True,Developing,...,35605.265432,108,Southeastern Asia,120.884124,15.351374,0,84619974,0.771,Medium,2.500000e+11
10,1429,608,2,Asia,C2,Vessel buyback,Ugly,0.000000,False,Developing,...,NaN,108,Southeastern Asia,120.884124,15.351374,0,84619974,0.771,Medium,2.500000e+11
11,1430,608,2,Asia,C3,Rural fisher communities,Ugly,21737.044519,False,Developing,...,21737.044519,108,Southeastern Asia,120.884124,15.351374,0,84619974,0.771,Medium,2.500000e+11
12,820,356,2,Asia,A1,Fisheries mangt.,Good,6450.238140,True,Developing,...,2733.696798,62,Southern Asia,78.936772,22.955232,0,1236344631,0.586,Medium,7.277000e+12
13,821,356,2,Asia,A2,Fishery R&D,Good,2179.113474,True,Developing,...,904.297382,62,Southern Asia,78.936772,22.955232,0,1236344631,0.586,Medium,7.277000e+12
14,822,356,2,Asia,A3,MPAs,Good,1781.843735,False,Developing,...,755.169097,62,Southern Asia,78.936772,22.955232,0,1236344631,0.586,Medium,7.277000e+12
15,823,356,2,Asia,B1,Boat constsruct. & renov.,Bad,4035.395412,True,Developing,...,0.000000,62,Southern Asia,78.936772,22.955232,0,1236344631,0.586,Medium,7.277000e+12
16,824,356,2,Asia,B2,Fisheries dev. projects,Bad,3751.334747,True,Developing,...,750.266949,62,Southern Asia,78.936772,22.955232,0,1236344631,0.586,Medium,7.277000e+12
17,825,356,2,Asia,B3,Fishing port develop.,Bad,4062.029933,True,Developing,...,690.545089,62,Southern Asia,78.936772,22.955232,0,1236344631,0.586,Medium,7.277000e+12
18,826,356,2,Asia,B4,Markt. & storage infrast.,Bad,4035.395412,True,Developing,...,1008.848853,62,Southern Asia,78.936772,22.955232,0,1236344631,0.586,Medium,7.277000e+12
19,827,356,2,Asia,B5,Tax exemption,Bad,123957.406261,False,Developing,...,24791.481252,62,Southern Asia,78.936772,22.955232,0,1236344631,0.586,Medium,7.277000e+12
20,828,356,2,Asia,B6,Fishing access,Bad,0.000000,False,Developing,...,NaN,62,Southern Asia,78.936772,22.955232,0,1236344631,0.586,Medium,7.277000e+12
21,830,356,2,Asia,C1,Fisher assistance,Ugly,5084.598507,True,Developing,...,2110.027391,62,Southern Asia,78.936772,22.955232,0,1236344631,0.586,Medium,7.277000e+12
22,831,356,2,Asia,C2,Vessel buyback,Ugly,0.000000,False,Developing,...,NaN,62,Southern Asia,78.936772,22.955232,0,1236344631,0.586,Medium,7.277000e+12
23,832,356,2,Asia,C3,Rural fisher communities,Ugly,2905.485033,True,Developing,...,2905.485033,62,Southern Asia,78.936772,22.955232,0,1236344631,0.586,Medium,7.277000e+12
24,1756,764,2,Asia,A1,Fisheries mangt.,Good,18538.640909,False,Developing,...,7838.119773,136,Southeastern Asia,100.870285,15.604314,0,67741401,0.722,Medium,9.901000e+11
25,1757,764,2,Asia,A2,Fishery R&D,Good,2067.787646,False,Developing,...,280.398288,136,Southeastern Asia,100.870285,15.604314,0,67741401,0.722,Medium,9.901000e+11
26,1758,764,2,Asia,A3,MPAs,Good,2884.411251,False,Developing,...,1219.526338,136,Southeastern Asia,100.870285,15.604314,0,67741401,0.722,Medium,9.901000e+11
27,1759,764,2,Asia,B1,Boat constsruct. & renov.,Bad,58456.068748,False,Developing,...,14614.017187,136,Southeastern Asia,100.870285,15.604314,0,67741401,0.722,Medium,9.901000e+11
28,1760,764,2,Asia,B2,Fisheries dev. projects,Bad,242.934986,True,Developing,...,32.942722,136,Southeastern Asia,100.870285,15.604314,0,67741401,0.722,Medium,9.901000e+11
29,1761,764,2,Asia,B3,Fishing port develop.,Bad,8015.852723,True,Developing,...,0.000000,136,Southeastern Asia,100.870285,15.604314,0,67741401,0.722,Medium,9.901000e+11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
774,1502,642,1,Europe,B4,Markt. & storage infrast.,Bad,25694.478873,True,Developing,...,334.028225,112,Eastern Europe,24.864120,45.849698,0,21729871,0.785,High,3.865000e+11
775,1503,642,1,Europe,B5,Tax exemption,Bad,47.431407,False,Developing,...,0.616608,112,Eastern Europe,24.864120,45.849698,0,21729871,0.785,High,3.865000e+11
776,1504,642,1,Europe,B6,Fishing access,Bad,0.000000,False,Developing,...,NaN,112,Eastern Europe,24.864120,45.849698,0,21729871,0.785,High,3.865000e+11
777,1506,642,1,Europe,C1,Fisher assistance,Ugly,10.566188,True,Developing,...,0.137360,112,Eastern Europe,24.864120,45.849698,0,21729871,0.785,High,3.865000e+11
778,1507,642,1,Europe,C2,Vessel buyback,Ugly,0.000000,False,Developing,...,NaN,112,Eastern Europe,24.864120,45.849698,0,21729871,0.785,High,3.865000e+11
779,1508,642,1,Europe,C3,Rural fisher communities,Ugly,0.000000,False,Developing,...,NaN,112,Eastern Europe,24.864120,45.849698,0,21729871,0.785,High,3.865000e+11
780,1860,804,1,Europe,A1,Fisheries mangt.,Good,9039.338360,False,Developing,...,931.051851,145,Eastern Europe,33.178719,48.942347,0,44291413,0.734,High,3.731000e+11
781,1861,804,1,Europe,A2,Fishery R&D,Good,0.000000,False,Developing,...,NaN,145,Eastern Europe,33.178719,48.942347,0,44291413,0.734,High,3.731000e+11
782,1862,804,1,Europe,A3,MPAs,Good,815.509180,False,Developing,...,83.997446,145,Eastern Europe,33.178719,48.942347,0,44291413,0.734,High,3.731000e+11
783,1863,804,1,Europe,B1,Boat constsruct. & renov.,Bad,16357.036931,False,Developing,...,490.711108,145,Eastern Europe,33.178719,48.942347,0,44291413,0.734,High,3.731000e+11
784,1864,804,1,Europe,B2,Fisheries dev. projects,Bad,6.506637,True,Developing,...,0.195199,145,Eastern Europe,33.178719,48.942347,0,44291413,0.734,High,3.731000e+11
785,1865,804,1,Europe,B3,Fishing port develop.,Bad,0.000000,False,Developing,...,NaN,145,Eastern Europe,33.178719,48.942347,0,44291413,0.734,High,3.731000e+11
786,1866,804,1,Europe,B4,Markt. & storage infrast.,Bad,0.000000,False,Developing,...,NaN,145,Eastern Europe,33.178719,48.942347,0,44291413,0.734,High,3.731000e+11
787,1867,804,1,Europe,B5,Tax exemption,Bad,0.000000,False,Developing,...,NaN,145,Eastern Europe,33.178719,48.942347,0,44291413,0.734,High,3.731000e+11
788,1868,804,1,Europe,B6,Fishing access,Bad,0.000000,False,Developing,...,NaN,145,Eastern Europe,33.178719,48.942347,0,44291413,0.734,High,3.731000e+11
789,1870,804,1,Europe,C1,Fisher assistance,Ugly,0.000000,False,Developing,...,NaN,145,Eastern Europe,33.178719,48.942347,0,44291413,0.734,High,3.731000e+11
790,1871,804,1,Europe,C2,Vessel buyback,Ugly,0.000000,False,Developing,...,NaN,145,Eastern Europe,33.178719,48.942347,0,44291413,0.734,High,3.731000e+11
791,1872,804,1,Europe,C3,Rural fisher communities,Ugly,1218.802917,False,Developing,...,1218.802917,145,Eastern Europe,33.178719,48.942347,0,44291413,0.734,High,3.731000e+11
792,469,208,1,Europe,A1,Fisheries mangt.,Good,27710.195182,True,Developed,...,2161.395224,33,Northern Europe,9.305420,56.284154,0,5569077,0.900,High,2.487000e+11
793,470,208,1,Europe,A2,Fishery R&D,Good,12472.157835,True,Developed,...,972.828311,33,Northern Europe,9.305420,56.284154,0,5569077,0.900,High,2.487000e+11
794,471,208,1,Europe,A3,MPAs,Good,27261.643121,False,Developed,...,2126.408163,33,Northern Europe,9.305420,56.284154,0,5569077,0.900,High,2.487000e+11
795,472,208,1,Europe,B1,Boat constsruct. & renov.,Bad,26508.544867,True,Developed,...,1802.581051,33,Northern Europe,9.305420,56.284154,0,5569077,0.900,High,2.487000e+11
796,473,208,1,Europe,B2,Fisheries dev. projects,Bad,0.000000,True,Developed,...,NaN,33,Northern Europe,9.305420,56.284154,0,5569077,0.900,High,2.487000e+11
797,474,208,1,Europe,B3,Fishing port develop.,Bad,0.000000,False,Developed,...,NaN,33,Northern Europe,9.305420,56.284154,0,5569077,0.900,High,2.487000e+11
798,475,208,1,Europe,B4,Markt. & storage infrast.,Bad,18192.846849,True,Developed,...,3329.290973,33,Northern Europe,9.305420,56.284154,0,5569077,0.900,High,2.487000e+11
799,476,208,1,Europe,B5,Tax exemption,Bad,0.000000,False,Developed,...,NaN,33,Northern Europe,9.305420,56.284154,0,5569077,0.900,High,2.487000e+11
800,477,208,1,Europe,B6,Fishing access,Bad,2867.290462,True,Developed,...,0.000000,33,Northern Europe,9.305420,56.284154,0,5569077,0.900,High,2.487000e+11
801,479,208,1,Europe,C1,Fisher assistance,Ugly,23594.021906,True,Developed,...,1203.295117,33,Northern Europe,9.305420,56.284154,0,5569077,0.900,High,2.487000e+11
802,480,208,1,Europe,C2,Vessel buyback,Ugly,7601.016403,True,Developed,...,0.000000,33,Northern Europe,9.305420,56.284154,0,5569077,0.900,High,2.487000e+11
803,481,208,1,Europe,C3,Rural fisher communities,Ugly,0.000000,False,Developed,...,NaN,33,Northern Europe,9.305420,56.284154,0,5569077,0.900,High,2.487000e+11

In [89]:
groupby_subregions_type = merged_countries.groupby(['Subregion','Type']).sum()
groupby_subregions_type

                                  ID  Cnumber  RegionID  ReEst_Subsidy2009  \
Subregion                 Type
Australia and New Zealand A1    1341      590        10      129241.779085
                          A2    1343      590        10        9922.318280
                          A3    1345      590        10       79448.594283
                          B1    1347      590        10       89014.750270
                          B2    1349      590        10           0.000000
                          B3    1351      590        10           0.000000
                          B4    1353      590        10           0.000000
                          B5    1355      590        10           0.000000
                          B6    1357      590        10           0.000000
                          C1    1361      590        10       28262.262712
                          C2    1363      590        10      168997.617791
                          C3    1365      590        10           0.000000
Caribbean                 A1    1354      580         8       14204.563990
                          A2    1356      580         8           0.000000
                          A3    1358      580         8        9803.020892
                          B1    1360      580         8        8654.268922
                          B2    1362      580         8        1102.749167
                          B3    1364      580         8           0.000000
                          B4    1366      580         8        2436.401207
                          B5    1368      580         8           0.000000
                          B6    1370      580         8           0.000000
                          C1    1374      580         8           0.000000
                          C2    1376      580         8           0.000000
                          C3    1378      580         8         644.850741
Central America           A1    4229     1821        18       41031.154338
                          A2    4233     1821        18       26098.801716
                          A3    4237     1821        18       19210.143120
                          B1    4241     1821        18           0.000000
                          B2    4245     1821        18        1674.262234
                          B3    4249     1821        18           0.000000
...                              ...      ...       ...                ...
Western Africa            B4    7088     3036        18       10818.881328
                          B5    7094     3036        18       13493.031350
                          B6    7100     3036        18        6681.592074
                          C1    7112     3036        18         471.611311
                          C2    7118     3036        18           0.000000
                          C3    7124     3036        18        5680.738385
Western Asia              A1    3408     1474         4       49329.749991
                          A2    3410     1474         4        7495.464883
                          A3    3412     1474         4        6020.948473
                          B1    3414     1474         4       16006.024961
                          B2    3416     1474         4       33953.610232
                          B3    3418     1474         4           0.000000
                          B4    3420     1474         4       22024.582593
                          B5    3422     1474         4           0.000000
                          B6    3424     1474         4           0.000000
                          C1    3428     1474         4           0.000000
                          C2    3430     1474         4           0.000000
                          C3    3432     1474         4        1367.021810
Western Europe            A1    1835      778         2       37406.749168
                          A2    1837      778         2       33151.656781
                          A3    1839      778         2       22570.416613
                          B1    1841      778         2      136543.967137
                          B2    1843      778         2       11026.511790
                          B3    1845      778         2         903.788941
                          B4    1847      778         2       35520.227633
                          B5    1849      778         2           0.000000
                          B6    1851      778         2       55180.060301
                          C1    1855      778         2      135891.508438
                          C2    1857      778         2       47375.889951
                          C3    1859      778         2           0.000000

                                NewData  HDI_2005  %SSFsubsidies_assessed  \
Subregion                 Type
Australia and New Zealand A1          1     1.905               33.399670
                          A2          0     1.905               17.146119
                          A3          1     1.905               33.399670
                          B1          0     1.905               17.146119
                          B2          0     1.905                     NaN
                          B3          0     1.905                     NaN
                          B4          0     1.905                     NaN
                          B5          0     1.905                     NaN
                          B6          0     1.905                     NaN
                          C1          0     1.905              100.000000
                          C2          0     1.905                0.000000
                          C3          0     1.905                     NaN
Caribbean                 A1          0     1.574              190.100000
                          A2          0     1.574                     NaN
                          A3          0     1.574              190.100000
                          B1          0     1.574              100.000000
                          B2          1     1.574              181.792717
                          B3          0     1.574                     NaN
                          B4          0     1.574              100.000000
                          B5          0     1.574                     NaN
                          B6          0     1.574                     NaN
                          C1          0     1.574                     NaN
                          C2          0     1.574                     NaN
                          C3          0     1.574              100.000000
Central America           A1          0     3.197               67.450318
                          A2          0     3.197              143.655814
                          A3          0     3.197              115.459307
                          B1          0     3.197                     NaN
                          B2          3     3.197               35.344639
                          B3          0     3.197                     NaN
...                                 ...       ...                     ...
Western Africa            B4          1     2.864              201.549627
                          B5          0     2.864               50.000000
                          B6          1     2.864                0.000000
                          C1          1     2.864              100.000000
                          C2          0     2.864                     NaN
                          C3          0     2.864              600.000000
Western Asia              A1          0     1.587               81.100000
                          A2          0     1.587               79.900000
                          A3          0     1.587               81.100000
                          B1          0     1.587                0.000000
                          B2          1     1.587              115.000000
                          B3          0     1.587                     NaN
                          B4          0     1.587                0.000000
                          B5          0     1.587                     NaN
                          B6          0     1.587                     NaN
                          C1          0     1.587                     NaN
                          C2          0     1.587                     NaN
                          C3          0     1.587              200.000000
Western Europe            A1          2     1.905               40.762985
                          A2          2     1.905               22.617134
                          A3          0     1.905               40.932985
                          B1          2     1.905               16.400000
                          B2          2     1.905                9.900000
                          B3          0     1.905               22.117134
                          B4          2     1.905               22.617134
                          B5          0     1.905                     NaN
                          B6          2     1.905                0.000000
                          C1          2     1.905               22.617134
                          C2          1     1.905                0.000000
                          C3          0     1.905                     NaN

                                Data_group  %SSF_totalCatch_EEZ  \
Subregion                 Type
Australia and New Zealand A1             6            33.399670
                          A2             3            33.399670
                          A3             6            33.399670
                          B1             3            33.399670
                          B2           NaN            33.399670
                          B3           NaN            33.399670
                          B4           NaN            33.399670
                          B5           NaN            33.399670
                          B6           NaN            33.399670
                          C1             2            33.399670
                          C2             3            33.399670
                          C3           NaN            33.399670
Caribbean                 A1             5           190.100000
                          A2           NaN           190.100000
                          A3             5           190.100000
                          B1             2           190.100000
                          B2             5           190.100000
                          B3           NaN           190.100000
                          B4             2           190.100000
                          B5           NaN           190.100000
                          B6           NaN           190.100000
                          C1           NaN           190.100000
                          C2           NaN           190.100000
                          C3             2           190.100000
Central America           A1             9           115.452457
                          A2             8           115.452457
                          A3            12           115.452457
                          B1           NaN           115.452457
                          B2             7           115.452457
                          B3           NaN           115.452457
...                                    ...                  ...
Western Africa            B4             9           269.401466
                          B5             4           269.401466
                          B6             2           269.401466
                          C1             2           269.401466
                          C2           NaN           269.401466
                          C3            14           269.401466
Western Asia              A1             6            81.114982
                          A2             6            81.114982
                          A3             6            81.114982
                          B1             2            81.114982
                          B2             5            81.114982
                          B3           NaN            81.114982
                          B4             2            81.114982
                          B5           NaN            81.114982
                          B6           NaN            81.114982
                          C1           NaN            81.114982
                          C2           NaN            81.114982
                          C3             5            81.114982
Western Europe            A1             4            40.980712
                          A2             6            40.980712
                          A3             6            40.980712
                          B1             5            40.980712
                          B2             2            40.980712
                          B3             3            40.980712
                          B4             6            40.980712
                          B5           NaN            40.980712
                          B6             6            40.980712
                          C1             5            40.980712
                          C2             5            40.980712
                          C3           NaN            40.980712

                                %SSF_totalCatch_Country  SSF_USD_1000  CID  \
Subregion                 Type
Australia and New Zealand A1                  39.383025  21426.276002  104
                          A2                  39.383025   1701.292472  104
                          A3                  39.383025  15054.748009  104
                          B1                  39.383025  15262.574761  104
                          B2                  39.383025           NaN  104
                          B3                  39.383025           NaN  104
                          B4                  39.383025           NaN  104
                          B5                  39.383025           NaN  104
                          B6                  39.383025           NaN  104
                          C1                  39.383025  28262.262712  104
                          C2                  39.383025      0.000000  104
                          C3                  39.383025           NaN  104
Caribbean                 A1                 181.792717  13239.783898  100
                          A2                 181.792717           NaN  100
                          A3                 181.792717   9274.321445  100
                          B1                 181.792717   8654.268922  100
                          B2                 181.792717    907.279170  100
                          B3                 181.792717           NaN  100
                          B4                 181.792717   2436.401207  100
                          B5                 181.792717           NaN  100
                          B6                 181.792717           NaN  100
                          C1                 181.792717           NaN  100
                          C2                 181.792717           NaN  100
                          C3                 181.792717    644.850741  100
Central America           A1                 103.978820   6612.211493  321
                          A2                 103.978820  10784.801781  321
                          A3                 103.978820   6631.776769  321
                          B1                 103.978820           NaN  321
                          B2                 103.978820    237.668391  321
                          B3                 103.978820           NaN  321
...                                                 ...           ...  ...
Western Africa            B4                 365.468522   8290.804998  529
                          B5                 365.468522   2637.924284  529
                          B6                 365.468522      0.000000  529
                          C1                 365.468522    471.611311  529
                          C2                 365.468522           NaN  529
                          C3                 365.468522   5680.738385  529
Western Asia              A1                  86.665592  12007.939411  258
                          A2                  86.665592   4051.910527  258
                          A3                  86.665592   1724.250880  258
                          B1                  86.665592      0.000000  258
                          B2                  86.665592   5095.695616  258
                          B3                  86.665592           NaN  258
                          B4                  86.665592      0.000000  258
                          B5                  86.665592           NaN  258
                          B6                  86.665592           NaN  258
                          C1                  86.665592           NaN  258
                          C2                  86.665592           NaN  258
                          C3                  86.665592   1367.021810  258
Western Europe            A1                  22.302142   7854.974633  142
                          A2                  22.302142   4562.799174  142
                          A3                  22.302142   6955.288162  142
                          B1                  22.302142  18581.043278  142
                          B2                  22.302142   1091.624667  142
                          B3                  22.302142    199.892207  142
                          B4                  22.302142   6914.605327  142
                          B5                  22.302142           NaN  142
                          B6                  22.302142      0.000000  142
                          C1                  22.302142  28415.470151  142
                          C2                  22.302142      0.000000  142
                          C3                  22.302142           NaN  142

                                      CLon       CLat  SIDS     TotPop    HDI  \
Subregion                 Type
Australia and New Zealand A1    305.340099 -68.575151     0   26909533  1.843
                          A2    305.340099 -68.575151     0   26909533  1.843
                          A3    305.340099 -68.575151     0   26909533  1.843
                          B1    305.340099 -68.575151     0   26909533  1.843
                          B2    305.340099 -68.575151     0   26909533  1.843
                          B3    305.340099 -68.575151     0   26909533  1.843
                          B4    305.340099 -68.575151     0   26909533  1.843
                          B5    305.340099 -68.575151     0   26909533  1.843
                          B6    305.340099 -68.575151     0   26909533  1.843
                          C1    305.340099 -68.575151     0   26909533  1.843
                          C2    305.340099 -68.575151     0   26909533  1.843
                          C3    305.340099 -68.575151     0   26909533  1.843
Caribbean                 A1   -156.155522  40.100795     2   13977301  1.530
                          A2   -156.155522  40.100795     2   13977301  1.530
                          A3   -156.155522  40.100795     2   13977301  1.530
                          B1   -156.155522  40.100795     2   13977301  1.530
                          B2   -156.155522  40.100795     2   13977301  1.530
                          B3   -156.155522  40.100795     2   13977301  1.530
                          B4   -156.155522  40.100795     2   13977301  1.530
                          B5   -156.155522  40.100795     2   13977301  1.530
                          B6   -156.155522  40.100795     2   13977301  1.530
                          C1   -156.155522  40.100795     2   13977301  1.530
                          C2   -156.155522  40.100795     2   13977301  1.530
                          C3   -156.155522  40.100795     2   13977301  1.530

In [90]:
mean_per_type = groupby_subregions_type.loc[:,['ReEst_Subsidy2009','SSF_USD_1000']]

In [91]:
mean_per_type

                                ReEst_Subsidy2009  SSF_USD_1000
Subregion                 Type
Australia and New Zealand A1        129241.779085  21426.276002
                          A2          9922.318280   1701.292472
                          A3         79448.594283  15054.748009
                          B1         89014.750270  15262.574761
                          B2             0.000000           NaN
                          B3             0.000000           NaN
                          B4             0.000000           NaN
                          B5             0.000000           NaN
                          B6             0.000000           NaN
                          C1         28262.262712  28262.262712
                          C2        168997.617791      0.000000
                          C3             0.000000           NaN
Caribbean                 A1         14204.563990  13239.783898
                          A2             0.000000           NaN
                          A3          9803.020892   9274.321445
                          B1          8654.268922   8654.268922
                          B2          1102.749167    907.279170
                          B3             0.000000           NaN
                          B4          2436.401207   2436.401207
                          B5             0.000000           NaN
                          B6             0.000000           NaN
                          C1             0.000000           NaN
                          C2             0.000000           NaN
                          C3           644.850741    644.850741
Central America           A1         41031.154338   6612.211493
                          A2         26098.801716  10784.801781
                          A3         19210.143120   6631.776769
                          B1             0.000000           NaN
                          B2          1674.262234    237.668391
                          B3             0.000000           NaN
...                                           ...           ...
Western Africa            B4         10818.881328   8290.804998
                          B5         13493.031350   2637.924284
                          B6          6681.592074      0.000000
                          C1           471.611311    471.611311
                          C2             0.000000           NaN
                          C3          5680.738385   5680.738385
Western Asia              A1         49329.749991  12007.939411
                          A2          7495.464883   4051.910527
                          A3          6020.948473   1724.250880
                          B1         16006.024961      0.000000
                          B2         33953.610232   5095.695616
                          B3             0.000000           NaN
                          B4         22024.582593      0.000000
                          B5             0.000000           NaN
                          B6             0.000000           NaN
                          C1             0.000000           NaN
                          C2             0.000000           NaN
                          C3          1367.021810   1367.021810
Western Europe            A1         37406.749168   7854.974633
                          A2         33151.656781   4562.799174
                          A3         22570.416613   6955.288162
                          B1        136543.967137  18581.043278
                          B2         11026.511790   1091.624667
                          B3           903.788941    199.892207
                          B4         35520.227633   6914.605327
                          B5             0.000000           NaN
                          B6         55180.060301      0.000000
                          C1        135891.508438  28415.470151
                          C2         47375.889951      0.000000
                          C3             0.000000           NaN

[240 rows x 2 columns]

In [92]:
Meansubsidies_subregion_type = (mean_per_type.SSF_USD_1000 / mean_per_type.ReEst_Subsidy2009)*100 
Meansubsidies_subregion_type

Subregion                  Type
Australia and New Zealand  A1       16.578444
                           A2       17.146119
                           A3       18.949043
                           B1       17.146119
                           B2             NaN
                           B3             NaN
                           B4             NaN
                           B5             NaN
                           B6             NaN
                           C1      100.000000
                           C2        0.000000
                           C3             NaN
Caribbean                  A1       93.207957
                           A2             NaN
                           A3       94.606770
                           B1      100.000000
                           B2       82.274301
                           B3             NaN
                           B4      100.000000
                           B5             NaN
                           B6             NaN
                           C1             NaN
                           C2             NaN
                           C3      100.000000
Central America            A1       16.115100
                           A2       41.322977
                           A3       34.522266
                           B1             NaN
                           B2       14.195410
                           B3             NaN
                                      ...
Western Africa             B4       76.632738
                           B5       19.550272
                           B6        0.000000
                           C1      100.000000
                           C2             NaN
                           C3      100.000000
Western Asia               A1       24.342186
                           A2       54.058162
                           A3       28.637529
                           B1        0.000000
                           B2       15.007817
                           B3             NaN
                           B4        0.000000
                           B5             NaN
                           B6             NaN
                           C1             NaN
                           C2             NaN
                           C3      100.000000
Western Europe             A1       20.998817
                           A2       13.763412
                           A3       30.815949
                           B1       13.608103
                           B2        9.900000
                           B3       22.117134
                           B4       19.466670
                           B5             NaN
                           B6        0.000000
                           C1       20.910409
                           C2        0.000000
                           C3             NaN
dtype: float64

In [93]:
groupby_subregions = merged_countries.groupby(['Subregion']).sum()
Meansubsidies_subregions = (groupby_subregions.SSF_USD_1000 / groupby_subregions.ReEst_Subsidy2009)*100

In [94]:
Meansubsidies_subregions

Subregion
Australia and New Zealand    16.183245
Caribbean                    95.416175
Central America              31.300110
Eastern Africa               47.192361
Eastern Asia                 22.014088
Eastern Europe                5.486709
Melanesia                     2.370248
Micronesia                    1.936005
Middle Africa                44.275252
Northern Africa              13.881914
Northern America             18.676442
Northern Europe               6.567230
South America                29.126989
Southeastern Asia            21.994490
Southern Africa               3.202589
Southern Asia                44.287819
Southern Europe               8.531187
Western Africa               45.349402
Western Asia                 17.802702
Western Europe               14.464687
dtype: float64

In [95]:
Catch = pd.read_csv("SAU_Catches.csv")

In [96]:
Catch

,Region,Developed,Countries,EEZ,Recreational,Subsistence,Artisanal,Industrial,Total_Catch,SSF_Catch,SSF_Catch_percent
0,Europe,Developing,Albania,True,0.0,0.00,0.40,4.50,4.9,0.4,8.163265
1,Europe,Developing,Albania,False,0.0,0.00,0.40,4.40,4.8,0.4,8.333333
2,Africa,Developing,Algeria,True,1.1,0.20,89.80,164.70,255.8,90.0,35.183737
3,Africa,Developing,Algeria,False,1.1,0.20,89.80,156.70,247.8,90.0,36.319613
4,Africa,Developing,Angola,True,0.1,63.70,156.10,273.20,493.1,219.8,44.575137
5,Africa,Developing,Angola,False,0.1,63.70,156.10,257.40,477.3,219.8,46.050702
6,South and Central America,Developing,Antigua Barb,True,0.1,0.40,2.20,0.90,3.6,2.6,72.222222
7,South and Central America,Developing,Antigua Barb,False,0.1,0.40,2.20,0.00,2.7,2.6,96.296296
8,South and Central America,Developing,Argentina,True,72.3,0.30,227.00,1062.70,1362.3,227.3,16.685018
9,South and Central America,Developing,Argentina,False,72.3,0.30,227.00,1011.00,1310.6,227.3,17.343202
10,Oceania,Developed,Australia,True,29.4,3.93,41.13,188.34,262.8,45.1,17.161339
11,Oceania,Developed,Australia,False,29.4,3.91,41.12,156.95,231.4,45.0,19.446845
12,South and Central America,Developing,Bahamas,True,5.5,0.60,2.10,8.50,16.7,2.7,16.167665
13,South and Central America,Developing,Bahamas,False,5.5,0.60,2.10,7.50,15.7,2.7,17.197452
14,Asia,Developed,Bahrain,True,0.7,0.00,46.00,0.50,47.2,46.0,97.457627
15,Asia,Developed,Bahrain,False,0.7,0.00,46.00,7.30,54.0,46.0,85.185185
16,Asia,Developing,Bangladesh,True,0.0,240.90,664.20,150.20,1055.3,905.1,85.767080
17,Asia,Developing,Bangladesh,False,0.0,240.90,664.20,115.30,1020.4,905.1,88.700510
18,South and Central America,Developing,Barbados,True,0.0,0.80,2.30,3.00,6.1,3.1,50.819672
19,South and Central America,Developing,Barbados,False,0.0,0.80,2.30,3.00,6.1,3.1,50.819672
20,Europe,Developed,Belgium,True,0.1,0.00,0.00,6.20,6.3,0.0,0.000000
21,Europe,Developed,Belgium,False,0.1,0.00,0.00,33.70,33.8,0.0,0.000000
22,South and Central America,Developing,Belize,True,0.0,1.40,4.80,0.10,6.3,6.2,98.412698
23,South and Central America,Developing,Belize,False,0.0,1.40,4.80,223.50,229.7,6.2,2.699173
24,Africa,Developing,Benin,True,0.0,19.10,46.40,7.00,72.5,65.5,90.344828
25,Africa,Developing,Benin,False,0.0,19.10,46.40,1.00,66.5,65.5,98.496241
26,Europe,Developing,Bosnia Herzg,True,0.0,0.10,0.00,0.00,0.1,0.1,100.000000
27,Europe,Developing,Bosnia Herzg,False,0.0,0.10,0.00,0.00,0.1,0.1,100.000000
28,South and Central America,Developing,Brazil,True,1.4,4.90,443.30,462.80,912.4,448.2,49.123192
29,South and Central America,Developing,Brazil,False,1.4,4.90,443.30,483.00,932.6,448.2,48.059189
...,...,...,...,...,...,...,...,...,...,...,...
274,Africa,Developing,Togo,True,0.0,1.10,19.40,42.70,63.2,20.5,32.436709
275,Africa,Developing,Togo,False,0.0,1.10,19.40,3.50,24.0,20.5,85.416667
276,Oceania,Developing,Tonga,True,0.0,2.60,1.70,1.20,5.5,4.3,78.181818
277,Oceania,Developing,Tonga,False,0.0,2.60,1.70,0.30,4.6,4.3,93.478261
278,South and Central America,Developing,Trinidad Tob,True,1.0,4.00,8.90,8.30,22.2,12.9,58.108108
279,South and Central America,Developing,Trinidad Tob,False,1.0,4.00,8.90,8.10,22.0,12.9,58.636364
280,Africa,Developing,Tunisia,True,0.1,0.00,24.90,70.00,95.0,24.9,26.210526
281,Africa,Developing,Tunisia,False,0.1,0.00,24.90,69.20,94.2,24.9,26.433121
282,Asia,Developing,Turkey,True,55.2,7.30,110.00,552.10,724.6,117.3,16.188242
283,Asia,Developing,Turkey,False,55.2,7.30,110.00,610.70,783.2,117.3,14.977017
284,Oceania,Developing,Tuvalu,True,1.2,0.00,0.50,46.30,48.0,0.5,1.041667
285,Oceania,Developing,Tuvalu,False,1.2,0.00,0.50,0.30,2.0,0.5,25.000000
286,Europe,Developed,UK,True,3.9,3.70,55.70,1585.10,1648.5,59.4,3.603276
287,Europe,Developed,UK,False,3.9,3.70,55.70,674.00,737.4,59.4,8.055330
288,Europe,Developing,Ukraine,True,15.8,7.00,3.90,79.20,105.9,10.9,10.292729
289,Europe,Developing,Ukraine,False,15.8,7.00,3.90,333.20,359.9,10.9,3.028619
290,Asia,Developed,Untd Arab Em,True,0.8,0.10,66.90,4.20,72.0,67.0,93.055556
291,Asia,Developed,Untd Arab Em,False,0.9,0.10,66.90,13.20,81.1,67.0,82.614057
292,South and Central America,Developing,Uruguay,True,0.2,3.20,29.00,87.50,119.9,32.2,26.855713
293,South and Central America,Developing,Uruguay,False,0.2,3.20,29.00,88.50,120.9,32.2,26.633581
294,North America,Developed,USA,True,126.9,6.60,1397.00,3722.70,5253.1,1403.6,26.719461
295,North America,Developed,USA,False,127.0,6.60,1397.00,5677.00,7207.6,1403.6,19.473889
296,Oceania,Developing,Vanuatu,True,0.1,2.90,0.70,13.20,16.9,3.6,21.301775
297,Oceania,Developing,Vanuatu,False,0.1,2.90,0.70,48.90,52.6,3.6,6.844106
298,South and Central America,Developing,Venezuela,True,0.0,7.30,266.20,16.50,290.0,273.5,94.310345
299,South and Central America,Developing,Venezuela,False,0.0,7.30,266.20,87.80,361.3,273.5,75.698865
300,Asia,Developing,Viet Nam,True,0.0,441.00,633.60,2301.50,3376.1,1074.6,31.829626
301,Asia,Developing,Viet Nam,False,0.0,441.00,633.60,1821.20,2895.8,1074.6,37.108916
302,Asia,Developing,Yemen,True,0.0,25.80,227.40,22.80,276.0,253.2,91.739130
303,Asia,Developing,Yemen,False,0.0,25.80,227.40,69.40,322.6,253.2,78.487291

In [97]:
Catch_Subregions = pd.merge(left=Catch,right=countrydata, how='left')
Catch_Subregions

,Region,Developed,Countries,EEZ,Recreational,Subsistence,Artisanal,Industrial,Total_Catch,SSF_Catch,SSF_Catch_percent,CID,Subregion,CLon,CLat,SIDS,TotPop,HDI,Develop,GDP
0,Europe,Developing,Albania,True,0.0,0.00,0.40,4.50,4.9,0.4,8.163265,1,Southern Europe,20.050049,40.934006,0,3020209,0.749,High,3.066000e+10
1,Europe,Developing,Albania,False,0.0,0.00,0.40,4.40,4.8,0.4,8.333333,1,Southern Europe,20.050049,40.934006,0,3020209,0.749,High,3.066000e+10
2,Africa,Developing,Algeria,True,1.1,0.20,89.80,164.70,255.8,90.0,35.183737,2,Northern Africa,2.296145,27.940730,0,38813722,0.717,Medium,5.626000e+11
3,Africa,Developing,Algeria,False,1.1,0.20,89.80,156.70,247.8,90.0,36.319613,2,Northern Africa,2.296145,27.940730,0,38813722,0.717,Medium,5.626000e+11
4,Africa,Developing,Angola,True,0.1,63.70,156.10,273.20,493.1,219.8,44.575137,3,Middle Africa,17.237553,-13.299091,0,19088106,0.526,Low,1.755000e+11
5,Africa,Developing,Angola,False,0.1,63.70,156.10,257.40,477.3,219.8,46.050702,3,Middle Africa,17.237553,-13.299091,0,19088106,0.526,Low,1.755000e+11
6,South and Central America,Developing,Antigua Barb,True,0.1,0.40,2.20,0.90,3.6,2.6,72.222222,4,Caribbean,-61.800000,17.050000,1,91295,0.774,High,1.989000e+09
7,South and Central America,Developing,Antigua Barb,False,0.1,0.40,2.20,0.00,2.7,2.6,96.296296,4,Caribbean,-61.800000,17.050000,1,91295,0.774,High,1.989000e+09
8,South and Central America,Developing,Argentina,True,72.3,0.30,227.00,1062.70,1362.3,227.3,16.685018,5,South America,-64.379883,-33.707205,0,43024374,0.808,High,9.274000e+11
9,South and Central America,Developing,Argentina,False,72.3,0.30,227.00,1011.00,1310.6,227.3,17.343202,5,South America,-64.379883,-33.707205,0,43024374,0.808,High,9.274000e+11
10,Oceania,Developed,Australia,True,29.4,3.93,41.13,188.34,262.8,45.1,17.161339,6,Australia and New Zealand,133.769531,-25.105497,0,22507617,0.933,High,1.100000e+12
11,Oceania,Developed,Australia,False,29.4,3.91,41.12,156.95,231.4,45.0,19.446845,6,Australia and New Zealand,133.769531,-25.105497,0,22507617,0.933,High,1.100000e+12
12,South and Central America,Developing,Bahamas,True,5.5,0.60,2.10,8.50,16.7,2.7,16.167665,7,Caribbean,-77.934265,24.533303,1,321834,0.789,High,9.034000e+09
13,South and Central America,Developing,Bahamas,False,5.5,0.60,2.10,7.50,15.7,2.7,17.197452,7,Caribbean,-77.934265,24.533303,1,321834,0.789,High,9.034000e+09
14,Asia,Developed,Bahrain,True,0.7,0.00,46.00,0.50,47.2,46.0,97.457627,8,Western Asia,50.550000,26.000000,1,1314089,0.815,High,6.156000e+10
15,Asia,Developed,Bahrain,False,0.7,0.00,46.00,7.30,54.0,46.0,85.185185,8,Western Asia,50.550000,26.000000,1,1314089,0.815,High,6.156000e+10
16,Asia,Developing,Bangladesh,True,0.0,240.90,664.20,150.20,1055.3,905.1,85.767080,9,Southern Asia,90.186768,24.444024,0,166280712,0.558,Medium,5.366000e+11
17,Asia,Developing,Bangladesh,False,0.0,240.90,664.20,115.30,1020.4,905.1,88.700510,9,Southern Asia,90.186768,24.444024,0,166280712,0.558,Medium,5.366000e+11
18,South and Central America,Developing,Barbados,True,0.0,0.80,2.30,3.00,6.1,3.1,50.819672,10,Caribbean,-59.550018,13.151284,1,289680,0.776,High,4.513000e+09
19,South and Central America,Developing,Barbados,False,0.0,0.80,2.30,3.00,6.1,3.1,50.819672,10,Caribbean,-59.550018,13.151284,1,289680,0.776,High,4.513000e+09
20,Europe,Developed,Belgium,True,0.1,0.00,0.00,6.20,6.3,0.0,0.000000,11,Western Europe,4.383545,50.692543,0,10449361,0.881,High,4.671000e+11
21,Europe,Developed,Belgium,False,0.1,0.00,0.00,33.70,33.8,0.0,0.000000,11,Western Europe,4.383545,50.692543,0,10449361,0.881,High,4.671000e+11
22,South and Central America,Developing,Belize,True,0.0,1.40,4.80,0.10,6.3,6.2,98.412698,12,Central America,-88.846436,17.261154,1,340844,0.732,Medium,2.907000e+09
23,South and Central America,Developing,Belize,False,0.0,1.40,4.80,223.50,229.7,6.2,2.699173,12,Central America,-88.846436,17.261154,1,340844,0.732,Medium,2.907000e+09
24,Africa,Developing,Benin,True,0.0,19.10,46.40,7.00,72.5,65.5,90.344828,13,Western Africa,2.438965,9.702289,0,10160556,0.476,Low,1.985000e+10
25,Africa,Developing,Benin,False,0.0,19.10,46.40,1.00,66.5,65.5,98.496241,13,Western Africa,2.438965,9.702289,0,10160556,0.476,Low,1.985000e+10
26,Europe,Developing,Bosnia Herzg,True,0.0,0.10,0.00,0.00,0.1,0.1,100.000000,14,Southern Europe,18.416667,43.866667,NaN,3871643,0.731,High,3.808000e+10
27,Europe,Developing,Bosnia Herzg,False,0.0,0.10,0.00,0.00,0.1,0.1,100.000000,14,Southern Europe,18.416667,43.866667,NaN,3871643,0.731,High,3.808000e+10
28,South and Central America,Developing,Brazil,True,1.4,4.90,443.30,462.80,912.4,448.2,49.123192,15,South America,-51.815643,-12.986242,0,202656788,0.744,High,3.073000e+12
29,South and Central America,Developing,Brazil,False,1.4,4.90,443.30,483.00,932.6,448.2,48.059189,15,South America,-51.815643,-12.986242,0,202656788,0.744,High,3.073000e+12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
274,Africa,Developing,Togo,True,0.0,1.10,19.40,42.70,63.2,20.5,32.436709,138,Western Africa,1.068420,8.400375,0,7351374,0.473,Medium,1.018000e+10
275,Africa,Developing,Togo,False,0.0,1.10,19.40,3.50,24.0,20.5,85.416667,138,Western Africa,1.068420,8.400375,0,7351374,0.473,Medium,1.018000e+10
276,Oceania,Developing,Tonga,True,0.0,2.60,1.70,1.20,5.5,4.3,78.181818,139,Polynesia,-175.198242,-21.178986,1,106440,0.705,High,5.230000e+08
277,Oceania,Developing,Tonga,False,0.0,2.60,1.70,0.30,4.6,4.3,93.478261,139,Polynesia,-175.198242,-21.178986,1,106440,0.705,High,5.230000e+08
278,South and Central America,Developing,Trinidad Tob,True,1.0,4.00,8.90,8.30,22.2,12.9,58.108108,140,Caribbean,-61.272337,10.442975,1,1223916,0.766,High,4.223000e+10
279,South and Central America,Developing,Trinidad Tob,False,1.0,4.00,8.90,8.10,22.0,12.9,58.636364,140,Caribbean,-61.272337,10.442975,1,1223916,0.766,High,4.223000e+10
280,Africa,Developing,Tunisia,True,0.1,0.00,24.90,70.00,95.0,24.9,26.210526,141,Northern Africa,9.593815,34.010550,0,10937521,0.721,Medium,1.251000e+11
281,Africa,Developing,Tunisia,False,0.1,0.00,24.90,69.20,94.2,24.9,26.433121,141,Northern Africa,9.593815,34.010550,0,10937521,0.721,Medium,1.251000e+11
282,Asia,Developing,Turkey,True,55.2,7.30,110.00,552.10,724.6,117.3,16.188242,142,Western Asia,34.628908,39.527348,0,81619392,0.759,Medium,1.512000e+12
283,Asia,Developing,Turkey,False,55.2,7.30,110.00,610.70,783.2,117.3,14.977017,142,Western Asia,34.628908,39.527348,0,81619392,0.759,Medium,1.512000e+12
284,Oceania,Developing,Tuvalu,True,1.2,0.00,0.50,46.30,48.0,0.5,1.041667,143,Polynesia,178.679921,-7.478442,1,10782,NaN,NaN,3.500000e+07
285,Oceania,Developing,Tuvalu,False,1.2,0.00,0.50,0.30,2.0,0.5,25.000000,143,Polynesia,178.679921,-7.478442,1,10782,NaN,NaN,3.500000e+07
286,Europe,Developed,UK,True,3.9,3.70,55.70,1585.10,1648.5,59.4,3.603276,144,Northern Europe,-1.538080,53.032955,0,63742977,0.892,Medium,2.435000e+12
287,Europe,Developed,UK,False,3.9,3.70,55.70,674.00,737.4,59.4,8.055330,144,Northern Europe,-1.538080,53.032955,0,63742977,0.892,Medium,2.435000e+12
288,Europe,Developing,Ukraine,True,15.8,7.00,3.90,79.20,105.9,10.9,10.292729,145,Eastern Europe,33.178719,48.942347,0,44291413,0.734,High,3.731000e+11
289,Europe,Developing,Ukraine,False,15.8,7.00,3.90,333.20,359.9,10.9,3.028619,145,Eastern Europe,33.178719,48.942347,0,44291413,0.734,High,3.731000e+11
290,Asia,Developed,Untd Arab Em,True,0.8,0.10,66.90,4.20,72.0,67.0,93.055556,146,Western Asia,54.448252,23.913460,0,5628805,0.827,High,6.050000e+08
291,Asia,Developed,Untd Arab Em,False,0.9,0.10,66.90,13.20,81.1,67.0,82.614057,146,Western Asia,54.448252,23.913460,0,5628805,0.827,High,6.050000e+08
292,South and Central America,Developing,Uruguay,True,0.2,3.20,29.00,87.50,119.9,32.2,26.855713,147,South America,-56.206051,-32.888813,0,3332972,0.790,High,6.978000e+10
293,South and Central America,Developing,Uruguay,False,0.2,3.20,29.00,88.50,120.9,32.2,26.633581,147,South America,-56.206051,-32.888813,0,3332972,0.790,High,6.978000e+10
294,North America,Developed,USA,True,126.9,6.60,1397.00,3722.70,5253.1,1403.6,26.719461,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
295,North America,Developed,USA,False,127.0,6.60,1397.00,5677.00,7207.6,1403.6,19.473889,148,Northern America,-104.690304,40.278267,0,318892103,0.914,High,1.746000e+13
296,Oceania,Developing,Vanuatu,True,0.1,2.90,0.70,13.20,16.9,3.6,21.301775,149,Melanesia,166.959158,-15.376706,1,266937,0.616,Medium,6.870000e+08
297,Oceania,Developing,Vanuatu,False,0.1,2.90,0.70,48.90,52.6,3.6,6.844106,149,Melanesia,166.959158,-15.376706,1,266937,0.616,Medium,6.870000e+08
298,South and Central America,Developing,Venezuela,True,0.0,7.30,266.20,16.50,290.0,273.5,94.310345,150,South America,-66.369987,7.927041,0,28868486,0.764,Medium,5.457000e+08
299,South and Central America,Developing,Venezuela,False,0.0,7.30,266.20,87.80,361.3,273.5,75.698865,150,South America,-66.369987,7.927041,0,28868486,0.764,Medium,5.457000e+08
300,Asia,Developing,Viet Nam,True,0.0,441.00,633.60,2301.50,3376.1,1074.6,31.829626,151,Southeastern Asia,108.277199,14.058324,0,93421835,0.638,Medium,5.095000e+11
301,Asia,Developing,Viet Nam,False,0.0,441.00,633.60,1821.20,2895.8,1074.6,37.108916,151,Southeastern Asia,108.277199,14.058324,0,93421835,0.638,Medium,5.095000e+11
302,Asia,Developing,Yemen,True,0.0,25.80,227.40,22.80,276.0,253.2,91.739130,152,Western Asia,47.373059,15.990375,0,26052966,0.500,Medium,1.060000e+11
303,Asia,Developing,Yemen,False,0.0,25.80,227.40,69.40,322.6,253.2,78.487291,152,Western Asia,47.373059,15.990375,0,26052966,0.500,Medium,1.060000e+11

In [140]:
Catch_groupby_subregions = Catch_Subregions.groupby(['Subregion','EEZ']).sum()
Catch_groupby_subregions

                                 Recreational  Subsistence  Artisanal  \
Subregion                 EEZ
Australia and New Zealand False          40.6         5.01     135.92
                          True           40.6         5.03     135.93
Caribbean                 False           9.1        68.70     104.40
                          True            9.1        68.70     104.40
Central America           False           5.4        40.90     939.90
                          True            5.4        41.00     938.50
Eastern Africa            False           2.8       146.90     277.80
                          True            2.8       145.90     273.70
Eastern Asia              False         155.2        63.65    5274.30
                          True          155.2        63.65    5274.30
Eastern Europe            False          42.1        33.20    1092.10
                          True           41.2        33.30    1092.20
Melanesia                 False           1.1        51.30      18.10
                          True            1.1        51.30      18.10
Micronesia                False           0.0        28.50      12.50
                          True            0.0        14.40       4.90
Middle Africa             False           0.1        82.80     300.00
                          True            0.1        82.50     298.50
Northern Africa           False          34.6        32.80     353.00
                          True           34.6        32.90     352.90
Northern America          False         155.9        22.50    1448.20
                          True           29.0        15.90      51.14
Northern Europe           False          30.5        13.20     243.20
                          True           37.8        52.20     437.80
Polynesia                 False           1.2        12.70       6.80
                          True            1.2        12.70       6.80
South America             False          73.9        44.03    3015.70
                          True           73.9        43.93    3015.70
Southeastern Asia         False          33.4      1154.90    4018.90
                          True           33.6      1155.00    4018.80
Southern Africa           False           7.2         3.90      43.00
                          True            7.2         3.90      43.00
Southern Asia             False           0.3      1483.60    2347.60
                          True            0.3      1483.60    2331.80
Southern Europe           False         124.3        19.40     300.60
                          True          124.3        19.30     300.70
Western Africa            False           3.3       140.90    1748.30
                          True            3.3       140.80    1739.70
Western Asia              False          65.0        43.85     578.80
                          True           65.1        97.05     713.10
Western Europe            False           4.7         0.20       3.10
                          True            1.3         3.80       4.60

                                 Industrial  Total_Catch  SSF_Catch  \
Subregion                 EEZ
Australia and New Zealand False      481.15        662.7      140.9
                          True       769.34        950.9      141.0
Caribbean                 False       54.10        236.3      173.1
                          True        28.10        210.3      173.1
Central America           False     1679.10       2665.3      980.8
                          True      1327.80       2312.7      979.5
Eastern Africa            False      155.30        582.8      424.7
                          True       239.20        661.6      419.6
Eastern Asia              False    18128.00      23621.2     5338.0
                          True     12722.60      18215.8     5338.0
Eastern Europe            False     6565.50       7732.9     1125.3
                          True      6299.90       7466.6     1125.5
Melanesia                 False      271.10        341.6       69.4
                          True       403.90        474.4       69.4
Micronesia                False      408.70        449.7       41.0
                          True       439.60        458.9       19.3
Middle Africa             False      305.80        688.7      382.8
                          True       500.80        881.9      381.0
Northern Africa           False     1845.10       2265.5      385.8
                          True      3106.90       3527.3      385.8
Northern America          False     6675.40       8302.0     1470.7
                          True      1583.60       1679.6       67.0
Northern Europe           False     4656.50       4943.5      256.4
                          True      6890.10       7418.0      490.0
Polynesia                 False        3.70         24.4       19.5
                          True        49.10         69.8       19.5
South America             False    13433.90      16567.5     3059.7
                          True     13115.80      16249.3     3059.6
Southeastern Asia         False    14986.60      20193.8     5173.8
                          True     14972.00      20179.4     5173.8
Southern Africa           False      925.90        980.0       46.9
                          True       945.00        999.1       46.9
Southern Asia             False     3541.70       7373.2     3831.2
                          True      3621.80       7437.5     3815.4
Southern Europe           False     2392.10       2836.4      320.0
                          True      1036.90       1481.2      320.0
Western Africa            False     1235.30       3127.8     1889.2
                          True      5670.10       7553.9     1880.5
Western Asia              False     1129.50       1817.2      622.7
                          True       857.80       1733.1      810.2
Western Europe            False      594.60        602.6        3.3
                          True       321.50        331.1        8.3

                                 SSF_Catch_percent   CID         CLon  \
Subregion                 EEZ
Australia and New Zealand False          41.681948   104   305.340099
                          True           31.098267   104   305.340099
Caribbean                 False         858.489485   827  -867.636998
                          True          950.608313   827  -867.636998
Central America           False         281.626831   380  -625.384348
                          True          406.491673   380  -625.384348
Eastern Africa            False         718.661555   811   441.441712
                          True          586.992071   811   441.441712
Eastern Asia              False         153.398903   436   731.729800
                          True          208.010486   436   731.729800
Eastern Europe            False          27.216638   496   195.112388
                          True          132.195198   496   195.112388
Melanesia                 False          86.939277   298   489.044653
                          True           88.456702   298   489.044653
Micronesia                False         251.903459   449   473.544124
                          True           25.359480   449   473.544124
Middle Africa             False         518.933602   276    96.159551
                          True          309.542090   276    96.159551
Northern Africa           False         200.279341   483    82.331402
                          True          223.364735   483    82.331402
Northern America          False          25.605102   168  -211.114865
                          True            3.989045    20  -106.424561
Northern Europe           False          45.145068   680    97.705721
                          True           61.423000   781   106.738543
Polynesia                 False         201.062531   396  -168.851654
                          True          169.407534   396  -168.851654
South America             False         360.742845   695  -650.725904
                          True          369.087425   695  -650.725904
Southeastern Asia         False         403.256001   926  1091.429437
                          True          388.278123   926  1091.429437
Southern Africa           False           8.156781   219    39.542541
                          True            8.166942   219    39.542541
Southern Asia             False         336.349397   448   446.892895
                          True          318.639907   448   446.892895
Southern Europe           False         252.449267   697   124.794579
                          True          299.204636   697   124.794579
Western Africa            False         950.746231   912  -105.783574
                          True          525.441643   912  -105.783574
Western Asia              False         861.336030  1294   631.658031
                          True         1026.524164  1396   687.934124
Western Europe            False           1.334378   158    19.964219
                          True            7.745482   158    19.964219

                                       CLat  SIDS      TotPop     HDI  \
Subregion                 EEZ
Australia and New Zealand False  -68.575151     0    26909533   1.843
                          True   -68.575151     0    26909533   1.843
Caribbean                 False  215.454896    13    36751917   9.450
                          True   215.454896    13    36751917   9.450
Central America           False  105.242434     1   160602530   4.772
                          True   105.242434     1   160602530   4.772
Eastern Africa            False  -44.482833     3   162351959   4.777
                          True   -44.482833     3   162351959   4.777
Eastern Asia              False  194.820779     0  1586360797   4.754
                          True   194.820779     0  1586360797   4.754
Eastern Europe            False  251.484460     0   253762551   3.908
                          True   251.484460     0   253762551   3.908
Melanesia                 False  -39.381019     3     7722874   1.831
                          True   -39.381019     3     7722874   1.831
Micronesia                False   22.825763     5      299734   3.422
                          True    22.825763     5      299734   3.422
Middle Africa             False  -11.804490     1   126900283   3.720
                          True   -11.804490     1   126900283   3.720
Northern Africa           False  162.412417     0   211359955   3.994
                          True   162.412417     0   211359955   3.994
Northern America          False   96.810306     0   353726944   1.816
                          True    56.532039     0    34834841   0.902
Northern Europe           False  522.497171     0    96383602   7.847
                          True   583.055695     0   101531394   8.791
Polynesia                 False  -42.240761     3      313850   1.399
                          True   -42.240761     3      313850   1.399
South America             False  -97.952648     2   388603022   7.430
                          True   -97.952648     2   388603022   7.430
Southeastern Asia         False   78.878172     1   589146119   7.113
                          True    78.878172     1   589146119   7.113
Southern Africa           False  -53.347082     0    50574051   1.282
                          True   -53.347082     0    50574051   1.282
Southern Asia             False  116.352822     1  1701900476   3.878
                          True   116.352822     1  1701900476   3.878
Southern Europe           False  417.179712     0   145366560   8.200
                          True   417.179712     0   145366560   8.200
Western Africa            False  142.136266     2   285895348   6.101
                          True   142.136266     2   285895348   6.101
Western Asia              False  456.708864     1   224358989  10.047
                          True   477.221756     1   227578764  10.830
Western Europe            False  153.437182     0   108323397   2.707
                          True   153.437182     0   108323397   2.707

                                          GDP
Subregion                 EEZ
Australia and New Zealand False  1.258700e+12
                          True   1.258700e+12
Caribbean                 False  3.699738e+11
                          True   3.699738e+11
Central America           False  2.455517e+12
                          True   2.455517e+12
Eastern Africa            False  3.341740e+11
                          True   3.341740e+11
Eastern Asia              False  2.566100e+13
                          True   2.566100e+13
Eastern Europe            False  5.392300e+12
                          True   5.392300e+12
Melanesia                 False  2.608900e+10
                          True   2.608900e+10
Micronesia                False  1.026101e+09
                          True   1.026101e+09
Middle Africa             False  3.867720e+11
                          True   3.867720e+11
Northern Africa           False  2.150300e+12
                          True   2.150300e+12
Northern America          False  1.903900e+13
                          True   1.579000e+12
Northern Europe           False  3.350070e+12
                          True   3.689570e+12
Polynesia                 False  1.553000e+09
                          True   1.553000e+09
South America             False  5.358134e+12
                          True   5.358134e+12
Southeastern Asia         False  3.934754e+12
                          True   3.934754e+12
Southern Africa           False  7.066900e+11
                          True   7.066900e+11
Southern Asia             False  1.020315e+13
                          True   1.020315e+13
Southern Europe           False  4.338541e+12
                          True   4.338541e+12
Western Africa            False  1.357041e+12
                          True   1.357041e+12
Western Asia              False  4.160585e+12
                          True   4.324185e+12
Western Europe            False  4.886200e+12
                          True   4.886200e+12

In [121]:
for col in Catch_groupby_subregions:
    print col, Catch_groupby_subregions[col].dtypes

Recreational float64
Subsistence float64
Artisanal float64
Industrial float64
Total_Catch float64
SSF_Catch float64
SSF_Catch_percent float64
CID float64
CLon float64
CLat float64
SIDS float64
TotPop float64
HDI float64
GDP float64

In [141]:
Meancatch_subregions = (Catch_groupby_subregions.SSF_Catch / Catch_groupby_subregions.Total_Catch)*100
Meancatch_subregions

Subregion                  EEZ
Australia and New Zealand  False    21.261506
                           True     14.828058
Caribbean                  False    73.254338
                           True     82.310984
Central America            False    36.798859
                           True     42.353094
Eastern Africa             False    72.872340
                           True     63.422007
Eastern Asia               False    22.598344
                           True     29.304230
Eastern Europe             False    14.552109
                           True     15.073795
Melanesia                  False    20.316159
                           True     14.629005
Micronesia                 False     9.117189
                           True      4.205709
Middle Africa              False    55.582982
                           True     43.202177
Northern Africa            False    17.029353
                           True     10.937544
Northern America           False    17.715008
                           True      3.989045
Northern Europe            False     5.186609
                           True      6.605554
Polynesia                  False    79.918033
                           True     27.936963
South America              False    18.468085
                           True     18.829119
Southeastern Asia          False    25.620735
                           True     25.639018
Southern Africa            False     4.785714
                           True      4.694225
Southern Asia              False    51.961157
                           True     51.299496
Southern Europe            False    11.281907
                           True     21.604105
Western Africa             False    60.400281
                           True     24.894425
Western Asia               False    34.267004
                           True     46.748601
Western Europe             False     0.547627
                           True      2.506796
dtype: float64

In [123]:
Type = pd.read_csv('Subtype_Fleet_EEZ.csv')

In [124]:
Type

                      SubType Type    EEZ
0            Fisheries mangt.   A1   True
1                 Fishery R&D   A2   True
2                        MPAs   A3   True
3   Boat constsruct. & renov.   B1  False
4     Fisheries dev. projects   B2  False
5       Fishing port develop.   B3  False
6   Markt. & storage infrast.   B4  False
7               Tax exemption   B5  False
8              Fishing access   B6  False
9              Fuel subsidies   B7  False
10          Fisher assistance   C1  False
11             Vessel buyback   C2  False
12   Rural fisher communities   C3  False

In [125]:
Subsidies2009 = pd.read_csv("subsidies2009_nofuel.csv")

In [126]:
Subsidies2009_subregions = pd.merge(left=Subsidies2009,right=countrydata, how='left')

In [127]:
Subsidies2009_subregions

,ID,Cnumber,RegionID,RegionName,Countries,Type,SubType,Category,ReEst_Subsidy2009,NewData,...,HDI_2005,CID,Subregion,CLon,CLat,SIDS,TotPop,HDI,Develop,GDP
0,1,8,1,Europe,Albania,A1,Fisheries mangt.,Good,387.260735,0,...,0.801,1,Southern Europe,20.050049,40.934006,0,3020209,0.749,High,3.066000e+10
1,2,8,1,Europe,Albania,A2,Fishery R&D,Good,198.557500,0,...,0.801,1,Southern Europe,20.050049,40.934006,0,3020209,0.749,High,3.066000e+10
2,3,8,1,Europe,Albania,A3,MPAs,Good,58.941816,0,...,0.801,1,Southern Europe,20.050049,40.934006,0,3020209,0.749,High,3.066000e+10
3,4,8,1,Europe,Albania,B1,Boat constsruct. & renov.,Bad,0.000000,0,...,0.801,1,Southern Europe,20.050049,40.934006,0,3020209,0.749,High,3.066000e+10
4,5,8,1,Europe,Albania,B2,Fisheries dev. projects,Bad,472.011572,0,...,0.801,1,Southern Europe,20.050049,40.934006,0,3020209,0.749,High,3.066000e+10
5,6,8,1,Europe,Albania,B3,Fishing port develop.,Bad,107.025943,0,...,0.801,1,Southern Europe,20.050049,40.934006,0,3020209,0.749,High,3.066000e+10
6,7,8,1,Europe,Albania,B4,Markt. & storage infrast.,Bad,152.502950,0,...,0.801,1,Southern Europe,20.050049,40.934006,0,3020209,0.749,High,3.066000e+10
7,8,8,1,Europe,Albania,B5,Tax exemption,Bad,0.000000,0,...,0.801,1,Southern Europe,20.050049,40.934006,0,3020209,0.749,High,3.066000e+10
8,9,8,1,Europe,Albania,B6,Fishing access,Bad,0.000000,0,...,0.801,1,Southern Europe,20.050049,40.934006,0,3020209,0.749,High,3.066000e+10
9,11,8,1,Europe,Albania,C1,Fisher assistance,Ugly,0.000000,0,...,0.801,1,Southern Europe,20.050049,40.934006,0,3020209,0.749,High,3.066000e+10
10,12,8,1,Europe,Albania,C2,Vessel buyback,Ugly,0.000000,0,...,0.801,1,Southern Europe,20.050049,40.934006,0,3020209,0.749,High,3.066000e+10
11,13,8,1,Europe,Albania,C3,Rural fisher communities,Ugly,0.000000,0,...,0.801,1,Southern Europe,20.050049,40.934006,0,3020209,0.749,High,3.066000e+10
12,14,12,3,Africa,Algeria,A1,Fisheries mangt.,Good,72.985872,0,...,0.733,2,Northern Africa,2.296145,27.940730,0,38813722,0.717,Medium,5.626000e+11
13,15,12,3,Africa,Algeria,A2,Fishery R&D,Good,1925.441376,0,...,0.733,2,Northern Africa,2.296145,27.940730,0,38813722,0.717,Medium,5.626000e+11
14,16,12,3,Africa,Algeria,A3,MPAs,Good,753.613072,0,...,0.733,2,Northern Africa,2.296145,27.940730,0,38813722,0.717,Medium,5.626000e+11
15,17,12,3,Africa,Algeria,B1,Boat constsruct. & renov.,Bad,0.000000,0,...,0.733,2,Northern Africa,2.296145,27.940730,0,38813722,0.717,Medium,5.626000e+11
16,18,12,3,Africa,Algeria,B2,Fisheries dev. projects,Bad,598.465491,1,...,0.733,2,Northern Africa,2.296145,27.940730,0,38813722,0.717,Medium,5.626000e+11
17,19,12,3,Africa,Algeria,B3,Fishing port develop.,Bad,863.183032,0,...,0.733,2,Northern Africa,2.296145,27.940730,0,38813722,0.717,Medium,5.626000e+11
18,20,12,3,Africa,Algeria,B4,Markt. & storage infrast.,Bad,1478.844056,0,...,0.733,2,Northern Africa,2.296145,27.940730,0,38813722,0.717,Medium,5.626000e+11
19,21,12,3,Africa,Algeria,B5,Tax exemption,Bad,0.000000,0,...,0.733,2,Northern Africa,2.296145,27.940730,0,38813722,0.717,Medium,5.626000e+11
20,22,12,3,Africa,Algeria,B6,Fishing access,Bad,0.000000,0,...,0.733,2,Northern Africa,2.296145,27.940730,0,38813722,0.717,Medium,5.626000e+11
21,24,12,3,Africa,Algeria,C1,Fisher assistance,Ugly,0.000000,0,...,0.733,2,Northern Africa,2.296145,27.940730,0,38813722,0.717,Medium,5.626000e+11
22,25,12,3,Africa,Algeria,C2,Vessel buyback,Ugly,0.000000,0,...,0.733,2,Northern Africa,2.296145,27.940730,0,38813722,0.717,Medium,5.626000e+11
23,26,12,3,Africa,Algeria,C3,Rural fisher communities,Ugly,391.410826,0,...,0.733,2,Northern Africa,2.296145,27.940730,0,38813722,0.717,Medium,5.626000e+11
24,27,24,3,Africa,Angola,A1,Fisheries mangt.,Good,18410.390367,0,...,0.446,3,Middle Africa,17.237553,-13.299091,0,19088106,0.526,Low,1.755000e+11
25,28,24,3,Africa,Angola,A2,Fishery R&D,Good,825.875616,1,...,0.446,3,Middle Africa,17.237553,-13.299091,0,19088106,0.526,Low,1.755000e+11
26,29,24,3,Africa,Angola,A3,MPAs,Good,1037.353000,0,...,0.446,3,Middle Africa,17.237553,-13.299091,0,19088106,0.526,Low,1.755000e+11
27,30,24,3,Africa,Angola,B1,Boat constsruct. & renov.,Bad,44923.938932,0,...,0.446,3,Middle Africa,17.237553,-13.299091,0,19088106,0.526,Low,1.755000e+11
28,31,24,3,Africa,Angola,B2,Fisheries dev. projects,Bad,38847.837016,1,...,0.446,3,Middle Africa,17.237553,-13.299091,0,19088106,0.526,Low,1.755000e+11
29,32,24,3,Africa,Angola,B3,Fishing port develop.,Bad,5717.007841,0,...,0.446,3,Middle Africa,17.237553,-13.299091,0,19088106,0.526,Low,1.755000e+11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1806,1957,882,5,Oceania,Samoa,B4,Markt. & storage infrast.,Bad,0.000000,0,...,NaN,114,Polynesia,-172.333333,-13.583333,1,196628,0.694,High,9.950000e+08
1807,1958,882,5,Oceania,Samoa,B5,Tax exemption,Bad,1717.047093,0,...,NaN,114,Polynesia,-172.333333,-13.583333,1,196628,0.694,High,9.950000e+08
1808,1959,882,5,Oceania,Samoa,B6,Fishing access,Bad,0.000000,0,...,NaN,114,Polynesia,-172.333333,-13.583333,1,196628,0.694,High,9.950000e+08
1809,1961,882,5,Oceania,Samoa,C1,Fisher assistance,Ugly,0.000000,0,...,NaN,114,Polynesia,-172.333333,-13.583333,1,196628,0.694,High,9.950000e+08
1810,1962,882,5,Oceania,Samoa,C2,Vessel buyback,Ugly,0.000000,0,...,NaN,114,Polynesia,-172.333333,-13.583333,1,196628,0.694,High,9.950000e+08
1811,1963,882,5,Oceania,Samoa,C3,Rural fisher communities,Ugly,402.787125,0,...,NaN,114,Polynesia,-172.333333,-13.583333,1,196628,0.694,High,9.950000e+08
1812,1964,887,2,Asia,Yemen,A1,Fisheries mangt.,Good,41666.479712,0,...,0.508,152,Western Asia,47.373059,15.990375,0,26052966,0.500,Medium,1.060000e+11
1813,1965,887,2,Asia,Yemen,A2,Fishery R&D,Good,0.000000,0,...,0.508,152,Western Asia,47.373059,15.990375,0,26052966,0.500,Medium,1.060000e+11
1814,1966,887,2,Asia,Yemen,A3,MPAs,Good,NaN,0,...,0.508,152,Western Asia,47.373059,15.990375,0,26052966,0.500,Medium,1.060000e+11
1815,1967,887,2,Asia,Yemen,B1,Boat constsruct. & renov.,Bad,0.000000,0,...,0.508,152,Western Asia,47.373059,15.990375,0,26052966,0.500,Medium,1.060000e+11
1816,1968,887,2,Asia,Yemen,B2,Fisheries dev. projects,Bad,12124.347683,1,...,0.508,152,Western Asia,47.373059,15.990375,0,26052966,0.500,Medium,1.060000e+11
1817,1969,887,2,Asia,Yemen,B3,Fishing port develop.,Bad,0.000000,0,...,0.508,152,Western Asia,47.373059,15.990375,0,26052966,0.500,Medium,1.060000e+11
1818,1970,887,2,Asia,Yemen,B4,Markt. & storage infrast.,Bad,22765.003731,0,...,0.508,152,Western Asia,47.373059,15.990375,0,26052966,0.500,Medium,1.060000e+11
1819,1971,887,2,Asia,Yemen,B5,Tax exemption,Bad,25685.313394,0,...,0.508,152,Western Asia,47.373059,15.990375,0,26052966,0.500,Medium,1.060000e+11
1820,1972,887,2,Asia,Yemen,B6,Fishing access,Bad,0.000000,0,...,0.508,152,Western Asia,47.373059,15.990375,0,26052966,0.500,Medium,1.060000e+11
1821,1974,887,2,Asia,Yemen,C1,Fisher assistance,Ugly,0.000000,0,...,0.508,152,Western Asia,47.373059,15.990375,0,26052966,0.500,Medium,1.060000e+11
1822,1975,887,2,Asia,Yemen,C2,Vessel buyback,Ugly,0.000000,0,...,0.508,152,Western Asia,47.373059,15.990375,0,26052966,0.500,Medium,1.060000e+11
1823,1976,887,2,Asia,Yemen,C3,Rural fisher communities,Ugly,0.000000,0,...,0.508,152,Western Asia,47.373059,15.990375,0,26052966,0.500,Medium,1.060000e+11
1824,1977,891,1,Europe,Montenegro,A1,Fisheries mangt.,Good,47.665463,0,...,NaN,91,Southern Europe,19.466667,42.783333,NaN,620029,0.789,High,3.985000e+09
1825,1978,891,1,Europe,Montenegro,A2,Fishery R&D,Good,0.000000,0,...,NaN,91,Southern Europe,19.466667,42.783333,NaN,620029,0.789,High,3.985000e+09
1826,1979,891,1,Europe,Montenegro,A3,MPAs,Good,24.553596,0,...,NaN,91,Southern Europe,19.466667,42.783333,NaN,620029,0.789,High,3.985000e+09
1827,1980,891,1,Europe,Montenegro,B1,Boat constsruct. & renov.,Bad,0.000000,0,...,NaN,91,Southern Europe,19.466667,42.783333,NaN,620029,0.789,High,3.985000e+09
1828,1981,891,1,Europe,Montenegro,B2,Fisheries dev. projects,Bad,74.870248,0,...,NaN,91,Southern Europe,19.466667,42.783333,NaN,620029,0.789,High,3.985000e+09
1829,1982,891,1,Europe,Montenegro,B3,Fishing port develop.,Bad,0.000000,0,...,NaN,91,Southern Europe,19.466667,42.783333,NaN,620029,0.789,High,3.985000e+09
1830,1983,891,1,Europe,Montenegro,B4,Markt. & storage infrast.,Bad,0.000000,0,...,NaN,91,Southern Europe,19.466667,42.783333,NaN,620029,0.789,High,3.985000e+09
1831,1984,891,1,Europe,Montenegro,B5,Tax exemption,Bad,0.000000,0,...,NaN,91,Southern Europe,19.466667,42.783333,NaN,620029,0.789,High,3.985000e+09
1832,1985,891,1,Europe,Montenegro,B6,Fishing access,Bad,0.000000,0,...,NaN,91,Southern Europe,19.466667,42.783333,NaN,620029,0.789,High,3.985000e+09
1833,1987,891,1,Europe,Montenegro,C1,Fisher assistance,Ugly,0.000000,0,...,NaN,91,Southern Europe,19.466667,42.783333,NaN,620029,0.789,High,3.985000e+09
1834,1988,891,1,Europe,Montenegro,C2,Vessel buyback,Ugly,0.000000,0,...,NaN,91,Southern Europe,19.466667,42.783333,NaN,620029,0.789,High,3.985000e+09
1835,1989,891,1,Europe,Montenegro,C3,Rural fisher communities,Ugly,0.000000,0,...,NaN,91,Southern Europe,19.466667,42.783333,NaN,620029,0.789,High,3.985000e+09

In [128]:
Subsidies2009_subregions_Type = pd.merge(left=Subsidies2009_subregions, right=Type, how='left')

In [129]:
Subsidies2009_Catch = pd.merge(left=Subsidies2009_subregions_Type, right=Catch_Subregions, how='left')

In [130]:
Catch_Subregions.head()

,Region,Developed,Countries,EEZ,Recreational,Subsistence,Artisanal,Industrial,Total_Catch,SSF_Catch,SSF_Catch_percent,CID,Subregion,CLon,CLat,SIDS,TotPop,HDI,Develop,GDP
0,Europe,Developing,Albania,True,0.0,0.0,0.4,4.5,4.9,0.4,8.163265,1,Southern Europe,20.050049,40.934006,0,3020209,0.749,High,3.066000e+10
1,Europe,Developing,Albania,False,0.0,0.0,0.4,4.4,4.8,0.4,8.333333,1,Southern Europe,20.050049,40.934006,0,3020209,0.749,High,3.066000e+10
2,Africa,Developing,Algeria,True,1.1,0.2,89.8,164.7,255.8,90.0,35.183737,2,Northern Africa,2.296145,27.940730,0,38813722,0.717,Medium,5.626000e+11
3,Africa,Developing,Algeria,False,1.1,0.2,89.8,156.7,247.8,90.0,36.319613,2,Northern Africa,2.296145,27.940730,0,38813722,0.717,Medium,5.626000e+11
4,Africa,Developing,Angola,True,0.1,63.7,156.1,273.2,493.1,219.8,44.575137,3,Middle Africa,17.237553,-13.299091,0,19088106,0.526,Low,1.755000e+11

In [131]:
Subsidies2009_subregions_Type.head()

,ID,Cnumber,RegionID,RegionName,Countries,Type,SubType,Category,ReEst_Subsidy2009,NewData,...,CID,Subregion,CLon,CLat,SIDS,TotPop,HDI,Develop,GDP,EEZ
0,1,8,1,Europe,Albania,A1,Fisheries mangt.,Good,387.260735,0,...,1,Southern Europe,20.050049,40.934006,0,3020209,0.749,High,30660000000,True
1,2,8,1,Europe,Albania,A2,Fishery R&D,Good,198.557500,0,...,1,Southern Europe,20.050049,40.934006,0,3020209,0.749,High,30660000000,True
2,3,8,1,Europe,Albania,A3,MPAs,Good,58.941816,0,...,1,Southern Europe,20.050049,40.934006,0,3020209,0.749,High,30660000000,True
3,4,8,1,Europe,Albania,B1,Boat constsruct. & renov.,Bad,0.000000,0,...,1,Southern Europe,20.050049,40.934006,0,3020209,0.749,High,30660000000,False
4,5,8,1,Europe,Albania,B2,Fisheries dev. projects,Bad,472.011572,0,...,1,Southern Europe,20.050049,40.934006,0,3020209,0.749,High,30660000000,False

In [132]:
list(Subsidies2009_subregions_Type.columns.values)

['ID',
 'Cnumber',
 'RegionID',
 'RegionName',
 'Countries',
 'Type',
 'SubType',
 'Category',
 'ReEst_Subsidy2009',
 'NewData',
 'Developed',
 'HDI_2005',
 'CID',
 'Subregion',
 'CLon',
 'CLat',
 'SIDS',
 'TotPop',
 'HDI',
 'Develop',
 'GDP',
 'EEZ']

In [133]:
list(Catch_Subregions.columns.values)

['Region',
 'Developed',
 'Countries',
 'EEZ',
 'Recreational',
 'Subsistence',
 'Artisanal',
 'Industrial',
 'Total_Catch',
 'SSF_Catch',
 'SSF_Catch_percent',
 'CID',
 'Subregion',
 'CLon',
 'CLat',
 'SIDS',
 'TotPop',
 'HDI',
 'Develop',
 'GDP']

In [134]:
list(Subsidies2009_Catch.columns.values)

['ID',
 'Cnumber',
 'RegionID',
 'RegionName',
 'Countries',
 'Type',
 'SubType',
 'Category',
 'ReEst_Subsidy2009',
 'NewData',
 'Developed',
 'HDI_2005',
 'CID',
 'Subregion',
 'CLon',
 'CLat',
 'SIDS',
 'TotPop',
 'HDI',
 'Develop',
 'GDP',
 'EEZ',
 'Region',
 'Recreational',
 'Subsistence',
 'Artisanal',
 'Industrial',
 'Total_Catch',
 'SSF_Catch',
 'SSF_Catch_percent']

In [135]:
Subsidies2009_Catch

,ID,Cnumber,RegionID,RegionName,Countries,Type,SubType,Category,ReEst_Subsidy2009,NewData,...,GDP,EEZ,Region,Recreational,Subsistence,Artisanal,Industrial,Total_Catch,SSF_Catch,SSF_Catch_percent
0,1,8,1,Europe,Albania,A1,Fisheries mangt.,Good,387.260735,0,...,3.066000e+10,True,Europe,0.0,0.0,0.4,4.5,4.9,0.4,8.163265
1,2,8,1,Europe,Albania,A2,Fishery R&D,Good,198.557500,0,...,3.066000e+10,True,Europe,0.0,0.0,0.4,4.5,4.9,0.4,8.163265
2,3,8,1,Europe,Albania,A3,MPAs,Good,58.941816,0,...,3.066000e+10,True,Europe,0.0,0.0,0.4,4.5,4.9,0.4,8.163265
3,4,8,1,Europe,Albania,B1,Boat constsruct. & renov.,Bad,0.000000,0,...,3.066000e+10,False,Europe,0.0,0.0,0.4,4.4,4.8,0.4,8.333333
4,5,8,1,Europe,Albania,B2,Fisheries dev. projects,Bad,472.011572,0,...,3.066000e+10,False,Europe,0.0,0.0,0.4,4.4,4.8,0.4,8.333333
5,6,8,1,Europe,Albania,B3,Fishing port develop.,Bad,107.025943,0,...,3.066000e+10,False,Europe,0.0,0.0,0.4,4.4,4.8,0.4,8.333333
6,7,8,1,Europe,Albania,B4,Markt. & storage infrast.,Bad,152.502950,0,...,3.066000e+10,False,Europe,0.0,0.0,0.4,4.4,4.8,0.4,8.333333
7,8,8,1,Europe,Albania,B5,Tax exemption,Bad,0.000000,0,...,3.066000e+10,False,Europe,0.0,0.0,0.4,4.4,4.8,0.4,8.333333
8,9,8,1,Europe,Albania,B6,Fishing access,Bad,0.000000,0,...,3.066000e+10,False,Europe,0.0,0.0,0.4,4.4,4.8,0.4,8.333333
9,11,8,1,Europe,Albania,C1,Fisher assistance,Ugly,0.000000,0,...,3.066000e+10,False,Europe,0.0,0.0,0.4,4.4,4.8,0.4,8.333333
10,12,8,1,Europe,Albania,C2,Vessel buyback,Ugly,0.000000,0,...,3.066000e+10,False,Europe,0.0,0.0,0.4,4.4,4.8,0.4,8.333333
11,13,8,1,Europe,Albania,C3,Rural fisher communities,Ugly,0.000000,0,...,3.066000e+10,False,Europe,0.0,0.0,0.4,4.4,4.8,0.4,8.333333
12,14,12,3,Africa,Algeria,A1,Fisheries mangt.,Good,72.985872,0,...,5.626000e+11,True,Africa,1.1,0.2,89.8,164.7,255.8,90.0,35.183737
13,15,12,3,Africa,Algeria,A2,Fishery R&D,Good,1925.441376,0,...,5.626000e+11,True,Africa,1.1,0.2,89.8,164.7,255.8,90.0,35.183737
14,16,12,3,Africa,Algeria,A3,MPAs,Good,753.613072,0,...,5.626000e+11,True,Africa,1.1,0.2,89.8,164.7,255.8,90.0,35.183737
15,17,12,3,Africa,Algeria,B1,Boat constsruct. & renov.,Bad,0.000000,0,...,5.626000e+11,False,Africa,1.1,0.2,89.8,156.7,247.8,90.0,36.319613
16,18,12,3,Africa,Algeria,B2,Fisheries dev. projects,Bad,598.465491,1,...,5.626000e+11,False,Africa,1.1,0.2,89.8,156.7,247.8,90.0,36.319613
17,19,12,3,Africa,Algeria,B3,Fishing port develop.,Bad,863.183032,0,...,5.626000e+11,False,Africa,1.1,0.2,89.8,156.7,247.8,90.0,36.319613
18,20,12,3,Africa,Algeria,B4,Markt. & storage infrast.,Bad,1478.844056,0,...,5.626000e+11,False,Africa,1.1,0.2,89.8,156.7,247.8,90.0,36.319613
19,21,12,3,Africa,Algeria,B5,Tax exemption,Bad,0.000000,0,...,5.626000e+11,False,Africa,1.1,0.2,89.8,156.7,247.8,90.0,36.319613
20,22,12,3,Africa,Algeria,B6,Fishing access,Bad,0.000000,0,...,5.626000e+11,False,Africa,1.1,0.2,89.8,156.7,247.8,90.0,36.319613
21,24,12,3,Africa,Algeria,C1,Fisher assistance,Ugly,0.000000,0,...,5.626000e+11,False,Africa,1.1,0.2,89.8,156.7,247.8,90.0,36.319613
22,25,12,3,Africa,Algeria,C2,Vessel buyback,Ugly,0.000000,0,...,5.626000e+11,False,Africa,1.1,0.2,89.8,156.7,247.8,90.0,36.319613
23,26,12,3,Africa,Algeria,C3,Rural fisher communities,Ugly,391.410826,0,...,5.626000e+11,False,Africa,1.1,0.2,89.8,156.7,247.8,90.0,36.319613
24,27,24,3,Africa,Angola,A1,Fisheries mangt.,Good,18410.390367,0,...,1.755000e+11,True,Africa,0.1,63.7,156.1,273.2,493.1,219.8,44.575137
25,28,24,3,Africa,Angola,A2,Fishery R&D,Good,825.875616,1,...,1.755000e+11,True,Africa,0.1,63.7,156.1,273.2,493.1,219.8,44.575137
26,29,24,3,Africa,Angola,A3,MPAs,Good,1037.353000,0,...,1.755000e+11,True,Africa,0.1,63.7,156.1,273.2,493.1,219.8,44.575137
27,30,24,3,Africa,Angola,B1,Boat constsruct. & renov.,Bad,44923.938932,0,...,1.755000e+11,False,Africa,0.1,63.7,156.1,257.4,477.3,219.8,46.050702
28,31,24,3,Africa,Angola,B2,Fisheries dev. projects,Bad,38847.837016,1,...,1.755000e+11,False,Africa,0.1,63.7,156.1,257.4,477.3,219.8,46.050702
29,32,24,3,Africa,Angola,B3,Fishing port develop.,Bad,5717.007841,0,...,1.755000e+11,False,Africa,0.1,63.7,156.1,257.4,477.3,219.8,46.050702
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1806,1957,882,5,Oceania,Samoa,B4,Markt. & storage infrast.,Bad,0.000000,0,...,9.950000e+08,False,Oceania,0.0,10.1,4.6,3.1,17.8,14.7,82.584270
1807,1958,882,5,Oceania,Samoa,B5,Tax exemption,Bad,1717.047093,0,...,9.950000e+08,False,Oceania,0.0,10.1,4.6,3.1,17.8,14.7,82.584270
1808,1959,882,5,Oceania,Samoa,B6,Fishing access,Bad,0.000000,0,...,9.950000e+08,False,Oceania,0.0,10.1,4.6,3.1,17.8,14.7,82.584270
1809,1961,882,5,Oceania,Samoa,C1,Fisher assistance,Ugly,0.000000,0,...,9.950000e+08,False,Oceania,0.0,10.1,4.6,3.1,17.8,14.7,82.584270
1810,1962,882,5,Oceania,Samoa,C2,Vessel buyback,Ugly,0.000000,0,...,9.950000e+08,False,Oceania,0.0,10.1,4.6,3.1,17.8,14.7,82.584270
1811,1963,882,5,Oceania,Samoa,C3,Rural fisher communities,Ugly,402.787125,0,...,9.950000e+08,False,Oceania,0.0,10.1,4.6,3.1,17.8,14.7,82.584270
1812,1964,887,2,Asia,Yemen,A1,Fisheries mangt.,Good,41666.479712,0,...,1.060000e+11,True,Asia,0.0,25.8,227.4,22.8,276.0,253.2,91.739130
1813,1965,887,2,Asia,Yemen,A2,Fishery R&D,Good,0.000000,0,...,1.060000e+11,True,Asia,0.0,25.8,227.4,22.8,276.0,253.2,91.739130
1814,1966,887,2,Asia,Yemen,A3,MPAs,Good,NaN,0,...,1.060000e+11,True,Asia,0.0,25.8,227.4,22.8,276.0,253.2,91.739130
1815,1967,887,2,Asia,Yemen,B1,Boat constsruct. & renov.,Bad,0.000000,0,...,1.060000e+11,False,Asia,0.0,25.8,227.4,69.4,322.6,253.2,78.487291
1816,1968,887,2,Asia,Yemen,B2,Fisheries dev. projects,Bad,12124.347683,1,...,1.060000e+11,False,Asia,0.0,25.8,227.4,69.4,322.6,253.2,78.487291
1817,1969,887,2,Asia,Yemen,B3,Fishing port develop.,Bad,0.000000,0,...,1.060000e+11,False,Asia,0.0,25.8,227.4,69.4,322.6,253.2,78.487291
1818,1970,887,2,Asia,Yemen,B4,Markt. & storage infrast.,Bad,22765.003731,0,...,1.060000e+11,False,Asia,0.0,25.8,227.4,69.4,322.6,253.2,78.487291
1819,1971,887,2,Asia,Yemen,B5,Tax exemption,Bad,25685.313394,0,...,1.060000e+11,False,Asia,0.0,25.8,227.4,69.4,322.6,253.2,78.487291
1820,1972,887,2,Asia,Yemen,B6,Fishing access,Bad,0.000000,0,...,1.060000e+11,False,Asia,0.0,25.8,227.4,69.4,322.6,253.2,78.487291
1821,1974,887,2,Asia,Yemen,C1,Fisher assistance,Ugly,0.000000,0,...,1.060000e+11,False,Asia,0.0,25.8,227.4,69.4,322.6,253.2,78.487291
1822,1975,887,2,Asia,Yemen,C2,Vessel buyback,Ugly,0.000000,0,...,1.060000e+11,False,Asia,0.0,25.8,227.4,69.4,322.6,253.2,78.487291
1823,1976,887,2,Asia,Yemen,C3,Rural fisher communities,Ugly,0.000000,0,...,1.060000e+11,False,Asia,0.0,25.8,227.4,69.4,322.6,253.2,78.487291
1824,1977,891,1,Europe,Montenegro,A1,Fisheries mangt.,Good,47.665463,0,...,3.985000e+09,True,Europe,0.3,0.4,0.1,1.0,1.8,0.5,27.777778
1825,1978,891,1,Europe,Montenegro,A2,Fishery R&D,Good,0.000000,0,...,3.985000e+09,True,Europe,0.3,0.4,0.1,1.0,1.8,0.5,27.777778
1826,1979,891,1,Europe,Montenegro,A3,MPAs,Good,24.553596,0,...,3.985000e+09,True,Europe,0.3,0.4,0.1,1.0,1.8,0.5,27.777778
1827,1980,891,1,Europe,Montenegro,B1,Boat constsruct. & renov.,Bad,0.000000,0,...,3.985000e+09,False,Europe,0.3,0.4,0.1,0.7,1.5,0.5,33.333333
1828,1981,891,1,Europe,Montenegro,B2,Fisheries dev. projects,Bad,74.870248,0,...,3.985000e+09,False,Europe,0.3,0.4,0.1,0.7,1.5,0.5,33.333333
1829,1982,891,1,Europe,Montenegro,B3,Fishing port develop.,Bad,0.000000,0,...,3.985000e+09,False,Europe,0.3,0.4,0.1,0.7,1.5,0.5,33.333333
1830,1983,891,1,Europe,Montenegro,B4,Markt. & storage infrast.,Bad,0.000000,0,...,3.985000e+09,False,Europe,0.3,0.4,0.1,0.7,1.5,0.5,33.333333
1831,1984,891,1,Europe,Montenegro,B5,Tax exemption,Bad,0.000000,0,...,3.985000e+09,False,Europe,0.3,0.4,0.1,0.7,1.5,0.5,33.333333
1832,1985,891,1,Europe,Montenegro,B6,Fishing access,Bad,0.000000,0,...,3.985000e+09,False,Europe,0.3,0.4,0.1,0.7,1.5,0.5,33.333333
1833,1987,891,1,Europe,Montenegro,C1,Fisher assistance,Ugly,0.000000,0,...,3.985000e+09,False,Europe,0.3,0.4,0.1,0.7,1.5,0.5,33.333333
1834,1988,891,1,Europe,Montenegro,C2,Vessel buyback,Ugly,0.000000,0,...,3.985000e+09,False,Europe,0.3,0.4,0.1,0.7,1.5,0.5,33.333333
1835,1989,891,1,Europe,Montenegro,C3,Rural fisher communities,Ugly,0.000000,0,...,3.985000e+09,False,Europe,0.3,0.4,0.1,0.7,1.5,0.5,33.333333

In [136]:
subsidiesSSF = subsidies.loc[:,['RegionName', 'Countries', 'Type', 'SSF_USD_1000','weighted_by_sectorsize', 'Data_group']]

In [137]:
subsidiesSSF

,RegionName,Countries,Type,SSF_USD_1000,weighted_by_sectorsize,Data_group
0,Asia,Philippines,A1,43084.605195,TRUE,3
1,Asia,Philippines,A2,27240.860867,TRUE,3
2,Asia,Philippines,A3,4106.020784,TRUE,3
3,Asia,Philippines,B1,74318.064163,TRUE,3
4,Asia,Philippines,B2,1525.321511,TRUE,3
5,Asia,Philippines,B3,NaN,NaN,NaN
6,Asia,Philippines,B4,461.093622,FALSE,1
7,Asia,Philippines,B5,0.000000,FALSE,2
8,Asia,Philippines,B6,NaN,NaN,NaN
9,Asia,Philippines,C1,35605.265432,FALSE,1
10,Asia,Philippines,C2,NaN,NaN,NaN
11,Asia,Philippines,C3,21737.044519,FALSE,1
12,Asia,India,A1,2733.696798,TRUE,3
13,Asia,India,A2,904.297382,TRUE,3
14,Asia,India,A3,755.169097,TRUE,3
15,Asia,India,B1,0.000000,FALSE,2
16,Asia,India,B2,750.266949,FALSE,1
17,Asia,India,B3,690.545089,FALSE,1
18,Asia,India,B4,1008.848853,FALSE,1
19,Asia,India,B5,24791.481252,FALSE,1
20,Asia,India,B6,NaN,NaN,NaN
21,Asia,India,C1,2110.027391,TRUE,3
22,Asia,India,C2,NaN,NaN,NaN
23,Asia,India,C3,2905.485033,FALSE,1
24,Asia,Thailand,A1,7838.119773,TRUE,3
25,Asia,Thailand,A2,280.398288,TRUE,3
26,Asia,Thailand,A3,1219.526338,TRUE,3
27,Asia,Thailand,B1,14614.017187,FALSE,1
28,Asia,Thailand,B2,32.942722,TRUE,3
29,Asia,Thailand,B3,0.000000,FALSE,2
...,...,...,...,...,...,...
774,Europe,Romania,B4,334.028225,1,3
775,Europe,Romania,B5,0.616608,1,3
776,Europe,Romania,B6,NaN,NaN,NaN
777,Europe,Romania,C1,0.137360,1,3
778,Europe,Romania,C2,NaN,NaN,NaN
779,Europe,Romania,C3,NaN,NaN,NaN
780,Europe,Ukraine,A1,931.051851,1,3
781,Europe,Ukraine,A2,NaN,NaN,NaN
782,Europe,Ukraine,A3,83.997446,1,3
783,Europe,Ukraine,B1,490.711108,1,3
784,Europe,Ukraine,B2,0.195199,1,3
785,Europe,Ukraine,B3,NaN,NaN,NaN
786,Europe,Ukraine,B4,NaN,NaN,NaN
787,Europe,Ukraine,B5,NaN,NaN,NaN
788,Europe,Ukraine,B6,NaN,NaN,NaN
789,Europe,Ukraine,C1,NaN,NaN,NaN
790,Europe,Ukraine,C2,NaN,NaN,NaN
791,Europe,Ukraine,C3,1218.802917,0,3
792,Europe,Denmark,A1,2161.395224,1,3
793,Europe,Denmark,A2,972.828311,1,3
794,Europe,Denmark,A3,2126.408163,1,3
795,Europe,Denmark,B1,1802.581051,1,3
796,Europe,Denmark,B2,NaN,NaN,NaN
797,Europe,Denmark,B3,NaN,NaN,NaN
798,Europe,Denmark,B4,3329.290973,0,2
799,Europe,Denmark,B5,NaN,NaN,NaN
800,Europe,Denmark,B6,0.000000,1,3
801,Europe,Denmark,C1,1203.295117,0,2
802,Europe,Denmark,C2,0.000000,0,3
803,Europe,Denmark,C3,NaN,NaN,NaN